### ISSUE TITLE
netlrts with replicas leaves zombie processes behind

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1001]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1001*

---
For netlrts-linux-x86_64-iccstatic/tests/charm++/megatest
 ./charmrun ++local +p16 ./pgm +replicas 4
will typically leave two zombie processes behind per invocation.
Without +replicas it works fine.

**Comment by bilgeacun** [comment]
*Original date: 2017-02-06 19:28:38*

---
I am unable to reproduce this bug. After megatest run ends with the command above, I do; _killall -9 pgm_ and I get _pgm: no process found_.

**Comment by jcphill** [comment]
*Original date: 2017-02-06 20:09:42*

---
I can confirm it works for me too.  OK to close.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-12 02:30:51*

---
For the sake of diligence, it would be useful to know what commit actually resolved this. There have been about 650 commits since 6.7.0, which was released a few months before this was opened. So, bisection shouldn't take more than 10 commits tested. With each build and test being maybe 3 minutes, and time for scripting and such, that should be doable in under an hour.

**Comment by bilgeacun** [comment]
*Original date: 2017-04-13 18:44:52*

---
Cannot reproduce the problem even with 6.7.0.

**Comment by PhilMiller** [comment]
*Original date: 2017-07-03 13:12:43*

---
Clearing out bugs like this.
