### ISSUE TITLE
charmxi: using reserved keywords fails silently

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1017]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1017*

---
The following code fails silently (no headers are generated):

```
<code>mainmodule module {
  readonly int group;
  mainchare chare {
    entry void entry();
  }
}</code>
```

**Comment by stwhite91** [comment]
*Original date: 2016-06-22 13:47:20*

---
This just bit me, adding a parameter named 'sync' to an entry method. This is a pretty bad error to fail silently on, since we reserve some not uncommon words (local, inline, sync, threaded, exclusive, etc.)

The error is the following and no headers are generated:

Command ../../../../bin/charmxi -orig-file ampi.ci returned error code 1

**Comment by nitbhat** [comment]
*Original date: 2016-08-29 08:01:43*

---
I wasn't able to entirely reproduce this bug. For the code in the bug description, I get a slightly informative command output: 

```
<code class="c++">
STDIN:3:33-20: error: invalid construct
Fatal Error by charmc in directory /Users/nitinbhat/Work/software/charm/tests/charm++/simplearrayhello
   Command ../../../bin/charmxi -orig-file hello.ci returned error code 1
charmc exiting...
</code>
```


This is still good enough infomation indicating the line number. 


For codes like 

```
<code class="c++">
mainmodule group {
...
}
</code>
```


I was able to reporduce the bug. 
The generated error after the fix is: 

```
<code class="c++">
../../../bin/charmc   hello.ci
STDIN:1:12-16: error: Reserved word 'group' used as an identifier
  mainmodule group {
             ^^^^^
}Fatal Error by charmc in directory /dcsdata/home/nbhat4/Work/software/charm/tests/charm++/simplearrayhello
   Command ../../../bin/charmxi -orig-file hello.ci returned error code 1
charmc exiting...
</code>
```



NOTE: In xi-grammer.y, some of the reserved words are commented out from generating errors (like READONLY, PUPABLE, MESSAGE etc). There's a comment saying "Commented reserved words introduce parsing conflicts, so they're currently not handled". Anyone knows what these conflicts are? 
As these are commented out, when these keywords are used, there is no error message displayed.

**Comment by nitbhat** [comment]
*Original date: 2016-08-29 08:02:21*

---
Gerrit link: ~~https://charm.cs.illinois.edu/gerrit/#/c/1816/~~ https://github.com/UIUC-PPL/charm/commit/06293a33bf7bcbb67c1ee27697d4e2c07b23e028

**Comment by nitbhat** [comment]
*Original date: 2016-09-12 01:51:40*

---
Change merged into charm by Sam.
