### ISSUE TITLE
Fixed-size object IDs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#108]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/108*

---
Right now, CkArrayIndex is 12 bytes of index data plus 4 bytes of metadata. This is used throughout the code to identify chare array elements. Message envelopes to array elements must carry the full array index to identify the recipient. Since the number of objects in a system is likely much smaller than the index space can represent, the index space is likely very sparse. We should use a smaller ID number that can fit into a smaller bit space (say 64 bits) to actually identify and address these chare array elements. 

This requires mechanisms to assign and look up object IDs dynamically, and design for how they will be used in the message construction, transmission, and delivery paths. The effect of this work on other parts of the system should be considered.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-25 03:39:58*

---
Notes on architecture and design discussions have been updated in the PPL wiki. Detailed work breakdown will come in the next few days.

**Comment by heyram** [comment]
*Original date: 2013-04-03 14:55:11*

---
Wiki page here:
https://wiki.engr.illinois.edu/x/Vbo1DQ

**Comment by heyram** [comment]
*Original date: 2013-04-05 19:12:19*

---
Phil and I had an initial discussion of high level tasks. This will result in a list of subtasks that will be added to redmine after a second discussion. The objective is to realize the required functionality in an incremental manner. Here are some notes from our discussion. We still need to induce more coherence into this and create a list of tasks.

(1) Bring objid_t into existence. Use in one runtime component
- objid_t definition (intial header file, typedefs, bit masks, basic functions etc)
- add a new extradata struct that will carry objid_t
- chare array size metadata should be stored and accessible on all PEs (only for the bcast constructor use case)
- idx --> id conversion function
- send and recv paths will still use CkArrayIndex

This should allow objid_t to be used in just the envelope without modifying any of the send/recv software stacks.

(2) Expanding the use cases (needs more elaboration)
- specify array size at construction time via CkArrayOptions despite non-bulk-construction
- compile-time declared size bounds
    -- charmxi declaration syntax
    -- code generation for conversion functions
    -- change generated code to directly call conversion functions when given a CkArrayIndex (rather than runtime querying of idx -- id from locmgr)
    -- change generated chare array constructor to specify conversion function
- user-specified conversion functions
    -- at runtime
    -- at compile-time (with accompanying generated code optimizations)
    -- design discussion for how to deal with id --> idx inversion
- distributed lookup
    -- requires more design discussions

(3) Runtime adoption (from basic inspection of msg delivery software stack)
- blocked by #165
- location cache should be keyed by objid_t (unless vetoed by design discussion for lookup case)
- tracing infrastructure should use objid_t (should be audited first. eg: `getProjectionID()`)
- lb infrastructure should use objid_t (should be audited first. eg: `idx2LDobjid()`)
- fault tolerance infrastructure should use objid_t (should be audited first. specifically look at msg logging, ckobjid.h etc)
- callbacks
- sections (?)
- other use cases yet to be discussed

**Comment by PhilMiller** [comment]
*Original date: 2013-05-01 22:53:50*

---
We didn't actually work out how we were going to weave the basic implementation into the send or receive paths. Are we going to wait until the location manager cleanup work (#165?) is integrated before doing that? If so, we'll need to merge the relevant branches together, or merge one to mainline and continue the other from there. I think what we have so far on `ramv/objid` should be fine to merge (to mainline) if we want to go that route.

**Comment by heyram** [comment]
*Original date: 2013-05-02 16:02:54*

---
Phil Miller wrote:
> We didn't actually work out how we were going to weave the basic implementation into the send or receive paths. Are we going to wait until the location manager cleanup work (#165?) is integrated before doing that? If so, we'll need to merge the relevant branches together, or merge one to mainline and continue the other from there. I think what we have so far on `ramv/objid` should be fine to merge (to mainline) if we want to go that route.

Second that. We should merge what we have on objid so far, because it should not disrupt anything on the mainline.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:03:12*

---
This isn't getting finished and integrated before the release, so push it back.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-28 17:46:38*

---
Known bugs all seem to have been fixed. Remaining functional transitions can happen later.
