### ISSUE TITLE
Converse command line arguments produce false warnings

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1081]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1081*

---
Converse command line arguments are not properly registered during initialization, so using them generates a warning that they are not being parsed by the runtime.
The command line options in convcore.c are +csdLocalMax, +useAbsoluteTime, +nice, +CmiSpinOnIdle, +CmiSleepOnIdle, and +CmiNoProcForComThread.

**Comment by epmikida** [comment]
*Original date: 2016-10-11 21:49:57*

---
There are two separate issues here from what I can tell.

For +nice and +csdLocalMax, they are correctly registered and function fine. The warning prints out when you pass them without an integer argument since they are registered as integer command line options. So here, I think either the general warning needs to be clarified to say that the option may not have been used as intended, or if we try to consume a command line argument that does is not used properly we should spit out an error right then and there. I would lean towards the latter.

For the others, they never seem to be read from the command line (at least for the build im currently using which is netlrts-linux-x86_64). I need to dig a bit further to figure out when and where they are used and therefore where they should be registered to the CLA database.

**Comment by epmikida** [comment]
*Original date: 2016-10-12 19:07:01*

---
+useAbsoluteTime, +CmiSpinOnIdle, +CmiSleepOnIdle, and +CmiNoProcForComThread are all SMP options, and when running with the SMP build the warning does not show up as expected.

In summary, all of the above options seem to be registered correctly, and the warning functions as expected. The only thing that should change is that if an option that expects an int isn't given an int, there should be an error. I'm pretty sure that the Charm++ options do something like that, so the same functionality should be added for Converse options. I'll look to add that some time this week probably.

**Comment by epmikida** [comment]
*Original date: 2016-10-12 19:12:07*

---
There already exists code in convcore.c that is supposed to make sure that arguments expecting an int actually are given that int, but it no longer seems to work. Fixing this code should fix this bug.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 20:02:13*

---
I'm going to take a quick look at this, and if I can't just nail it down, we should defer it. If we've lived with it for the past year, it's not a reason to hold the bug-fix release.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 20:23:32*

---
~~https://charm.cs.illinois.edu/gerrit/3091~~ https://github.com/UIUC-PPL/charm/commit/329e0989f2133be4600e9b005e6ea37a7ea9d540
