### ISSUE TITLE
Test and merge section ID and manager work

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#109]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/109*

---
Work on compact section IDs and the related management infrastructure was done ages ago. Get it integrated.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:44:48*

---
Inactive for 3 months. Please update the status - are there roadblocks in the integration?

**Comment by PhilMiller** [comment]
*Original date: 2015-07-16 19:19:47*

---
What branch is this on? Where can others go to examine it?

**Comment by ericjbohm** [comment]
*Original date: 2016-02-15 21:40:33*

---
ramv/com-kliqs is the branch that contains the code.  I believe we delayed this due to the design collisions with 64bit ID for location management.  

This branch is rather rusty, and includes a few hacks (i.e., changes to mempool) that should probably be nuked from orbit.

A naive attempt to rebase this against charm master will land you in the briar patch of conflicts.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-01 21:18:31*

---
What got merged as a result of this? Is it actually moot due to other changes?
