### ISSUE TITLE
syncft: sporadic ampi/jacobi3d crash due to mis-matched reduction callback

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1118]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1118*

---
https://charm.cs.illinois.edu/autobuild/old.2016_06_29__01_02/netlrts-linux-x86_64-syncft.txt

```
iter 48 elapsed time: 14.429296 time: 0.224982 maxerr: 668.614646
iter 49 elapsed time: 14.656716 time: 0.224970 maxerr: 661.832941
iter 50 elapsed time: 14.889231 time: 0.230784 maxerr: 655.253453
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: mis-matched client callbacks in reduction messages

[0] Stack Traceback:
  [0:0] CmiAbortHelper+0x63  [0x5d01e3]
  [0:1] _ZN14CkReductionMgr14reduceMessagesEv+0x314  [0x5555c4]
  [0:2] _ZN14CkReductionMgr15finishReductionEv+0x110  [0x565010]
  [0:3] _ZN14CkReductionMgr15addContributionEP14CkReductionMsg+0x4e  [0x56561e]
  [0:4] _ZN10ampiParent15startCheckpointEPKc+0x60  [0x4b70b0]
  [0:5] AMPI_Migrate+0x277  [0x4c4b77]
  [0:6] _Z13AMPI_Main_cppiPPc+0xdf2  [0x49c832]
  [0:7] AMPI_Fallback_Main+0x10  [0x4aa9a0]
  [0:8] AMPI_threadstart+0x91  [0x4ae301]
  [0:9]   [0x49fc18]
  [0:10] CthStartThread+0x1e  [0x5ce6ee]
  [0:11] +0x45ce0  [0x7ffff7077ce0]
Fatal error on PE 0> mis-matched client callbacks in reduction messages

make[3]: Leaving directory `/scratch/autobuild/netlrts-linux-x86_64-syncft/charm/netlrts-linux-x86_64-syncft/tests/ampi/jacobi3d'
make[3]: *** [syncfttest] Error 1
```

**Comment by PhilMiller** [comment]
*Original date: 2016-07-10 14:49:11*

---
Another occurrence: https://charm.cs.illinois.edu/autobuild/old.2016_07_10__01_01/netlrts-linux-x86_64-syncft.txt

**Comment by stwhite91** [comment]
*Original date: 2016-07-13 16:56:03*

---
This is the code for the contribution to the reduction that starts the checkpoint and sometimes results in "mis-matched client callbacks in reduction messages":
```
if (thisIndex==0) {
    ckptClientStruct *clientData = new ckptClientStruct(dname, this);
    CkCallback cb(checkpointClient, clientData);
    contribute(0, NULL, CkReduction::sum_int, cb);
}
else
    contribute(0, NULL, CkReduction::sum_int);
```

The issue is that the callback uses a ckptClientStruct that has a pointer to index 0's ampiParent instance, so we only want index 0 to set the callback, not everyone.
Instead of only giving the callback from one contributor and using a dummy sum_int reduction, we would like to set the callback somehow from index 0 and then do an empty CkReduction::random contribution.

**Comment by stwhite91** [comment]
*Original date: 2016-07-13 18:29:46*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1309/~~ https://github.com/UIUC-PPL/charm/commit/4dba04596ceb1b756e2270cb546c659435b2cca3
