### ISSUE TITLE
Don't require autoconf to be installed on user systems for hwloc build

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1175]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1175*

---
No body.

**Comment by pplimport** [comment]
*Original author: Gengbin Zheng*
*Original date: 2016-09-02 02:15:57*

---
it seems some systems requires autoconf. It seems that there is some issue with hwloc's default configure script that does not work well with embedded build. It sometimes works, sometimes not. I don't know the reason. 

Most systems has "autogen.sh" script which calls autoreconf, same as we do here.
I could create an autogen.sh that calls autoreconf so that it looks more like a common practice. User still needs to have autoconf installed, which is a common. I don't see why that would be a problem.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 19:10:13*

---
We can revisit this later, then. The other code changes shouldn't interact with it.

**Comment by evan-charmworks** [comment]
*Original date: 2017-10-27 20:59:58*

---
I believe the merge of package-tarball.sh completes this task.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-27 21:16:52*

---
Agreed, ~~https://charm.cs.illinois.edu/gerrit/#/c/3041/~~ https://github.com/UIUC-PPL/charm/commit/598e21e68cfb562a9955c234af3b701be3f08f39 resolves this
