### ISSUE TITLE
AMPI_Just_migrated callbacks break using tlsglobals/isomalloc

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1214]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1214*

---
AMPI doesn't properly take care of turning on/off isomalloc and tlsglobals before calling the user's justMigrated function.

**Comment by stwhite91** [comment]
*Original date: 2016-09-20 04:36:30*

---
https://charm.cs.illinois.edu/gerrit/#/c/1865/

**Comment by stwhite91** [comment]
*Original date: 2016-09-20 22:13:20*

---
This is tricky, because we need to create an instance of TCharmAPIRoutine from the user's thread only after their about_to_migrate routine has executed, and we need to destruct that instance right before their just_migrated function executes. Also, there seem to be deeper issues with tlsglobals+isomalloc...

**Comment by stwhite91** [comment]
@evan-charmworks could you take a look at this? You've been touching the TLS/Isomalloc (de)activation code recently so probably have a better handle on this

**Comment by evan-charmworks** [comment]
Addressed in #2524

**Comment by evan-charmworks** [comment]
I had to back the fix for this out of #2524 because it was failing validation, holding back the rest of the patch. It is a separate commit now on its own branch, and I will make a PR after the refactor is merged.

As I see it, `AMPI_Register_about_to_migrate` and `AMPI_Register_just_migrated` are semantically invalid at present. When they are called, no globals are privatized, any Isomalloc heap in use is not active (both mentioned as part of this issue), and no MPI calls may be made because the `_curTCharm` and `ampiPtr` globals are null. Even with these three things addressed, calls to `MPI_Comm_rank` in `just_migrated` may error out with `AMPI's getAmpiInstance> null pointer` because while `ampiParent::ckJustMigrated` can restore the things mentioned so far, `MPI_Comm_rank` calls `getAmpiInstance`, which calls `ampiParent::comm2ampi`, and the `worldPtr` that would be returned by that function is only restored by `ampi::ckJustMigrated` --> `ampi::findParent` --> `ampiParent::registerAmpi`, not `ampiParent::ckJustMigrated`.

@stwhite91 Do you know why `ampi` and `ampiParent` are separate classes?

**Comment by stwhite91** [comment]
Yes, these callbacks are extremely limited and almost useless as is.

ampi and ampiParent are separate chare array classes. The ampiParent chare array corresponds to the AMPI rank itself, whereas the ampi chare array corresponds to a specific communicator or an AMPI rank, so each rank always has multiple ampi instances (MPI_COMM_WORLD and MPI_COMM_SELF to start). So ampiParent is supposed to manage things that are defined across communicators (ops, datatypes, etc), and ampi is supposed to be per-communicator state (message matching, virtual topology, etc).

**Comment by evan-charmworks** [comment]
Even if these callbacks were fully functional, what would they be good for beyond diagnostic messages? Wouldn't any program that uses them for their control flow no longer work with conventional MPI implementations?

Separate question: Should we rename `ampiParent` and `ampi` to something like `ampiRank` and `ampiComm`, respectively?

**Comment by matthiasdiener** [comment]
> Even if these callbacks were fully functional, what would they be good for beyond diagnostic messages? Wouldn't any program that uses them for their control flow no longer work with conventional MPI implementations?

The only use for this I can imagine is to allow the application to implement some like MPI_Win_allocate_shared, to invalidate the communicator after migration (see also #1449). However, this doesn't seem to a hard requirement (the application could just invalidate the communicator after AMPI_Migrate?).

> 
> Separate question: Should we rename `ampiParent` and `ampi` to something like `ampiRank` and `ampiComm`, respectively?

+1. Also, Sam's explanation could be added as a comment.

**Comment by stwhite91** [comment]
The control flow only affects programs which use AMPI_Migrate(), which is already not something that works with traditional MPI libraries. So this is just another thing you need to ifdef out when not using AMPI. 

They are usual for diagnostics, when debugging migration issues, but the most practical use case for aboutToMigrate and justMigrated at the application level is for avoiding making copies of data during migration that users can generate a priori rather than PUPing. This is an optimization that Isomalloc for instance doesn't do since it treats all user allocations the same. That being said, we don't have any users of this interface anymore (in the early years of XPACC we used PUP for migration in PlasComCM and we added this API for that... Isomalloc wasn't yet portable enough for us to use and we didn't need {swap/tls}globals).

I'm fine with renaming them. There's also something called an ampiCommStruct that is a part of the ampi class.
