### ISSUE TITLE
Autobuild script not actually checking for successful execution/transfer/etc.

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#124]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/124*

---
[[http://charm.cs.illinois.edu/autobuild/old.2013_03_21__03_32/gni-crayxc.txt]]

Nikhil - if this autobuild maintenance should be offloaded to someone else, reassign.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-21 23:42:50*

---
This could, I guess, be a case of the build and test actually being successful, but none of the output getting captured. I doubt that simply because I know the code crashes in particular tests on Edison, or anyplace else using recent ICC on Cray.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-22 04:07:24*

---
I had coded autobuild to accept exit code 255 from rsync as a success since rsync threw that error even when successful (possibly because of some weird interplay with ControlMaster). What you saw was an artifact of that - for some transfers, rsync returned 255 on network connection failure; in those cases, it reported success! I have changed it to ignore the exit code of 255 only for the final copy (from the target to us since by then we know that the build is successful).

**Comment by PhilMiller** [comment]
*Original date: 2013-03-22 04:13:26*

---
As a double-check against this kind of thing cropping up in the future, might it be worthwhile to add a checksum of the tarball on the build/test system, and repeat that checksum after the transfer to confirm that it got the same bits on the receiving end? I'm thinking md5sum or the like, which should be relatively quick compared to the build itself.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-22 18:55:00*

---
It looks like some builds are now doing just fine, but still coming up with 255 from rsync and thus not showing as 'Good'. We may have to do the fallback-to-checksum thing after all.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-22 19:06:52*

---
Ah, I forgot to ignore at the place that mattered the most - copy from remote to poise after completion. Done that now.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-24 15:47:47*

---
It looks like most of these problems have been covered now. The exception seems to be the copy of the charm source tree from poise to challenger.
