### ISSUE TITLE
mlogft and causalft builds do not compile

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1244]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1244*

---
Trying to build netlrts-linux-x86_64 mlogft fails with many errors like the following:
```
error: no viable conversion from 'const CkArrayIndex' to 'const CmiUInt8'

```

**Comment by stwhite91** [comment]
*Original date: 2016-10-04 20:30:48*

---
mlogft builds may have been broken before 64bit ID based on some of the errors I'm seeing...

causalft builds are similarly broken...

**Comment by stwhite91** [comment]
*Original date: 2017-02-16 00:13:09*

---
It would be good for these to at least compile in the release.

**Comment by epmikida** [comment]
*Original date: 2017-02-16 00:33:29*

---
A large number of the issues look to be in src/ck-core/ckobjid.h, which wasn't updated to use a 64bit ID instead of an index. If the array branch of the union is changed to use a 64bit ID and the operators are defined appropriately I think that will solve a lot of issues from the 64bit merge. There are a couple places where the mlog code passes and index when an ID is expected as well, but the ID should be readily available in those places.

**Comment by evan-charmworks** [comment]
mlogft and causalft have been removed.
