### ISSUE TITLE
Document LLVM OpenMP runtime integration

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1265]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1265*

---
Add something to the manual about this, and add an example/test program to the source

**Comment by stwhite91** [comment]
*Original date: 2016-12-18 22:44:50*

---
We need a list of compilers/versions that are known to work with it, instructions on building the runtime support, compiling/linking applications (-module OmpCharm), an example Charm++/OpenMP program, and explanation of any tuning knobs exposed to the application...

Also disambiguate charmc's existing '-openmp' flag from the our OpenMP runtime support.

**Comment by stwhite91** [comment]
*Original date: 2017-03-05 19:06:10*

---
bump

**Comment by PhilMiller** [comment]
*Original date: 2017-03-14 23:40:14*

---
The existing `-openmp` flag should backend to the integrated support when the runtime has been built with the `omp` option. I got rather confused in trying to use it and finding that it didn't.

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 15:36:46*

---
This should be easy, so bumping priority.

**Comment by sbak5** [comment]
*Original date: 2017-04-17 08:24:48*

---
Sam White wrote:
> This should be easy, so bumping priority.

Some APIs and build,charmc and other changes will be included in this patch.

**Comment by sbak5** [comment]
*Original date: 2017-04-24 05:06:44*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2427/~~ https://github.com/UIUC-PPL/charm/commit/e3c158eab740ede270acfaacd3b2a32bdc7a1fe6

Completed documentation and add examples to show how to build and use the Integrated OpenMP.

Added an environment routine for the number of created OpenMP threads in the latest OpenMP region. 

Added an example. 

'-fopenmp' is included in default compiler flags when the charm++ is built with omp for gcc and icc. 

For clang, -fopenmp is not included in default. BG clang includes this compiler flag but  clang on linux should include -fopenmp separately. 

The reason why I adopted this ambiguous rule for the openmp flag is users can use clang on linux but if they're working in linux where the default version of clang is older than 3.7(first version of clang supporting OpenMP), they should install both clang and OpenMP runtime library separately. 

For example, on Ubuntu, clang higher than 3.7 has been installed in default since 15.10. 

If you want to use OpenMP with clang on ubuntu lower than 15.10, you can do with the following instructions. 

sudo apt-get install clang-3.8 
sudo apt-get install libiomp5 (intel's openmp runtime library)

sudo ln -svT /usr/bin/clang-3.8 /usr/bin/clang
sudo ln -svT /usr/bin/clang++-3.8 /usr/bin/clang++

when you build your applications with OpenMP, you should add '-fopenmp=libiomp5' instead of '-fopenmp' 

-fopenmp tries to link 'libomp' so it fails. (Installed clang doesn't include 'libomp' )
