### ISSUE TITLE
Align XL-specific conditional compilation TRAM to relevant versions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1311]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1311*

---
We need testing of the XL compiler on Crest to see whether it references standard libraries that contain `std::unordered_map` and whether it has fixed the bug that prevented compiling TRAM under BGQ XLC. Then adjust the compilation flags accordingly.

**Comment by stwhite91** [comment]
*Original date: 2017-08-02 17:18:00*

---
If we're requiring C++11 support in 6.9.0 does this issue go away?

**Comment by stwhite91** [comment]
*Original date: 2017-10-31 13:51:38*

---
TRAM needs to be tested on the XLC on Summit-dev now without the #if CMK_USING_XLC's in charmxi's generated code


Related:
~~https://charm.cs.illinois.edu/gerrit/#/c/3183/~~ https://github.com/UIUC-PPL/charm/commit/ff94faa7e6268ebb825dc484df21f70e67297e4d
~~https://charm.cs.illinois.edu/gerrit/#/c/3190/~~ https://github.com/UIUC-PPL/charm/commit/e7018d55a99a41a5bee627f98cf7d19d3808becc
~~https://charm.cs.illinois.edu/gerrit/#/c/3189/~~ https://github.com/UIUC-PPL/charm/commit/d4bffe5869a0be23319e93a1e262b6b02a54e6f3

**Comment by rbuch** [comment]
*Original date: 2018-02-01 01:34:43*

---
I think this has already been fixed in ~~https://charm.cs.illinois.edu/gerrit/#/c/3190/~~ https://github.com/UIUC-PPL/charm/commit/e7018d55a99a41a5bee627f98cf7d19d3808becc, but my latest changes fix improve the situation a bit: ~~https://charm.cs.illinois.edu/gerrit/#/c/3603/~~ https://github.com/UIUC-PPL/charm/commit/62e6201779b095d596fb0460144067fa6771e949, ~~https://charm.cs.illinois.edu/gerrit/#/c/3604/~~ https://github.com/UIUC-PPL/charm/commit/5280103c2f87f6bdd1aace399c4b4cba7512f5ce, ~~https://charm.cs.illinois.edu/gerrit/#/c/3605/~~ https://github.com/UIUC-PPL/charm/commit/8fdaae627d7d6ecea206f777272d9cb01c9ab9fc.

One lingering question is if we should remove the {mpi, pami, pamilrts}-bluegeneq conv-mach.sh files (and the other relevant files). They currently define CMK_USING_XLC, which is what all of these new changes is trying to excise. I think this should be done since BG/Q is no longer a relevant target for new versions of Charm++. Any input?
