### ISSUE TITLE
For broadcasts, avoid copies for destination PEs on same node for [nokeep] messages

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1351]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1351*

---
For broadcasts with [nokeep] messages, RTS makes a copy for each PE on the same node.  Copies can be avoided, if the message is read only.

**Comment by stwhite91** [comment]
*Original date: 2017-01-09 04:28:21*

---
Related (or redundant): https://charm.cs.illinois.edu/redmine/issues/1184

**Comment by stwhite91** [comment]
*Original date: 2017-01-11 19:43:49*

---
If you do "grep -r "CMK_BROADCAST_USE" charm/src/* you will see that currently this support is turned off by this macro, because CmiReference() and CmiFree() have no support for thread safety. The first (and possibly only) step to fixing this issue is to make their ref count atomic.
It would be good to have at least that much done by 6.8.0.

**Comment by jcphill** [comment]
*Original date: 2017-01-31 16:55:44*

---
First, all features should have a target version of 6.8.0-beta1 or 6.8.1, not 6.8.0.
Second, even in smp mode it should be possible for all receivers on the same *pe* to share a message, even if each pe on the node has its own copy.
Finally, making the reference count atomic is not the same as a proper fence on message deletion. Rather than altering the behavior of existing generic utility functions you should write new ones that do what you actually want without imposing overhead on existing uses.

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2017-02-06 21:03:04*

---
Seems like all destinations on the same PE do get one copy of the message for a broadcast

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2017-04-13 20:02:31*

---
Unable to reproduce different messages. Seems like for nokeep messages, the RTS does send the same message to each recipient on the same PE. Closing issue.
