### ISSUE TITLE
charmc hardcodes unversioned compiler names

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1353]
*Original author: William Throwe*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1353*

---
charmc always compiles source files using `g++` (or `clang++` or similar).  This means there is no easy way to test code with multiple versions of gcc, which are often installed as something like `g++-5.3.0`.  It would be nice if there were some way to override this, such as respecting the CC and CXX environment variables.

The only workaround I've found for this is creating a directory with a `g++` symlink to the desired version and then putting that at the front of PATH.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 14:21:46*

---
A fix for this, and more generally to enable standard build configuration practices for Charm++, will be available this summer.

If your concern is for application source files, rather than the runtime system itself, note that it is generally possible to use your compiler of choice directly, passing just a suitable `-I/path/to/charm/netlrts-linux-x86_64-whatever/include` argument so it can find the RTS headers. `charmc` then only needs to be used at link time.

If you need to change how Charm++ itself is built, the exact compiler configuration is set in the files `src/arch/<target platform>/conv-mach.sh`, which you could edit as needed.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 14:22:03*

---
Also, my apologies for the slow response to this.

**Comment by pplimport** [comment]
*Original author: William Throwe*
*Original date: 2017-05-16 22:41:16*

---
Unfortunately, I've found that using different compilers for building and linking can cause linking failures, so reducing the use of charmc to link time doesn't help.  (In particular, it seems that gcc-5 fails to link executables using std::thread that were compiled using gcc-6, presumably because they are using different standard library versions.)

**Comment by PhilMiller** [comment]
*Original date: 2017-11-29 21:02:12*

---
Evan: The CMake work ought to facilitate a solution to this as well. Maybe this just needs some documentation on top of that?

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-09 22:19:06*

---
~~https://charm.cs.illinois.edu/gerrit/3815~~ https://github.com/UIUC-PPL/charm/commit/ba80d8c4073514f7ddc7bfe5d1ffc0dad14eafca
