### ISSUE TITLE
Unable to attach to an application it launched

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1373]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1373*

---
Created launch configuration using the built in gui. When "start" is triggered, it was capable of launching the application and capturing stdout.  However, it was unable to display any application details, such as entry methods, or messages.  It crashed when "attach" was triggered with the error message "CcsServer FATAL ERROR: Couldn't parse port number"

Charm 6.8.0, netlrts-linux-x86_64 compiled with --enable-error-checking -O0 _g
OpenAtom built using that charm, also -O0 -g.

**Comment by stwhite91** [comment]
*Original date: 2017-04-05 16:46:23*

---
git bisect showed this commit to be at fault: ~~https://charm.cs.illinois.edu/gerrit/#/c/1903/~~ https://github.com/UIUC-PPL/charm/commit/01b69b0f41ed6ec8d988a5d929bbb85407c71a51

CharmDebug is probably just assuming that chare, group, nodegroup, or readonly's size is an int rather than a size_t...

**Comment by stwhite91** [comment]
*Original date: 2017-04-05 17:06:36*

---
Actually it should be as easy as grep'ing for "ReadonlyInfo" and "ChareInfo" inside charmdebug, changing the size fields passed to them. Those are the only 2 interfaces changed in that commit which are relevant to charmdebug I think.

**Comment by bilgeacun** [comment]
*Original date: 2017-04-05 17:16:28*

---
I've replaced ReadonlyInfo's and ChareTypeInfo's sizes from int to long, but simply doing that hasn't solved the problem. I'm inspecting more on where the size is used. Also, I'm not sure replacing it to long is the best idea but I'm not sure what would be the equivalent of size_t in Java.

**Comment by bilgeacun** [comment]
*Original date: 2017-04-05 17:51:12*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2356~~ https://github.com/UIUC-PPL/charm/commit/d3c7bc69f6eefd07cbf084a41775cf4aeb30f84b

**Comment by bilgeacun** [comment]
*Original date: 2017-04-05 20:22:29*

---
There are more problems with CharmDebug, with this commit being fault: ~~https://charm.cs.illinois.edu/gerrit/#/c/1873/~~ https://github.com/UIUC-PPL/charm/commit/053d2aa45c6ad9d2d590e409cd3b4de87ec9887e6
The problem is size changes similar to the previous one.

**Comment by bilgeacun** [comment]
*Original date: 2017-04-06 15:04:32*

---
Fix to solve the second commit that breaks CharmDebug is implemented here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2362~~ https://github.com/UIUC-PPL/charm/commit/1e3b6bfadb6f00fa19fc8c8046ec843451cadb6c
