### ISSUE TITLE
Document that array creation must occur on PE0

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#1397]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1397*

---
ckNew calls are restricted to PE0 since the 64-bit ID changes were integrated. Document this restriction in the array basics section of the manual. There's also a newly added API to call for array creation asynchronously, with the resulting array ID delivered through a callback. Document that in the intermediate/advanced section, and reference it from the earlier section.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-07 20:46:43*

---
This can't go into a release. Way too disruptive.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-09 22:04:35*

---
Waiting on info from bug reporter. I can't see what's causing problems in the code as it exists.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-21 18:18:12*

---
Unless we hear otherwise, this wasn't actually a problem that was occurring. Something else was conflated with this effect, probably.

**Comment by pplimport** [comment]
*Original author: Jozsef Bakosi (@jbakosi)*
*Original date: 2017-03-22 15:47:42*

---
I finally got around to reproduce this problem with the attached minimal example. This mimics what I'm trying to do: from a driver chare, create an empty array and a group and from the group use insert() to add array entries. Note insert.C:34. If the driver chare is created on PE 0 all is well in both serial and parallel. However, change the Driver chare's PE to, e.g., 1, and run on two PEs and the following assert is generated:


```
<code class="c">
[1] Assertion "CkMyPe() == 0" failed in file ckarray.C line 780.
</code>
```


I don't know if this is a behavior that would be incompatible with design/usability requirements, but this example does reproduce a behavior that was previously correct. Also, even if this is important for you guys to keep it this this way, i.e., array::ckNew() must always be called from PE 0, it is okay, because it appears that there is a simple fix: ensure that the driver is always created on PE 0.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-22 16:27:42*

---
Indeed, this is intended behavior, that does limit usage that was previously allowed. As you note, there's a fairly easy workaround. We need to document this in the manual, as well as the asynchronous interface that lets the array creation call come from any PE, but returns the resulting ID through a callback

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:12*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by stwhite91** [comment]
*Original date: 2017-04-04 21:01:00*

---
Here's the new API that can be used in the case of creation off PE 0: ~~https://charm.cs.illinois.edu/gerrit/#/c/736/~~ https://github.com/UIUC-PPL/charm/commit/d71fcf194fabc8210325c298b6bef79010dd47cc

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2017-04-05 21:55:43*

---
Added documentation
~~https://charm.cs.illinois.edu/gerrit/#/c/2357/~~ https://github.com/UIUC-PPL/charm/commit/1afe4b15537ab1622db5221c703bfd67f71d4be6

**Comment by stwhite91** [comment]
*Original date: 2017-04-06 16:01:32*

---
This hasn't been merged yet, and once it is it should be marked 'merged' since there was something pushed into the repo
