### ISSUE TITLE
TaskQ logic for randomly choosing a victim PE that is not self is incorrect

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1399]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1399*

---
Sanjay discovered this: the logic for randomly choosing a PE that is not self is wrong because it compares a global PE # to a node-local PE # (modulo node size):

```
int random_pe = CrnRand() % CkMyNodeSize();
  while (random_pe == CkMyPe()) {
    random_pe = CrnRand() % CkMyNodeSize();
  }
```

It is probably not even worth adding the check against the self PE #, because checking the empty local deque is probably faster than checking against the PE #, and it shouldn't cause any other issues.

**Comment by sbak5** [comment]
*Original date: 2017-02-06 20:42:15*

---
Yeah, this is not correct. 

Probably, stealing happens more frequently if this is fixed. (In the previous codes, it is highly possible that the randomly picked local PE number is different from the global PE num.)
-> All the PEs whose global PE number is larger than the size of a node should pass this condition. 

Removed the while loop and added condition so that it doesn't try to steal a task from its local task queue and push it to the queue again.
(When a thread starts stealing, it means its task queue is empty so it is meaningless to steal a task from its own queue)

**Comment by PhilMiller** [comment]
*Original date: 2017-02-09 20:32:22*

---
~~https://charm.cs.illinois.edu/gerrit/2206~~ https://github.com/UIUC-PPL/charm/commit/b34ad14ddbdd404517a00bb561c2864acfc12ac4
