### ISSUE TITLE
Various Mac clang warnings are likely bugs

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1413]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1413*

---
The pup_xlater.C error turns cvt_bool() into an infinite loop.

The machine.c error will make LrtsAbort do nothing if Cmi_truecrash is true - it should at least abort.

```
ckarrayreductionmgr.C:132:19: warning: comparison of constant -1 with expression of type 'unsigned short' is
      always true [-Wtautological-constant-out-of-range-compare]
                        if (m->userFlag!=-1)
                            ~~~~~~~~~~~^ ~~

pup_xlater.C:138:25: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
        for (i=nElem-1;i>=0;i--)
                       ~^ ~

machine.c:549:5: warning: indirection of non-volatile null pointer will be deleted, not trap
      [-Wnull-dereference]
    *(int *)NULL = 0; /*Write to null, causing bus error*/
    ^~~~~~~~~~~~
```

**Comment by stwhite91** [comment]
*Original date: 2017-02-13 21:11:21*

---
This commit will remove ckarrayreductionmgr completely, so that warning will go away: ~~https://charm.cs.illinois.edu/gerrit/#/c/2216/~~ https://github.com/UIUC-PPL/charm/commit/2c622f863c09793ab8410eb1138428d080fb8e63

The pup_xlater one should be fixed.

The machine.c one is more interesting. It appears from the git history to have been added so that when debugging Charm you get a true crash with the full stacktrace rather than a clean exit with an abort message when running with ++debug and/or +truecrash. That seems useful, and that code will only execute if Cmi_truecrash is true.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-14 01:02:03*

---
For the machine.c case, it would be easy enough to add the suggested volatile to it. That is precisely an intended use.

**Comment by stwhite91** [comment]
*Original date: 2017-02-14 03:30:01*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2242/~~ https://github.com/UIUC-PPL/charm/commit/9290be649351cf0acb89ee01c2010ea5d48b56f4
