### ISSUE TITLE
Parallel (make -j) build of AMPI libraries and client code is racy

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#143]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/143*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-05 23:27:32*

---
This one is from ampicc/ampiCC/ampicxx symlinking our mpi.h and then deleting it when each compilation is done. In a parallel build, if one compilation races with another such that it deletes the mpi.h link that another should have followed, then it will get the system's mpi.h instead and fail horribly.

The solutions I can see include
* explicitly including `ampi.h` instead of `mpi.h`, which is bad for real-world usability/adoption
* leaving the mpi.h link in place, rather than deleting it
* adding some bits in the makefile to delete the mpi.h link at the end, rather than while compilation is still in flight

This is something that will come up in parallel compilation of any AMPI code, so I'm not sure exactly how we want to deal with it.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:50:30*

---
With Intrepid down, I doubt this task is relevant.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-06 08:17:50*

---
This isn't in any way BG/P specific. Please read the comments.

Subject updated to accurately reflect issue.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 09:52:45*

---
As Phil indicated, none of the solution is a clear winner. Among the three proposed solutions, I like the second one (leaving our mpi.h in place) the best, but it may be troublesome if someone wants to compile for other MPI implementations also. I wonder if we want to do an ugly include <mpi.h> inside our mpi.h to include system implementation if not compiled using Charm's compiler. I don't even know if that will work..phew.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-19 20:02:43*

---
http://charm.cs.uiuc.edu/gerrit/#/c/543/

**Comment by PhilMiller** [comment]
*Original date: 2015-02-25 21:53:41*

---
Broke the build with MPI on BGQ:
http://charm.cs.illinois.edu/autobuild/cur/mpi-bluegeneq-xlc.txt
http://charm.cs.illinois.edu/autobuild/cur/mpi-bluegeneq-gcc.txt
