### ISSUE TITLE
Enable pre-pinning memory for the zero-copy message sends through the Entry Method API

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1468]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1468*

---
The cost of memory pinning on Verbs and GNI is high, so we'd like to enable users to pre-pin memory for use in later RDMA message sends. This is a step toward a persistent messaging API in that users can pin once and send multiple times.

We'd like to let the user allocate however they like, and then underneath we avoid re-pinning memory that is already pinned. Unfortunately, Verbs does not seem implement re-pinning of memory that is already pinned in a faster way, and doesn't seem to have a method to query the pinned-ness of some memory, so we'll have to track that ourselves. We can provide a CkAlloc routine that wraps something like infi_CmiAlloc() or that accepts a parameter that says whether memory should be pinned or not.

**Comment by minitu** [comment]
*Original date: 2017-04-13 21:26:04*

---
`CmiAlloc()` calls `infi_CmiAlloc()` underneath, which in turn calls `getInfiCmiChunk()` where the memory is actually pinned through `ibv_reg_mr()`.
So this is not a memory pool per se, since pinning occurs at memory allocation time and not at program initialization time.
If this is fine, we could provide a `CkAlloc()` (which doesn't seem to exist currently) for the user to use when pinned memory is needed.

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 21:30:20*

---
Yes I think that's what we want is a CkAlloc. We can eventually provide a pre-pinned memory pool behind that, but at first just pinning inside the call to CkAlloc is okay.

**Comment by stwhite91** [comment]
*Original date: 2017-04-22 15:30:27*

---
Phil suggested a complementary optimization on the GNI RDMA patch (~~https://charm.cs.illinois.edu/gerrit/#/c/1908/~~ https://github.com/UIUC-PPL/charm/commit/27595aa83f8bf95bf0a87ff92925707f32175f59) where the runtime would lazily deregister memory. That is, register memory that is not already registered, keep a cache of pre-registered memory (with some configurable limit on the number of buffers and the total size of those buffers), and only de-register memory when that cache is full.

**Comment by minitu** [comment]
*Original date: 2017-04-25 20:17:42*

---
Can we move this to 6.8.1? I don't think it will be finished anytime soon.

**Comment by stwhite91** [comment]
*Original date: 2017-04-25 21:56:04*

---
Is this more complicated than providing the following?
A) Add a CkAlloc() routine that just calls CmiAlloc()
B) Maintain an unordered_map or something that keeps track of pointers that are already pinned on a particular PE.
C) In the machine layers in which it is relevant (Verbs and GNI), check the map before pinning any memory.

Since accel/gpu manager updates aren't going to be merged before 6.8.0 and rdma is one of the most important new features of 6.8.0, it would be good to have this before then.

**Comment by minitu** [comment]
*Original date: 2017-04-25 22:42:33*

---
If we just provide a wrapper for malloc and keep track of its pinned-ness, it should be relatively straightforward like you said.
I was more worried about Phil's suggestion of keeping a cache of pre-registered memory, because that sounds similar to creating a mempool of varying sizes.
I have a question though; where should the new CkAlloc routine be defined? Should I create a new file called ckalloc.C in ck-core and somehow add it to the build chain?

**Comment by PhilMiller** [comment]
*Original date: 2017-05-09 20:52:18*

---
The automatic caching approach could go in 6.8.1, but an explicit API would have to be the next feature release.

**Comment by nitbhat** [comment]
*Original date: 2018-03-27 20:26:17*

---
Moving it out of 6.9 release as the Nocopy Broadcast API has higher priority.

**Comment by nitbhat** [comment]
*Original date: 2018-09-20 18:04:05*

---
By implementing the Entry Method API internally using the Direct API, the Entry Method API can be used for passing pre-registered buffers using "CkRdmaAlloc/CmiRdmaAlloc" and "CkRdmaFree". 

The patch used for implementing this feature is the same patch that refactors the Entry Method API to use the Direct API: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4259/~~ https://github.com/UIUC-PPL/charm/commit/9ba90ab3be663d13e45b219c0d8d70e5b3cabe59
Examples for the PREREG mode are added in this patch: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4529/~~ https://github.com/UIUC-PPL/charm/commit/02dd7dac0cd2befa6b6ce5441b1e043b7c49e141
