### ISSUE TITLE
Deprecate the FFT library in ck-libs in favor of Nikhil's new FFT library

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#1547]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1547*

---
Right now the libraries manual still points to the in-tree version of the FFT library. Anyone using this library should get a deprecation warning, and the manual should be updated to point to Nikhil's library at https://charm.cs.illinois.edu/gerrit/gitweb?p=libs%2Ffft.git;a=summary instead.

**Comment by ericjbohm** [comment]
*Original date: 2017-05-09 22:37:49*

---
There are a few complications to accomplishing this in that Nikhil's fft library is not a drop in replacement for the prior version.

1. Documentation is far from complete
## the current manual includes inline TODO items from a prior review
## the API is not completely described
## there is no functioning example in the manual
1. the tests provided do not run correctly
## they either crash or hang
1. the prior library provided both a Charm and AMPI API.
## no documentation is provided for using this library with AMPI
1. this library is thought to be interoperable with MPI from publication history, but no documentation is provided.
1. it is known to work in production for OpenAtom, but we lack production tests for any part of the API not in use by OpenAtom.

Might be a good summer project, but current state appear to be days (possibly more depending on how much functionality is necessary) of effort away from production level.

**Comment by pplimport** [comment]
*Original author: Justin Szaday*
*Original date: 2017-07-21 16:11:48*

---
Just a few questions about the way forward.
1. The prior library's documentation notes that the AMPI API was 'not in CVS,' was it ever actually released?
1. Should I try to address the TODO's in the documentation? If so, I would like to have a discussion with the relevant people so I can get a better idea of what the goal of some of these todo's originally was (mostly due to my lack of familiarity with this library).
1. "Thought to be interoperable with MPI," does this just mean we need to verify it can be run in interopt mode or is more thorough testing required?

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2017-12-13 17:00:03*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3421/~~ https://github.com/UIUC-PPL/charm/commit/3200c48bfd87187c92faa28d4c00099d62d481ce

New manual is largely based on the within library manual.
