### ISSUE TITLE
icc build fails on NASA Pleiades

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1560]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1560*

---
Building with
./build ChaNGa verbs-linux-x86_64 cuda smp icc -j8 --with-production
gives errors like:
../bin/charmc  -optimize -production  -I.   -c -o DummyLB.o DummyLB.C
In file included from sdag.h(28),
                 from CkMarshall.decl.h(6),
                 from charm++.h(134),
                 from LBDatabase.decl.h(3),
                 from LBDatabase.h(100),
                 from BaseLB.h(9),
                 from CentralLB.h(9),
                 from DummyLB.h(9),
                 from DummyLB.C(6):
../bin/../include/pup_stl.h(51): error: namespace "std" has no member "unique_pt
r"
    inline void operator|(er &p, std::unique_ptr<T, std::default_delete<T>> &ptr
);
                                      ^
Here is the icc version: icc -v
icc version 16.0.2 (gcc version 4.3.0 compatibility)

**Comment by trquinn** [comment]
*Original date: 2017-05-15 03:20:44*

---
That last line was a clue: it looks like the intel compiler depends on the g++ libraries, so a modern gcc has to be loaded as well as the intel compiler.  On pleiades:
module load gcc
module load comp-intel
is needed.

**Comment by stwhite91** [comment]
*Original date: 2017-05-15 03:55:34*

---
Yes, that is true on a few other systems too. AFAIK we decided to require at least gcc v4.4 headers for 6.8.0, and we are planning for future releases after 6.8 to require full C++11 support. Phil knows more about the specifics here.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 14:17:19*

---
We ran into the exact same issue on some of the NERSC Cray systems.

We could maybe push a test that would trigger this failure into the configure process, and give a more explicit error explaining what went wrong and how to fix it. In the meanwhile, it should probably get at least a release notes entry.

**Comment by stwhite91** [comment]
*Original date: 2017-05-16 17:37:15*

---
If we don't catch this during configure and abort with a message explaining why it failed, I think we're basically asking for future emails to the charm mailing list about it.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-18 19:34:10*

---
Notes on the errors encountered with different icc/gcc version matchups:

|_.gcc \ Intel            |_.12              |_.13     |_.14       |_.15      |_.16       |_.17         |
|_<. 4.3 (Edison default) |                  |         |           |          | %{color:red}unique_ptr not defined in std% | %{color:red}unique_ptr not defined in std% | 
|_<. 4.4                  |module won't load - conflict|module won't load - conflict|module won't load - conflict|module won't load - conflict| module won't load - conflict with intel module| module won't load - conflict with intel module| 
|_<. 4.5 (edison n/a)     |   -              |  -      |    -      |  -       | -         | - | 
|_<. 4.6 (edison n/a)     |   -              |  -      |    -      |  -       | -         | - | 
|_<. 4.7                  |                  |         |           |          |%{color:red}icpc: internal error: Assertion failed (shared/driver/drvutils.c, line 670)%| %{color:red}icpc: internal error: Assertion failed (shared/driver/drvutils.c, line 670)%| 
|_<. 4.8                  |                  |         |           |          |%{color:green}good%| %{color:green}good% | 
|_<. 4.9                  |                  |         |           |          |           | %{color:green}good% | 
|_<. 5.3                  |                  |         |%{color:green}good% with older PrgEnv-intel/5.1.29|%{color:green}good%| %{color:green}good%| %{color:green}good% | 
|_<. 6.1                  |                  |         |           | %{color:red}see #1372%|Error #3802: Version 16.0 Update 2 is incompatible with GNU versions greater than or equal to 6.0, due to an incomplete implementation of SFINAE which is used extensively in gcc6 headers. If you wish to proceed, use option -wd3802| %{color:green}good%| 
|_<. 6.2                  |                  |         |           |          |Error #3802: Version 16.0 Update 2 is incompatible with GNU versions greater than or equal to 6.0, due to an incomplete implementation of SFINAE which is used extensively in gcc6 headers. If you wish to proceed, use option -wd3802| %{color:green}good%|

**Comment by PhilMiller** [comment]
*Original date: 2017-05-18 20:37:45*

---
The Intel 16 / GCC 6 combination errors at compile time. The configure output also shows error messages, but somehow doesn't detect those as failure, so it continues.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-19 14:08:55*

---
~~https://charm.cs.illinois.edu/gerrit/2542~~ https://github.com/UIUC-PPL/charm/commit/cd4d6f80b970ae702874a14404189f042e83478a

**Comment by stwhite91** [comment]
*Original date: 2017-05-30 14:05:14*

---
This seems to have broken the Edison autobuild targets.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-30 14:51:39*

---
Was working as intended. I had screwed up the login script configuration for the account used by autobuild, to say `module load gcc/6.3.0` when the latest available was `gcc/6.2.0`. I switched it over to `gcc/5.3.0` and confirmed that it now passes configure.

**Comment by jcphill** [comment]
*Original date: 2017-05-30 16:03:28*

---
This test is now failing on my build box because it doesn't pass through the "-gcc-name=gcc44 -gxx-name=g++44" options included on the build command line to icpc, and just runs "icpc -I../include -I. -c test.cpp -o test.o -h std=c++11" instead.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-30 16:52:31*

---
Jim:
I think the definitive resolution of the exact issue you're now seeing would be to pass `$OPTS` to the various compilers as we test them in `configure`. That would be a fairly high-risk change, and I feel like we've tried that at some point in the past, and encountered a lot of trouble.

Here's my suggestion for what I think should be a fairly solid workaround - apply the following patch, and change your build line to something like the following:

```
OPTS_CC="-gcc-name=gcc44" OPTS_CXX="-gxx-name=g++44" ./build charm++ netlrts-linux-x86_64 --with-config-options -build-options etc
```

~~https://charm.cs.illinois.edu/gerrit/2564~~ https://github.com/UIUC-PPL/charm/commit/cf9d5d1f4ca0f4d3c27727f8ab30e665e24b9154

I've tried this on my mac as follows:

```
OPTS_CXX=-std=c++1y ./build charm++ netlrts-darwin-x86_64
[...]
checking "C++ compiler as"... "clang++ -m64 -fPIC -dynamic -fno-common -mmacosx-version-min=10.7 -stdlib=libc++ -Wno-deprecated-declarations    -std=c++1y "
checking "whether C++ compiler works"... "ok"
checking "C++ linker as"... "clang++ -multiply_defined suppress -mmacosx-version-min=10.7 -Wl,-no_pie -stdlib=libc++     "
checking "whether linker works"... "ok"
checking "Native C++ compiler as"... "clang++ -m64 -fPIC -dynamic -fno-common -mmacosx-version-min=10.7 -stdlib=libc++ -Wno-deprecated-declarations "
checking "Sequential C++ compiler as"... "clang++ -m64 -fPIC -dynamic -fno-common -mmacosx-version-min=10.7 -stdlib=libc++ -Wno-deprecated-declarations "
checking "whether compiler accept -fno-stack-protector"... "ok"
checking "whether C++ compiler supports C++11 without flags"... "yes"
[...]
touch charm++
-------------------------------------------------
charm++ built successfully.
Next, try out a sample program like netlrts-darwin-x86_64-cxx1y.2/tests/charm++/simplearrayhello

```

**Comment by jcphill** [comment]
*Original date: 2017-05-30 17:43:00*

---
Seems to have failed the auto-test.  Will test after that passes.

**Comment by jcphill** [comment]
*Original date: 2017-05-30 18:28:54*

---
The fix works. Thanks.

**Comment by jcphill** [comment]
*Original date: 2017-07-06 21:56:49*

---
When I pass OPTS_CXX="-gxx-name=g++44" to the build script it is preserved for future charmc invocations, which breaks on other machines.

**Comment by PhilMiller** [comment]
*Original date: 2017-07-06 22:04:46*

---
Jim, could you please elaborate?

**Comment by stwhite91** [comment]
*Original date: 2017-10-27 14:26:03*

---
We need to update this for 6.9.0 and C++11 support. Our configure script points people to this issue if using ICC with old GCC headers.

**Comment by jcphill** [comment]
*Original date: 2018-01-08 19:39:51*

---
Wanted to update with two alternative solutions, neither of which preserves the options in the build config files.

First, rather than trying to pass the -gcc-name and -gxx-name options via the Charm++ build script, they can be set via the __INTEL_PRE_CFLAGS environment variable:

```
setenv __INTEL_PRE_CFLAGS "-gcc-name=gcc44 -gxx-name=g++44"
```

The modern way to install and access newer compilers is via the scl package (https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/):

```
scl enable devtoolset-6 -- ./build charm++ netlrts-linux-x86_64 ...

```

**Comment by sethrj** [comment]
I found this issue after some searching from a dead link via [the cppreference compiler support page](https://en.cppreference.com/w/cpp/compiler_support). I wish to report that GCC 8.3's stdlibc++ fails with Intel 18, as does the one from GCC 7.4. GCC 6.5 works with Intel 18. I've updated the above table and added new columns/rows. 

gcc \ Intel | 12 | 13 | 14 | 15 | 16 | 17 | 18
----------- | -- | -- | -- | -- | -- | -- | --
 4.3        |    |    |    |    | ❌ | ❌ |
 4.7        |    |    |    |    | ❌ | ❌ | ✅
 4.8        |    |    |    |    | ✅ | ✅ |
 4.9        |    |    |    |    |    | ✅ |
 5.3        |    |    | ✅ | ✅ | ✅ | ✅ |
 6.1        |    |    |    | ❌ | ❌ | ✅ |
 6.2        |    |    |    |    | ❌ | ✅ |
 6.5        |    |    |    |    | ❌ | ✅ | ✅
 7.4        |    |    |    |    |    |    | ❌

GCC 4.3 / Intel 16,17:
```
unique_ptr not defined in std
```

GCC 4.7 / Intel 16,17:
```
icpc: internal error: Assertion failed (shared/driver/drvutils.c, line 670)
```

GCC 6.1 / Intel 15:
```
/opt/gcc/6.1.0/snos/include/g++/bits/stl_iterator_base_types.h(154): 
error: class "std::__cxx11::list<client *, std::allocator<client *>>" has 
no member "iterator_category"
         typedef typename _Iterator::iterator_category iterator_category;
```

GCC 6.{1,2} / Intel 16:
```
Error #3802: Version 16.0 Update 2 is incompatible with GNU versions greater than or equal to 6.0, due to an incomplete implementation of SFINAE which is used extensively in gcc6 headers. If you wish to proceed, use option -wd3802
```

(error message from GCC 7.4:
```
/projects/spack/opt/spack/gcc-4.4.7/gcc/o5vbw5a/include/c++/7.4.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined
  _GLIBCXX_MEM_FN_TRAITS(noexcept, true_type, true_type)
  ^
```)
