### ISSUE TITLE
Inline entry methods don't respect group dependence from CkEntryOptions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1564]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1564*

---
When the target object exists locally and delivery happens inline, the CkEntryOptions are ignored, even if it indicates an unsatisfied group dependence.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 16:44:06*

---
This says 'Implemented', but I can't find code where I've actually done it. Shouldn't be too hard, but it's not something already done.

Note when doing this that the generated method definitions for chares, arrays, and groups each come form different places in charmxi, so implementation will have to touch each of them (or extract their commonality)

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:46:38*

---
Per discussion with Eric B, assigning to Nitin, based on recent work around CkEntryOptions handling

**Comment by nitbhat** [comment]
*Original date: 2018-01-09 21:10:49*

---
Is there a test/example that can reproduce this bug? (just to be sure that the fix works correctly). 
I am not able to reproduce this issue with a test that calls an inline entry method with a group dependence. (probably because in all my test cases, the system favors the default case of getting the group creation message before the entry method message).

**Comment by nitbhat** [comment]
*Original date: 2018-01-17 23:32:50*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3528/~~ https://github.com/UIUC-PPL/charm/commit/d24d191d92a48c9cab38b84e7565e794f588949d
