### ISSUE TITLE
Mark CkAbort [[noreturn]]

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1579]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1579*

---
Once C++11 is required `ckExit` should be marked `[[noreturn]]`

**Comment by matthiasdiener** [comment]
*Original date: 2018-01-18 23:17:50*

---
There is a WIP patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/3537/~~ https://github.com/UIUC-PPL/charm/commit/07aef728c23919c92dca5543bf8c091fd5c6a0a8

This seems to work, but I'd like some feedback if this is the best way to do it.

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-14 20:53:21*

---
Needs review.

**Comment by stwhite91** [comment]
*Original date: 2018-03-29 15:51:19*

---
The patch above has been updated to only mark CkAbort() as noreturn. We can't safely mark CkExit() as noreturn because when using MPI + Charm++ interoperation, CkExit does actually return. We could split the interop exit function from CkExit(), but that would just an obstacle to porting Charm++ code to interoperate with MPI.

**Comment by stwhite91** [comment]
*Original date: 2018-04-04 15:51:29*

---
I'm seeing compiler warnings about this now:

```
In file included from machine.c:228:0:
machine-common-core.c: In function ‘CmiAbort’:
machine-common-core.c:1694:1: warning: ‘noreturn’ function does return
 }
 ^
machine.c: In function ‘LrtsAbort’:
machine.c:562:1: warning: ‘noreturn’ function does return
 }

```
