### ISSUE TITLE
bgclang builds broken

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1642]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1642*

---
The bgclang builds in autobuild have been broken since 7/21/17. Seems like an upgrade to the bgclang compilers might have done this? Or perhaps our test script broke and is no longer loading the bgclang compiler environment properly anymore.

```
checking machine name... pamilrts-bluegeneq-clang
checking "cp command as"... cp -p
checking "C++ compiler as"... "bgclang++ -Wno-deprecated-declarations     "
checking "whether C++ compiler works"... "no"
Cannot compile C++ programs with bgclang++ -Wno-deprecated-declarations   
 (check your charm++ version)
*** Please find detailed output in charmconfig.out ***
make[1]: *** [conv-autoconfig.h] Error 1
make[1]: Leaving directory `/gpfs/vesta-fs0/projects/CharmRTS/nbhat/autobuild/pamilrts-clang-nosmp/charm/pamilrts-bluegeneq-clang/tmp'
make: *** [headers] Error 2
-------------------------------------------------

```

**Comment by stwhite91** [comment]
*Original date: 2017-07-26 12:42:05*

---
Assigning to Nitin because he's in charge of the autobuild on BGQ.

**Comment by nitbhat** [comment]
*Original date: 2017-07-26 22:59:13*

---
charmconfig.out showed that bgclang was not found: 

bgclang++ -Wno-deprecated-declarations -I../include -I. -I/bgsys/drivers/ppcfloor/comm/include -I/bgsys/drivers/ppcfloor/spi/include -I/bgsys/drivers/ppcfloor -I/bgsys/drivers/ppcfloor/spi/include/kernel/cnk -I/soft/libraries/alcf/current/xl/ZLIB//include -c test.cpp -o test.o
./configure: line 2212: bgclang++: command not found

This happened because of a recent change in my vesta programming environment i.e I had removed " +mpiwrapper-bgclang" from my ~/.soft. I added it back and was now able to build successfully. This should be seen in tonight's autobuild.
