### ISSUE TITLE
Do Not Require Default Constructors for Serializable Classes

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1679]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1679*

---
I've set the target to 7 because this could be implemented as a breaking change.

Currently Charm++ requires all classes be default constructible. However, with C++11 it is possible to `= delete` the default constructor, which in many cases is desirable and can help prevent bugs. Charm++ requires the object be created and then a `pup` member function be called. There are two solutions I can think of:

1) Have classes have a constructor that takes a `PUP::er` (I can see this being tricky with abstract base classes), and then deserialize the data from it. Some care would need to be taken not to call this constructor when serializing, only when deserializing.

2) Construct classes using a constructor that takes some charm++ defined type, say `charm::PupConstructor`, and then calling the `pup` as is done now. This allows people to `delete` (or make private) the default constructor to prevent unintentional default construction.

I think both are equally easy to implement, especially if one is willing to break code. If you do not want to break code you will need to use something like `std::is_constructible` (http://en.cppreference.com/w/cpp/types/is_constructible) to check whether the required constructor exists, making this an opt-in feature rather than an enforced idiomatic way of writing Charm++ code.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-28 17:01:03*

---
We actually ended up implementing something that should satisfy this request for a contract customer who wanted it ASAP: ~~https://charm.cs.illinois.edu/gerrit/#/c/3021/~~ https://github.com/UIUC-PPL/charm/commit/e839b4feb37c3e14f7f2314816fda376aa4019e9

Using an actual constructor with a tag type argument instead of a separately-named method may be preferable, since the special method ends up requiring also move constructor support.

Note that the patch following the one linked is necessary to fully actually eliminate the requirement of Default Constructible for types used as entry method arguments, since generated code default-constructs objects to unpack-PUP into.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-27 02:19:28*

---
Moved to a constructor with a tag argument approach. We now do not require either of the default or move constructor.

As currently implemented, entry methods can take their arguments by value, rvalue reference, or const lvalue reference. They cannot take them by non-const lvalue reference. Semantically, this is probably right, since the unpacked instances are logically 'expiring' when the call returns, even though they may actually be declared as local variables in the generated calling code. We'll see if the applications can handle this.

Applications that want to be wholly backwards compatible (current/evolved app code builds on charm<6.9) may pay a performance penalty if they want to be able to modify the value in question - they would have to switch to taking their arguments by value, since the older code generation won't let them accept rvalue references. Without breaking backwards compatibility, they could still take const lvalue reference.

**Comment by lvkale** [comment]
*Original date: 2017-11-02 20:39:30*

---
An example program will be useful to have  (and/or a fragment) in redmine to illustrate the feature.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-04 19:35:00*

---
Commits now all pass tests, minor application changes as needed have happened, and documentation is included.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-15 18:42:56*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3356/~~ https://github.com/UIUC-PPL/charm/commit/2daab851e9e2b9863058faff4f06c3dd1170d9b4 and predecessors

**Comment by stwhite91** [comment]
*Original date: 2018-04-09 20:25:34*

---
For direct documentation here, you can now specify a constructor that takes "PUP::reconstruct" as its argument
