### ISSUE TITLE
Core Dump file not available unless `--disable-charmdebug` is used while building. 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1688]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1688*

---
While building charm with debug symbols without production mode, CMK_CHARMDEBUG is turned on and this leads to Charm error handling throwing errors when bad signals are encountered during program execution. Although a stack trace is printed by charm error handling, it is sometimes incomplete and not as useful as having a core dump. The fix is to have a dump file generated even when charm error handling is used to handle bad signals.

**Comment by evan-charmworks** [comment]
*Original date: 2019-02-12 19:11:30*

---
For which machine layer(s) is this a problem? I see `sigaction` calls in the MPI, netlrts, and Verbs layers. The MPI machine layer unconditionally intercepts signal handlers with CMK_CHARMDEBUG. The other two can avoid the signal handling by specifying the hidden option `++debug` directly to the program binary.

**Comment by evan-charmworks** [comment]
*Original date: 2019-02-15 21:06:36*

---
The three machine layers I mentioned have something like this in their signal handler:

```
static void KillOnAllSigs(int sigNo) {
  // ...
    
    CmiAbortHelper("Caught Signal", strsignal(sigNo), NULL, 1, 1);
} 
```

```
static void KillOnAllSigs(int sigNo)
{
  // ...

  {
    Cmi_truecrash = 0;
    CmiAbortHelper("Caught Signal", sig, suggestion, 0, 1);
  }
}
```


Is the intent of this issue to essentially make `Cmi_truecrash` unconditionally active? I think this makes sense, because if an error occurs we should not hide it from anything that depends on the exit status of the program.

**Comment by evan-charmworks** [comment]
*Original date: 2019-03-14 19:24:03*

---
Does anyone know why `Cmi_truecrash = 0;` is the default -- or implemented at all? Why should crashes be hidden from the system and job launcher?

**Comment by kavithachandrasekar** [comment]
*Original date: 2019-03-14 21:27:34*

---
I agree, it's not clear why Cmi_truecrash is not enabled by default. It could have been for terminating gracefully because while specifying +truecrash generates core dump file, it does not print stack trace. Maybe CmiAbortHelper should do both - print stack trace and generate core dump file.

**Comment by kavithachandrasekar** [comment]
*Original date: 2019-03-28 19:21:18*

---
Based on discussion in core, we can generate core dump files for when CmiNumNodes() <= 32 or if charm is built without production flag.

**Comment by kavithachandrasekar** [comment]
*Original date: 2019-04-11 19:17:26*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5078~~ https://github.com/UIUC-PPL/charm/commit/8c85a3debc2254d68f8aa50c6ec0b1e302c86131
