### ISSUE TITLE
ensure charm builds with C11/C++11 flags

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#169]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/169*

---
Ensuring forward compatiblity with the latest available compiler support for the new standards might be useful as users start trying this themselves. There has been initial proof that we build and test without issues on gcc and xlc while enabling the new std (ram tried this manually in 2012/08). This should become an automated evaluation across all compilers.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-22 03:37:02*

---
I can now build and test with C11 and C++11 support enabled, modulo a few specific files (cmitls.c, isomalloc.c, threads.c, convcore.c). These errors seem to arise solely due to outdated headers on the lab workstations. Will test on my Debian Sid home system.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-22 03:48:42*

---
These 4 files fail to compile in C11 mode under both Clang 3.4 and G++ 4.8, on an up-to-date Debian Sid system.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-22 04:03:27*

---
When I define `-D_GNU_SOURCE`, convcore.c, isomalloc.c, and threads.c build cleanly, since they were purely lacking library features. The last, cmitls.c, also depends on inline assembly, which can be enabled with `-std=gnu11` instead  of `-std=c11`.
