### ISSUE TITLE
Inconsistent charm++ archives

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1702]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1702*

---
The v6.8.0 archive is a `.tar.bz2` archive while older versions are `.tar.gz`. This makes in more difficult when packaging Charm++ in package managers like spack, and also for CI systems. It would be nice to have a tar.gz of 6.8.0 available, but I mainly wanted to bring this inconsistency to your attention to make sure it's intentional :)

**Comment by PhilMiller** [comment]
*Original date: 2017-10-04 20:18:06*

---
It was intentional, to provide a smaller download. I hadn't thought about the impact on systems that would be looking for a specific filename, only on humans following a link from our website/email.

We'll post a tar.gz of that, and of future releases, to allow for easy consistent scripting.

**Comment by nilsdeppe** [comment]
*Original date: 2017-10-04 20:34:42*

---
Ah okay, well I'm fine with the change, I just wanted to make sure it's intentional. We restrict ourselves to the newest Charm++ version anyway, so if this will be consistently bz2 going forward it won't be an issue for us.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-05 01:11:52*

---
I've posted a gzipped version of the same tarball.

We'll release future versions as tar.gz, mostly for convenience of operation with `git archive`, since we can script that in preparing the release tarball.

**Comment by nilsdeppe** [comment]
*Original date: 2017-10-05 02:33:46*

---
Awesome, thank you very much!
