### ISSUE TITLE
objid_t: Distributed lookup protocol

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#174]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/174*

---
This first requires design discussions to delineate the subtasks

**Comment by heyram** [comment]
*Original date: 2013-07-08 19:54:32*

---
This is a summary of the original discussion between Ram and Akhil (mar 2013)

### context

There are several situations where an array index can be uniquely converted to an objid_t. This can happen when the size of the array (or each of its dimensions) is known exactly or is bounded by some number. This can also happen when the array indices are sparsely distributed in one or more dimensions, but the user supplies a conversion function that encodes a one-to-one mapping from index to id. This conversion function can be statically specified at compile time, or may depend on runtime parameters. 

Finally there exists a situation where there is no clear mapping from arrayIndex to objid. In this case, the runtime system has to generate a unique objid for each array index in a chare array. There exist two approaches:

(a) hash the arrayIndex to an objid. provide appropriate protocol to resolve hash collisions so that each objid is used for just one arrayIndex.
(b) generate a unique objid for each arrayIndex. maintain the mapping in a distributed lookup table

### hash-based approach:

Upon element insertion, each array index is hashed to yield a candidate object id. This object id is used to determine a homePE. The homePE is queried to validate the candidate objid. If there are no hash collisions, the objid is approved. If not, the homePE returns a different objid.  This idx<-->objid mapping is bcast to all PEs and stored in a collision table on all PEs. An element cannot be inserted until a homepe validates or provides a legal objid for the new element. 

While sending msgs, the app supplies the destination index. This is first checked in the collision table to see if a forcibly assigned objid is available. If not, the hash function is applied to generate the objid. This objid is then used for the usual cache / homepe lookup for location information and msg sending.

However, there currently seem to some easily generated race conditions in a situation where this scheme interacts with dynamic insertion. One example will shortly be explained here.

### distributed lookup

In this solution, any storage space benefits of using a shorter objid in the locmgr are washed out because the locmgr now has to store both the objid and the index. This scheme basically requires that each element be assigned a unique id and that the locmgr / homepe store both the index and objid. Any index can be looked up (in the loc cache or at the homepe) to get both the objid and location info. The objid is only used for uniform identification in all rts components and for shorter envelope data. However, races or more complicated distributed protocol are avoided.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:05:51*

---
This won't be ready for 6.6, so push it back.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-05 23:32:44*

---
Here's what I presented to Harshitha and Akhil:

The craziness with hashes and collision possibilities and so forth left many open questions, and is unworkable. So, I've developed an alternative design that should meet our needs and actually be straightforward to implement.

Definitions:
* key: an array element's index. Will be treated as opaque henceforth - we can ask an array map to give us a corresponding home PE, and do standard comparison/copy/assignment operations, but cannot ask the user to define any other hashing function for us, nor arbitrarily hash them ourselves
* home: the PE output by the array map's `procNum` method applied to an element's key
* ID: the fixed-size identifier for each object that the runtime system will deal in, to which user code will never be exposed
* owner: a PE that is in some sense (defined below) responsible for a given ID
* host: the PE on which an object resides

All messages directed to a given object will be represent the recipient by ID in the envelope, and eventually all other runtime system components. Thus, upon insertion of an object with a given, some PE has to assign an ID to that object, and ensure that the home PE knows the key -> ID mapping. This mapping must be a one-to-one (injective) function.

In the first pass, the owner of an ID is responsible for maintaining the `ID -> location` mapping. The `ID <-> owner` mapping needs to be a simple, easy to compute function. I plan to initially partition the ID space among owners, so that a PE can assign a fresh ID that it owns simply by incrementing a counter. For simplicity, all assignments of IDs owned by a given PE will only be made by that PE. Later, if we need to reclaim IDs to avoid exhaustion, owners can start tracking deletions and re-using those IDs. 

There are three 'obvious' choices for which PE should assign a new object its ID:
* The PE making the insert call
* The PE that will be the object's initial host
* The object's home PE

The problem with the inserter is that this creates a location-lookup hotspot on PE 0 in applications that do a big pile of insertions from a mainchare or the like.

The initial host is a reasonable prospect, and avoids complexity and cost on the object creation path. However, it has the potential for problems during normal communication or migration:
* Case 1: Sending a message to an unknown key could have the latency of remotely looking up key -> ID and then separately ID -> location
* Case 2: Migrating an object requires telling both its home PE and its ID owner PE about the new location, so that either can answer queries

The home PE avoids the above issues entirely. If we want to ensure that an object always has an ID before it's constructed, this adds some latency on the creation path, but that is not inherent or essential. Thus, I've concluded that this is the approach worth taking.

Harshitha has agreed that this design is reasonable. I've presented the design to Akhil, and he said he'll get back to me in the next day or two with any comments.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-02 19:52:46*

---
Simplest insertion protocol assuming home-PE based ID generation as documented in wiki:

1. Inserter assembles a message with the parameter marshaled array index and constructor argument message
1. Inserter sends insertion message to the appropriate group on the intended host.
1. Group on host receives insertion message
1. Host buffers constructor arguments 
1. Host sends home PE (based on index) message containing index and requesting a new ID for it
1. Home PE responds with a fresh ID that maps to that PE
1. Host receives ID, retrieves buffered message, and executes constructor

**Comment by PhilMiller** [comment]
*Original date: 2014-04-02 19:57:20*

---
Possible optimizations to insertion protocol described in comment #174-7:

* Instead of step 5, inserter sends message to home PE, directing response to host.

This potentially cuts the latency of the insertion process. The downside is the code complexity of handling the race condition in which the response arrives at the host before the constructor arguments.

* Instead of step 2, inserter sends the insertion message to the home PE, which then forwards the arguments and the new ID to the intended host

This cuts out one of three messages. The downside is the double-send of the constructor payload (thus, this is only justified when that is small), and the additional code complexity.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-02 20:09:25*

---
Basic send protocol, in which sender has target index and payload:

1. Sender looks for ID/host record in local tables. If found, fill in envelope and send
1. Otherwise, buffer message by index, compute home PE from index and send request for ID/host
1. Home PE sends back ID and host for requested index
1. Look up buffered messages for index. Fill in ID in their envelopes and send to indicated host

Simple forwarding of message containing 'unknown' ID

1. Compute home PE either directly from ID or from map function of decompressed ID (as appropriate)
1. Bounce message via home PE

More elaborate forwarding by ID

1. Compute home PE
1. Ask home PE for host of IDed object
1. Buffer message by ID
1. When forwarder receives host, send message(s) to host

Better when there are many or large messages, to avoid excess traffic

**Comment by PhilMiller** [comment]
*Original date: 2015-02-05 18:39:42*

---
The problem with the implemented scheme wrt demand creation is that PE A will want to send a [createhere] message to an index I that does not yet exist. So, not having a mapping from that index to an ID in its local cache, it will ask that index's home PE B for the index's location and ID, and store the message in the local [index -> held messages] buffer. When PE B gets a message from PE A asking for the ID and location of I, it will see that it has no record of I yet, and store the request in its local [index -> interested PEs] buffer. At this point, the program hangs, because neither side knows that the message in question should have led to the object being created.

**Comment by lvkale** [comment]
*Original date: 2015-02-07 20:17:22*

---
A solution is to add an extra bit to the message that provides Index and asks for Location and ID. This bit could be set for demand creation. The home PE assigns an ID even though the object is not ready yet.  (for collision detection, etc. it seems a waste to add a round-trip for this, when we know the location.. but it will be avoided for the common case when the index -> id map is statically pre-calculated.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-07 22:23:00*

---
Akhil and I actually implemented a solution already. The demand creation tests and collision detection examples all work fine now.

There's a later added test of TRAM that directly accesses some location manager API that's been changed/deleted that we'll have to update. Otherwise, this branch is fully up-to-date with mainline and suitable for performance testing/tuning, etc.

There's also a delay to integrating this because OpenAtom still contains a lot of Comlib code that's not going to be updated for this since we're deleting it. Eric said that the comlib-depending code will be deleted when other work associated with it gets merged around March.

**Comment by lvkale** [comment]
*Original date: 2015-02-09 16:12:36*

---
"a solution" => please record what the solution is in redmine.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 16:24:00*

---
It was essentially what you suggested - when asking for the mapping from Index to ID and location, it indicates the demand-creation status of the request. Along with the flag, it also has to provide the chare type and array ID of the intended recipient (since multiple arrays of different types can be bound to a single location manager) so that demand creation can be triggered appropriately.
