### ISSUE TITLE
Fix AMPI on mpi-windows builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1764]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1764*

---
ampicc has to be careful on MPI builds on Windows to replace the native MS MPI libraries with its own when compiling user programs.
This has been broken recently. Not sure if it was the hwloc changes or what exactly did it. This failure was hidden by AMPI ROMIO failures b/c of hwloc earlier.

**Comment by stwhite91** [comment]
*Original date: 2017-12-13 16:36:09*

---
In tests/ampi/megampi:
```
ampicxx -optimize -production  -optimize -production  -c test.C
Ignored Unrecognized argument -fno-lifetime-dse
test.C
test.C(93): error C2039: 'MPI_COMM': is not a member of 'MPI_Status'
c:\program files\microsoft compute cluster pack\include\mpi.h(316): note: see declaration of 'MPI_Status'
test.C(256): error C2039: 'MPI_COMM': is not a member of 'MPI_Status'
c:\program files\microsoft compute cluster pack\include\mpi.h(316): note: see declaration of 'MPI_Status'
test.C(256): error C2660: 'MPI_Recv': function does not take 6 arguments
test.C(270): error C2065: 'AMPI_MY_WTH': undeclared identifier
test.C(282): error C3861: 'AMPI_Migrate': identifier not found
test.C(287): error C2065: 'AMPI_MY_WTH': undeclared identifier

```

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-11 16:47:51*

---
This seems to be caused by the hwloc patches. In `tmp/conv-mach-opt.sh`, the following lines are added by hwloc configure:

```
CMK_CC_FLAGS="$CMK_CC_FLAGS -D_CRT_SECURE_NO_DEPRECATE -I /cygdrive/c/PROGRA~1/MI18F8~1/Inc -I /cygdrive/c/PROGRA~1/MI18F8~1/Include -I./../include -D__CHARMC__=1 -O2 -U_FORTIFY_SOURCE  "   # Option added by configure script's hwloc section
```

This appears to override the `NO_WIN_HPC_HEADERS_FOR_AMPI` case in `mpi-win64/conv-mach.sh`, which is used to prevent the inclusion of the Microsoft MPI headers when compiling an AMPI application.

Patch ~~https://charm.cs.illinois.edu/gerrit/#/c/3339/~~ https://github.com/UIUC-PPL/charm/commit/ee118682f957ee2382f7ef99849de7a7542c6e62 might be the culprit.

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-12 22:49:01*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/3713~~ https://github.com/UIUC-PPL/charm/commit/d5ee81eb759a2e5157b5f76c80daa1dfc6d47435
