### ISSUE TITLE
SMP hangs in megatest/multisectiontest

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1832]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1832*

---
Jenkins builds and the netlrts-linux-x86_64-smp autobuild target are hanging pretty consistently in tests/charm++/megatest/multisectiontest, like this:
```
test 36: initiated [multi groupmulti (gengbin)]
test 36: completed (0.23 sec)
test 37: initiated [multi groupsectiontest (ebohm)]
test 37: completed (0.54 sec)
test 38: initiated [multi multisectiontest (ebohm)]
Build timed out (after 60 minutes). Marking the build as aborted.
```

https://charm.cs.illinois.edu/autobuild/cur/netlrts-linux-x86_64-smp.txt

**Comment by stwhite91** [comment]
*Original date: 2018-03-28 01:26:43*

---
This is one of the few bugs left that would block the release of 6.9.0

**Comment by juanjgalvez** [comment]
*Original date: 2018-03-28 13:27:52*

---
Do we know the commit that triggered this bug?

**Comment by stwhite91** [comment]
*Original date: 2018-03-28 13:37:44*

---
Originally [1] caused failures in this test. That initial failure was then fixed by [2], but now we are seeing this hang in the same test.

[1] ~~https://charm.cs.illinois.edu/gerrit/#/c/3528/~~ https://github.com/UIUC-PPL/charm/commit/d24d191d92a48c9cab38b84e7565e794f588949d
[2] ~~https://charm.cs.illinois.edu/gerrit/#/c/3850/~~ https://github.com/UIUC-PPL/charm/commit/67790b711e36524c7a9e57b92f5bc96904ef98bc

**Comment by juanjgalvez** [comment]
*Original date: 2018-03-28 14:34:49*

---
Yeah, I thought it had been fixed by the above patch.

So what we are getting now is a random hang, not always in the same place?

**Comment by juanjgalvez** [comment]
*Original date: 2018-03-28 15:32:12*

---
Most of the hangs or crashes are in megatest/multisection test, but today SMP seemed to fail in tests/converse/commbench, not sure if just a spurious failure or what.

**Comment by juanjgalvez** [comment]
*Original date: 2018-03-30 02:29:52*

---
This is a QD bug introduced by the group dependence patch.

It hangs multisection test only because that test uses QD. The hang occurs only if the new "groupdependence" test added to megatest runs (without the groupdependence test it never hangs).
And it hangs only if during the groupdependence test, a group dependence and message arrival order causes a message (intended for either a singleton chare or a nodegroup) to be temporarily buffered. This situation doesn't happen very frequently which is why the bug is hard to replicate.

The actual cause of the bug is that the QD counters for the message that is buffered are incremented more than once, because the call to `ck->process()` for these msg types occurs in `_processHandler`, which is called everytime the msg is dequed. The message is dequed the first time it arrives and any time it is buffered because of a group dependency and released afterwards.

The solution appears to be to not call `ck->process()` in `_processHandler` but rather in the function that processes the msg (e.g. _processNodeBocInitMsg) right before the entry method is invoked. But if this is done, then I'll note that the `_initHandler` function in init.C needs to be modified also to disable calling `CpvAccess(_qd)->process();` for NodeBocInitMsg, otherwise QD doesn't work.

**Comment by nitbhat** [comment]
*Original date: 2018-04-02 19:51:01*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3934/~~ https://github.com/UIUC-PPL/charm/commit/cd5668b0ad3e6be26ba8292dc956311ed94fafc1
