### ISSUE TITLE
CkBitVector's comparison operators lie

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#189]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/189*

---
The basic `operator==` and `operator<` simply `return false;` rather than actually computing anything. If they're in use or prospectively useful, they should be fixed. If not, deleted, I guess.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 19:04:05*

---
Please look into this.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-09-16 15:39:34*

---
Fixed by implementing correct operations

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-09-17 04:11:34*

---
I implemented a compare function. 
If the length of their bits are different, the longer one is greater. 
If the length is same, I compare int by int from the first integer. This is because the most significant bit sits in the first integer.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-10-08 19:37:42*

---
Semantics:

(1) Compare bit by bit , the one who has smaller bit is smaller.  The one which is short is smaller. 
(2) smaller is less.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-10-11 14:07:27*

---
updated according to lexicographic order
