### ISSUE TITLE
Make mempool aware of Isomalloc's per-slot metadata

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1920]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1920*

---
By default Isomalloc uses the mempool implementation in src/arch/util/mempool.{h,c}.
That mempool always allocates memory in slots that are powers of two sized, with the smallest slot being I think 64 Bytes.
Isomalloc adds its own small metadata (~32 Bytes) to each of the application's allocations for its own bookkeeping.
As a consequence, if the user calls "malloc(64*1024*1024)" they will get a slot in the mempool that is actually get a 128 MB for an allocation that is 64MB + 32B.
We should instead make the mempool aware of Isomalloc's small metadata so that it plays nicely with even powers-of-two allocation sizes.

**Comment by stwhite91** [comment]
*Original date: 2018-08-22 01:54:30*

---
Evan looked into this and said it would be a bit tricky to implement, and making Isomalloc not use the mempool seems like a better long term move anyways, so rejecting...

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-23 18:29:07*

---
Yeah, this is a fundamental design flaw in the mempool, instead of an edge case that should be patched in. I've repeatedly tried to work on the mempool and found it difficult to read and non-modular. Based on its simplistic handling of allocations and complex code, ideally I would recommend replacing it with a permissively licensed library that can achieve better results, if we can find one.
