### ISSUE TITLE
Segmentation fault in examples/charm++/arraysection and cleanup 

### ISSUE THREAD

**Issue by raghavendrak** [UIUC-PPL/charm#1978]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1978*

---
Segmentation fault when the example in 
charm++/arraysection is run.
On a different system setup it runs into an error
`contribute: SectionID is not initialized`

Also, the example needs to be cleaned up to reflect what is quoted in the manual.
2D section array example needs to be added.

**Comment by stwhite91** [comment]
*Original date: 2018-09-12 02:25:18*

---
Some things to clean up:

1. It doesn't compile on my Mac using GCC:
```
check.C:35:37: error: use of parameter outside function body before ']' token
  void done(int q, int output[q]){
```
That line should be:
```
  void done(int q, int output[]){
```

2. The CkArgMsg* passed to the Mainchare's constructor is not deleted anywhere.

3. Section creation should use the std::vector-based API rather than the old CkVec one.

4. There are several lines of commented-out code, which should just be removed.

5. The recvMsg() currently calls 'CkFreeMsg(msg);', but I think it's cleaner / more consistent to do 'delete msg;'

**Comment by stwhite91** [comment]
*Original date: 2018-09-12 13:20:43*

---
Cleanup here: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4566/~~ https://github.com/UIUC-PPL/charm/commit/e1f98b3c31a50844411612f9b0dbd0f6c46839e5

Still need a 2D example...

**Comment by stwhite91** [comment]
*Original date: 2018-09-12 13:26:51*

---
The example builds and runs correctly now for me. Can you try it, and then add a 2D example?

**Comment by raghavendrak** [comment]
*Original date: 2018-09-12 15:25:13*

---
Yes, it works for me. Will add a 2D array example.

**Comment by stwhite91** [comment]
*Original date: 2018-09-13 00:51:43*

---
2D section example: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4568/~~ https://github.com/UIUC-PPL/charm/commit/9212ce48e779fc3360e491b224cae977df4dd0eb
