### ISSUE TITLE
Exit hang on Summit with pami

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#1988]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1988*

---
NAMD occasionally hangs at exit when using pami&pamilrts layer on Summit because of a race condition. Below is the key code piece where the race condition happens. exit(0) might get called before all threads call pthread_exit(0). It looks like the problem was prevented with a hack on BlueGeneQ by adding a sleep on rank 0 before exit. 
 

```
<code class="c">
charm-v6.8.2/src/arch/pami/machine.c line 1038:
CmiNodeBarrier(); //wait for all worker threads
if (rank0) {
#if CMK_BLUEGENEQ
   Delay(100000);
#endif
   exit(0);
}
else
   pthread_exit(0);
</code>
```

The sleep is not there for non-BGQ architectures. Adding usleep(100000) resolved the hang for me on Summit. A simple counter based exit-scheme could be implemented too.

**Comment by nitbhat** [comment]
*Original date: 2018-10-10 16:21:26*

---
I'm currently not able to run jobs on Summit as their batch queue is inactive because of acceptance testing. For now, I'll try to reproduce it on BGQ by removing the Delay(100000). 

Bilge, what are the conditions for reproducing the hang? Do you see the hang with other smaller applications? How many nodes/threads did you run it with?

**Comment by nitbhat** [comment]
*Original date: 2018-10-10 20:28:35*

---
Gerrit: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4681/~~ https://github.com/UIUC-PPL/charm/commit/3df8e38696921d877f28ba5e2885f9b7701ae314

I was not able to reproduce the bug on BG/Q with smaller examples or tests. And for some reason, I couldn't compile NAMD successfully on BG/Q. 
Bilge, could you verify if the fix is working?

**Comment by bilgeacun** [comment]
*Original date: 2018-10-12 17:55:34*

---
I did about 200 NAMD runs and there are no hangs with the fix. It used to hang 1 in 20 when large number of threads (+ppn42) is used.
