### ISSUE TITLE
Make VERBS layer work on non-Mellanox hardware

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#199]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/199*

---
We want to be able to run the ibverbs machine layer on non-Mellanox interfaces. Most notably, Qlogic hardware.

**Comment by ericjbohm** [comment]
*Original date: 2013-06-06 20:39:27*

---
The main issue with our implementation is that we use the Shared Receive Queue (SRQ) semantic to manage all Work Requests (WR)  on our Queue Pairs (QP).  The Spec does not require SRQs to support all types, notably only Mellanox supports RDMA Read WRs on QPs in SRQs.  Just that they return an error when they cannot support a type listed in the initial list during SRQ creation.  This subtlety was lost on us during the implementation phase due to our only having access to Mellanox implementations at that time.  The aggressive use of SRQs allows us to just test the SRQ for all WR activity on all QPs and handle transactions as they appear.  It gives a fairly uniform low overhead code path for all QPs and WR packets.

The problem with this is that we support RDMA Read on all QPs.  Which means we can't use SRQs to manage them on platforms which do not support RDMA QPs in SRQs.  This necessitates the creation of an alternate code path which manages QP receiveQs manually without SRQs.  Such a code path would need to issue distinct ibv_post_recv calls with appropriate WRs for each QP's receiveQ, to replace the existing scheme of posting a shared set of WRs to one SRQ via ibv_post_srq_recv.

The main site for things like OFED libibverbs API downloads is:
http://www.openfabrics.org/

A good online source for the VERBS Protocol specification is:

http://www.afs.enea.it/asantoro/V1r1_2_1.Release_12062007.pdf

Chapters 10 and 11 are most pertinent to our implementation.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-06 20:44:11*

---
If my understanding when I entered this is correct, that our primary target is Qlogic hardware, then we should also look at Qlogic's PSM API as well. From what I've heard, it's much nicer to work with than ibverbs. Sadly, it would be another vendor-specific port, but that may actually be less effort than hacking up the verbs port we have.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-07 17:00:06*

---
I think moving to PSM may be more work than changing existing verbs. Also, it is guaranteed to make verbs running on any general platform. If needed, we can do a PSM specific port in addition later.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-06-17 19:48:53*

---
Discussed the problem with Eric. 
Wrote an alternate code path which does not use SRQ. Need to test. Waiting to get Qlogic machine account from Xiang/Disney

**Comment by PhilMiller** [comment]
*Original date: 2013-06-17 19:51:52*

---
It might be a good idea to also ask some of the LLNL interns to test this on the clusters there. I believe they have a bunch of Qlogic hardware.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-01 21:37:51*

---
The code for this got merged back in June. Some unrelated issues with ibverbs support impeded testing, but those seem to have been resolved. If this code works, this issue should be marked 'Resolved'

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-01 21:40:58*

---
Second Phil's comment, but it will be good to make the selection either configure driven or make sure that it can be done by passing some -D flags to charm build (and state them somewhere visible).

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-03 18:25:33*

---

I added a runtime check in the code so that if the default parameters fail, it tries the same failed call with qlogic-specific parameters. If even those fails, it will report an error.

Also, there is a define directive QLOGIC which can be used to enable qlogic code. Determining it on configure time might be somewhat difficult so I am avoiding that. Further, I do not have access to a non-mellanox machine to try out these configuration tests.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-04 16:33:49*

---
Could someone with access to non-SRQ hardware (Xiang, looking at you, hopefully), test this and report whether it works or not.

Please also make suggestions for how switching this on/off could be made easier, if possible. If it's fine as is, then we should close the issue and move on.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-17 19:26:07*

---

Xiang checked it on the Disney cluster. I am marking it resolved.
