### ISSUE TITLE
AMPI with -O*

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#202]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/202*

---
Multiple people have reported that AMPI crashes at higher optimization levels. More specific instances to be added later.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 19:07:14*

---
Please consult with Nikhil to reproduce this bug, then investigate.

**Comment by stwhite91** [comment]
*Original date: 2015-02-09 15:28:34*

---
This problem is not easily reproducible. I built AMPI using the Intel compilers --with-production and then built AMPI programs with different levels of optimization. None failed.

This could have been an Intel compiler bug that has since been fixed (I used the Intel/14.0 compilers).

**Comment by stwhite91** [comment]
*Original date: 2015-04-06 17:58:52*

---
I tried reproducing the problem with Intel compiler versions 11, 14, and 15 but could never reproduce the issue.
