### ISSUE TITLE
Mac MPI build with MacPorts clang of v6.9.0-rc2 fails configure

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2020]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2020*

---
Jozsef Bakosi identified this on the mailing list. It looks like configure is somehow messing up the C++11 flags.

**Comment by jcphill** [comment]
*Original date: 2018-10-27 17:09:28*

---
It would be useful to post the details here.  It worked on my older Mac build boxes yesterday so try not to break those fixing this.

**Comment by matthiasdiener** [comment]
*Original date: 2018-10-27 18:40:24*

---
Here is what Jozsef wrote:

==================

Hi folks,

I'm trying to build on mac using a macports-installed clang and openmpi:

$ clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/jbakosi/tools/macports/libexec/llvm-6.0/bin

$ mpicc --showme
/Users/jbakosi/tools/macports/bin/clang-mp-6.0 -I/Users/jbakosi/tools/macports/include/openmpi-clang60 -L/Users/jbakosi/tools/macports/lib -L/Users/jbakosi/tools/macports/lib/openmpi-clang60 -lmpi

Build:

$ ./build charm++ mpi-darwin-x86_64

tmp/charmconfig.out and tmp/config.log attached and I'm not sure what
the problem is.

Using a similar procedure with gcc7 works fine. Any help is appreciated.
Please let me know if you need more information.

=============================

Relevant error from charmconfig.out:

```
mpicxx -mmacosx-version-min=10.7 -D_DARWIN_C_SOURCE -I../include -I. -c test.cpp -o test.o -std=c++11
test.cpp:8:6: error: no template named 'unique_ptr' in namespace 'std'
std::unique_ptr<int> i;

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-10-29 17:11:25*

---
I think this should fix it but I'm not 100% it's the cause of the problem: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4743~~ https://github.com/UIUC-PPL/charm/commit/8343c590d283cff206e95d21bfdc17fc9f4b639e

**Comment by stwhite91** [comment]
*Original date: 2018-10-29 17:23:42*

---
Can you link Jozsef to the patch and maybe he can test it soon?

**Comment by stwhite91** [comment]
*Original date: 2018-10-29 23:34:39*

---
Jozsef verified that this patch fixed the issue.
