### ISSUE TITLE
Reduce SDAG copies when possible

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#226]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/226*

---
SDAG makes more copies of data than necessary for parameter marshaled EPs.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 20:49:04*

---
I've started looking at the new code, and I was concerned that it would bump into the lack of SMP safety in PUP::able's registration paths (see pup_util.C PUP_getRegistry()). Looking at the history of pup_util.C, Gengbin tried to address this concern at that layer, but backed away because the PUP code is supposed to be stand-alone from the runtime system itself.

Fortunately, the outer-level registration code is only called on rank 0 of each process (ck-core/init.C), followed by a barrier. I'm noting this here so that someone else following along doesn't wonder the same thing.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 20:52:17*

---
I notice that the class `SDAG::Closure` defines virtual methods, but does *not* define a virtual destructor. It's rather important that it do so, since its children do have non-trivial destructors.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 20:56:43*

---
In `MsgClosure::pup`, you invert the presence of a message for the boolean, and then you invert that boolean for the test. Why not `bool hasMessage;`?

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 20:57:18*

---
The constructor for `Closure` will be called before the initialization lists of all of its child classes; why have the `Closure::init()` method at all?

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 21:05:30*

---
I have to admit: I can't follow how the `vector<Closure*> closure` in `SDAG::Continuation` ends up getting PUPed correctly. I know there's some magic involving pointers to `PUP::able` objects, but I can't quite trace it through. Would you mind explaining, and perhaps commenting that?

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 21:17:35*

---
Minor nit: the returned `Buffer *` from `Dependency::pushBuffer()` is never used. Unless there's a good reason to keep it, it should be dropped.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 21:20:52*

---
It looks like `Dependency` doesn't have a destructor defined, so anything that it's keeping pointers to when it's deleted will leak.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-19 21:39:36*

---
I've now reviewed the changes to everything outside `src/xlat-i` and the changes within related to removing the forward/connect/publishes constructs.

For ease of review and later understanding, would you mind rebasing so that the 4 commits that cover that removal happen first, as a single commit? They are
> 1ad5d871efc59c6bd8309833a35a6412dfc43e4f fb913b3f0cc84d7905ea674674c09606a8883ca9 a40f78209ac159c0e6dc7c418a12c9e5a5d353a6 c7ab6b8a6700ab2bf7d6a4d64f09ab9ba12acc48
Note that the last of these also deletes some unrelated dead code as well - that should stay in its own separate commit. I'd recommend a two-phase interactive rebase operation - the first to split that last commit in two, and the second to bring all 4 related commits up front into one bigger commit.

**Comment by lifflander** [comment]
*Original date: 2013-06-20 07:20:41*

---
Phil Miller wrote:
> I notice that the class `SDAG::Closure` defines virtual methods, but does *not* define a virtual destructor. It's rather important that it do so, since its children do have non-trivial destructors.

Good point. Will fix.

**Comment by lifflander** [comment]
*Original date: 2013-06-20 07:21:16*

---
Phil Miller wrote:
> In `MsgClosure::pup`, you invert the presence of a message for the boolean, and then you invert that boolean for the test. Why not `bool hasMessage;`?

Sounds good. Makes the code more readable.

**Comment by lifflander** [comment]
*Original date: 2013-06-20 07:24:15*

---
Phil Miller wrote:
> The constructor for `Closure` will be called before the initialization lists of all of its child classes; why have the `Closure::init()` method at all?

Note that `SDAG::Closure` is actually an abstract class. So it does not have a constructor. Yet it has state that needs to be initialized. Rather than repeat the initialization code, I opted for an `init()` method. Making it non-abstract should probably be the correct way, but due to limitations (and possibly my improper understanding of `PUP::able`), I made it abstract. Note that it can never actually be constructed so maybe that is the right solution.

**Comment by lifflander** [comment]
*Original date: 2013-06-20 07:26:25*

---
Phil Miller wrote:
> I have to admit: I can't follow how the `vector<Closure*> closure` in `SDAG::Continuation` ends up getting PUPed correctly. I know there's some magic involving pointers to `PUP::able` objects, but I can't quite trace it through. Would you mind explaining, and perhaps commenting that?

Yes, there is deep magic, which took me a while to understand. Really, `PUP::able` needs the commenting I think. You are suggesting commenting in my code to explain how this works? Or a comment in redmine?

**Comment by lifflander** [comment]
*Original date: 2013-06-20 07:28:53*

---
Phil Miller wrote:
> Minor nit: the returned `Buffer *` from `Dependency::pushBuffer()` is never used. Unless there's a good reason to keep it, it should be dropped.

Good point. That is a remnant of the previous implementation.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-20 17:42:53*

---
So I just tried to actually build the code, and encountered the following:

```
../bin/charmc  -g -c -I. BlockLB.C
In file included from CkMarshall.decl.h:7,
                 from charm++.h:142,
                 from BlockLB.decl.h:3,
                 from BlockLB.C:2:
sdag.h: In member function ‘void SDAG::Closure::packClosure(PUP::er&)’:
sdag.h:16: error: no match for ‘operator|’ in ‘p | ((SDAG::Closure*)this)->SDAG::Closure::continuations’
In file included from CkMarshall.decl.h:7,
                 from charm++.h:142,
                 from BlockLB.decl.h:3,
                 from BlockLB.C:2:
sdag.h: In member function ‘virtual void SDAG::ForallClosure::pup(PUP::er&)’:
sdag.h:52: error: no match for ‘operator|’ in ‘p | ((SDAG::ForallClosure*)this)->SDAG::ForallClosure::val’
sdag.h: In member function ‘virtual void SDAG::MsgClosure::pup(PUP::er&)’:
sdag.h:73: error: no match for ‘operator|’ in ‘p | isNull’

```
and so on for every PUP in sdag.h

I see these errors on GCC 4.4.3 on a lab machine running Ubuntu 10.04 and 4.6 on Ubuntu 12.04. Compilation with Clang 3.1 seems to work fine, which is why it would build on your Mac. I'll try it with GCC 4.7 and 4.8 when I get home tonight.

It looks like this is an issue of what namespace the `operator|` overloads appear in. The current pup.h has them in the global namespace, which doesn't match where either of the arguments are defined. I don't know which compiler is right or wrong in this case.

I will note that switching to `p(foo);` syntax papers over the issue, since `operator()` is a member function of `PUP::er`.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-20 17:59:59*

---
It gets worse:

```
phil`thrift:~/projects/devcharm/net-linux-x86_64-clang-sdag/tests/charm++/megatest (nocopy-sdag *$)$ make
../../../bin/charmc  -o marshall.o marshall.C
In file included from marshall.C:9:
In file included from ./marshall.h:7:
./marshall.decl.h:940:18: error: field has incomplete type 'flatStruct'
      flatStruct s;
                 ^
marshall.C:8:7: note: forward declaration of 'flatStruct'
class flatStruct; class pupStruct; class parent;
      ^
In file included from marshall.C:9:
In file included from ./marshall.h:7:
./marshall.decl.h:962:17: error: field has incomplete type 'pupStruct'
      pupStruct s;
                ^
marshall.C:8:25: note: forward declaration of 'pupStruct'
class flatStruct; class pupStruct; class parent;
                        ^
In file included from marshall.C:9:
In file included from ./marshall.h:7:
./marshall.decl.h:984:17: error: field has incomplete type 'pupStruct'
      pupStruct s;
                ^
marshall.C:8:25: note: forward declaration of 'pupStruct'
class flatStruct; class pupStruct; class parent;
                        ^
In file included from marshall.C:9:
In file included from ./marshall.h:4:
In file included from ../../../bin/../include/charm++.h:7:
In file included from ../../../bin/../include/charm.h:12:
../../../bin/../include/pup.h:905:4: error: no member named 'pup' in 'PUP::er'
        t.pup(p);
        ~ ^
./marshall.decl.h:1018:11: note: in instantiation of function template specialization 'operator|<PUP::er>' requested here
        p | p;
          ^
4 errors generated.
Fatal Error by charmc in directory /dcsdata/home/phil/projects/devcharm/net-linux-x86_64-clang-sdag/tests/charm++/megatest
   Command clang++ -I../../../bin/../include -D__CHARMC__=1 -fno-stack-protector -c marshall.C -o marshall.o returned error code 1
charmc exiting...
make: *** [marshall.o] Error 1

```

**Comment by lifflander** [comment]
*Original date: 2013-06-20 23:36:47*

---
Phil Miller wrote:
> It gets worse:
> [...]

I am having a lot of trouble fixing this problem. All my development has been with clang so far. I tried several things that did not help.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-21 01:35:01*

---
Even g++ 4.8.1 isn't happy with it, for the same reasons, while clang 3.3 is. One of them has to be wrong

**Comment by PhilMiller** [comment]
*Original date: 2013-06-21 04:02:37*

---
ICC 12 and 13 seem to be fine with it.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-21 04:03:10*

---
Lol xlc:

```
../bin/charmc -host  -c CSdagConstruct.C
"CSdagConstruct.C", line 551.37: 1540-0207 (S) No common type found for operands with type "xi::XStr" and "const char [2]".
Fatal Error by charmc in directory /home/phil/code/charm/net-linux-ppc-xlc/tmp
   Command xlC_r -I../bin/../include -D__CHARMC__=1 -c CSdagConstruct.C -o CSdagConstruct.o returned error code 1
charmc exiting...
gmake[1]: *** [CSdagConstruct.o] Error 1
gmake[1]: Leaving directory `/gpfs/vesta-home/phil/code/charm/net-linux-ppc-xlc/tmp'
```
Code fixed to make the conversion explicit. </sigh>

**Comment by lifflander** [comment]
*Original date: 2013-07-03 00:44:26*

---
Ready for review and merging.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 19:03:56*

---
It looks like you should be able to replace the few remaining calls to `generateSignature` with what's currently named `generateSignatureNew`, since the `params` argument is `NULL` at all of the call sites, and the handling of parameters is the only way in which they differ. At that point, you can rename them to drop the 'new'.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 19:19:46*

---
These four new methods have a couple repeated dummy implementations that may be deleted from `class Member`

```
    virtual void outputClosuresDecl(XStr& str) { (void)str; }
    virtual void outputClosuresDef(XStr& str) { (void)str; }
    virtual void genClosureEntryDecls(XStr& str) { }
    virtual void genClosureEntryDefs(XStr& str) { }
```

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 19:32:30*

---
I'm a bit bothered by the loss of uniformity in divergent calls like this:
```
if (!isSDAGGen)
  callEach(&Parameter::beginUnmarshall,str);
else
  callEach(&Parameter::beginUnmarshallSDAGCall,str);
```
 But I think that's fine to leave for the time being, and deal with later.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 19:41:33*

---
`class Entry` still has some 'connect'-related detritus in its members and constructor. If you're cleaning that out, clean it all the way.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 19:46:57*

---
`Entry::genCall()` takes a parameter `bool isSDAGGen` that's completely unnecessary, since it is always passed the same expression made of other members of `Entry`: `(sdagCon || isWhenEntry)`. Inside `genCall`, you could replace that variable with a method call of the same name that evaluates that expression.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 20:14:04*

---
The names `generateSignatureNew, generateCallNew, generateWhenCodeNew` are an abomination. Especially given that the latter 2 no longer have their original counterpart.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 20:18:55*

---
In `SdagConstruct::labelNodes()`, you may as well shift the underscores into `createLabel`, since it's repeated in every single case.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 20:42:56*

---
Looks like the critical path detection code in `WhenConstruct::generateCode()` got dropped on the floor. I forget if we had decided that was an acceptable consequence, or hadn't mentioned it.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 20:58:30*

---
Factor out length calculation of EntryList objects.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 21:13:01*

---
`CMK_REFNUM_TYPE` in place of `int` everywhere (`tryFindMessage`, generated code)

**Comment by PhilMiller** [comment]
*Original date: 2013-07-11 22:17:36*

---
`SdagConstruct::generateSdagEntry` seems to duplicate the signature generation code a bit. I recognize that this is at an interface of old and new code, but the repetition seems problematic.

**Comment by lifflander** [comment]
*Original date: 2013-07-23 01:40:47*

---
merged into mainline

**Comment by PhilMiller** [comment]
*Original date: 2013-08-09 17:44:45*

---
Implementation of #27 exposed a bug in which a reference number matching expression was re-evaluated every time a when clause was entered, rather than only when the continuation is first set up. After the fix, I've confirmed that the affected code now runs correctly without my client-side workaround.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-11 19:56:24*

---
Nikhil and I found out why the win64 builds broke after this code got merged. The variable `genClosureTypeNameProxy` was left uninitialized, and used in a conditional. After observing astoundingly weird behavior on Windows, we ran charmxi under valgrind on Linux and saw this report. After NULL-initializing it in Entry's constructor, the Windows builds get through the ci files without trouble.

**Comment by lifflander** [comment]
*Original date: 2013-08-11 22:33:44*

---
Thanks Phil and Nikhil for tracking this down. I've had it on my list of TODOs for a long time but haven't chased it down.

Jonathan

**Comment by PhilMiller** [comment]
*Original date: 2013-08-13 20:49:20*

---
There's a worrisome warning in bigsim builds (present before I started mucking with Makefile, so not related to that):

```
../bin/charmc   -c -I. sdag.C
In file included from ../bin/../include/ckarrayindex.h:6:0,
                 from ../bin/../include/envelope.h:10,
                 from sdag.h:28,
                 from sdag.C:1:
../bin/../include/charm.h:34:0: warning: "CkWallTimer" redefined [enabled by default]
../bin/../include/middle-blue.h:39:0: note: this is the location of the previous definition
../bin/../include/charm.h:35:0: warning: "CkCpuTimer" redefined [enabled by default]
../bin/../include/middle-blue.h:40:0: note: this is the location of the previous definition
```

Jonathan, could you please investigate?
