### ISSUE TITLE
<cuda-runtime.h> not found while building netlrts-linux-x86_64-cuda builds

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2427]
Autobuild log: http://charm.cs.illinois.edu/autobuild/old.2019_07_25__01_04/netlrts-linux-x86_64-cuda.txt
```
In file included from ampi.h:11:0,
                 from compat_ampius.C:2:
/scratch/autobuild/netlrts-linux-x86_64-cuda/charm/netlrts-linux-x86_64-cuda/bin/../include/hapi.h:3:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.
/bin/cp -f sim.h ../../../../include/pose/sim.h
```

**Comment by stwhite91** [comment]
Any update on this? It's release-critical

**Comment by matthiasdiener** [comment]
This appears to be caused by the fix to bug #2062 (#2121). Not sure what the best way to fix this is. Not only is the include path missing, but also the library path and the -lcudart library.

**Comment by minitu** [comment]
One problem is the ordering of libraries being linked in with AMPI: `-lcudahybridapi` must appear before `-lcudart` because HybridAPI depends on the CUDA runtime library. Matt is working on a quick fix, but a better long-term solution would be to make HybridAPI a header-only library, which I believe should be possible.

**Comment by matthiasdiener** [comment]
Patch #2460 caused new linking issues.

**Comment by matthiasdiener** [comment]
After reverting the PR above (#2466), this issue has been resolved. The current cuda autobuild failure is tracked in #2467.
