### ISSUE TITLE
MPI builds on BGQ do not compile due to location of MPI library

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#243]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/243*

---
Due to path changes, MPI builds on BGQ are currently not compilable. Task is to set the paths properly.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-25 15:20:16*

---
Take a look at autobuild - the check against `conv-mach-opt.sh` needs to be relative to the `tmp/` directory, not the current working directory.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-26 19:48:38*

---
Missing path-relative term in the patch meant it didn't build in subdirectories or an anywhere outside `mpi-bluegene-xlc/tmp`. Adding `$CHARMINC/` to the check of `conv-mach-opt.sh` seems to do the trick.

Fully tested `mpiwrappers-xl, mpiwrappers-gcc) * (mpi-bluegeneq, mpi-bluegeneq-xlc)`. The results are a bit strange for `mpiwrappers-gcc` with `mpi-bluegeneq-xlc`: because the build explicitly uses `mpixlcxx`, that build works even though the mpi wrappers are notionally GCC. That behavior seems to be perfectly fine, though. The other three combinations do as expected.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-27 14:37:29*

---
Autobuild is working.
