### ISSUE TITLE
Update documentation of GPGPU keywords

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#2721]
The manual lists the following as reserved words, but their use is not documented in the manual at all. If they no longer exist, they should be removed, otherwise documentation should be added.

- accel
- readwrite
- writeonly
- accelblock

**Comment by minitu** [comment]
AFAIK, although the accel-related keywords are processed in `xlat-i`, the actual implementation of accel is not yet merged in the mainline (https://charm.cs.illinois.edu/gerrit/#/c/charm/+/824/). We don't want to completely abandon it, but neither I or anyone else in the accel group has had the chance to thoroughly look it over (since a few years ago). Should we only get rid of the xi parsing and remove the keywords from the manual for now?

**Comment by rbuch** [comment]
Yeah, they are implemented on the `accel` branch and (in my opinion) should remain as reserved words unless we decide to definitely abandon it. I don't think that it should be completely abandoned, so I'd suggest to keep them in both the parsing and manual right now, but adding something to say that they're reserved for future/experimental use.

**Comment by epmikida** [comment]
Yes, I agree. They are still reserved words, so they should remain in the manual. We just need some text stating they are not yet utilized or something along those lines.
