### ISSUE TITLE
Don't duplicate 'net' charmrun code

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#285]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/285*

---
The code for the TCP/IP network ('net') charmrun is duplicated in three different machine layers: net, netlrts, and verbs. There have been updates to the various instances such that the copy under 'net' is ahead of the others.

This situation is untenable in the long term. This code is not expected to substantially diverge, and bug fixes in one instance are likely applicable to all the others. That means there should only be a single copy of the code, shared among all of them.

My suggestion is as follows:
* the code in `src/arch/net/charmrun` should move to `src/arch/util/charmrun-src`
* the `Makefile.machine` of those three architectures should specify a `charmrun` target that does what the current main `Makefile` does in the directory case currently
* the central `Makefile` target '`charmrun-target`' should depend on `charmrun`

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-05 05:54:27*

---

Removed the duplicated copies and followed Phil's suggestion. Tested on net, lrts, mpi etc. Need to test on windows build as well, since moving charmrun location will impact that build as well. I made a minor change to Makefile.win32 - basically the location where to copy charmrun from, how do I test on windows? I will check-in once it is ensured that it does not break windows build.

Code branch: abhigupta/charmrun-cleanup

**Comment by PhilMiller** [comment]
*Original date: 2013-10-18 21:10:50*

---
Things mostly look good. There may be an issue related to the Makefile change on multicore-win*. Could you look into that and either fix it, or figure out that it's unconnected to this effort and close this?

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-24 17:29:07*

---

Fixed the multicore-win issue related to this.
