### ISSUE TITLE
Reduction Starting messages

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#29]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/29*

---
Due to migratability, the current Chare Array reduction mechanic triggers partition wide broadcasts.  This is problematic for several reasons.

1. For arrays which do not migrate, this is pure overhead.
2. For arrays which do not span the entire partition and will not migrate off their subset of cores, the message traffic to unused cores is overhead
3. This happens even when arrays are constructed with flags that disable anytime migrate and anytime insertion.

The task is to implement a version of the chare array reduction which can perform better for the *very* common case of no anytime migration and no anytime insertion.  Notionally, the empty core and how many elements per core tracking issues should be something which can be determined after doneInserting completes.  Possible extensions would be to allow for reset of such quantities in dynamic situations by doneInserting, or some other mechanism.

**Comment by PhilMiller** [comment]
*Original date: 2013-02-07 21:16:10*

---
`Eric: Is this actually critical to shipping the next release? It hadn't been talked about that way in previous discussion. Also, it'd be nice to do this after the reduction code is refactored to a single instance (issue #12).

**Comment by ericjbohm** [comment]
*Original date: 2013-02-07 21:30:52*

---
Phil Miller wrote:
> `Eric: Is this actually critical to shipping the next release? It hadn't been talked about that way in previous discussion. Also, it'd be nice to do this after the reduction code is refactored to a single instance (issue #12).

Its not critical to next release.  6.5.0 was the only option in the pulldown.  I switched to the blank target.

**Comment by harshithamenon** [comment]
*Original date: 2013-02-22 20:54:08*

---
A first cut implementation of the scheme is implemented. Tested for the case with no local chares on any PE. 

The scheme is described below. If I can get feedback on the scheme that would be helpful.
Goal: Remove the ReductionStarting messages that are sent for every reduction so that the barren PEs contribute.

Scheme:

-A PE is barren if it does not have any local contributor nor any child with any contributor. 
-Each Processor keeps track of whether it is barren or not. It also keeps a list of barren kids.

The idea is
-If a processor realizes it is barren, then send a message to its parent along with the last reduction no it participated. (Make sure to send gcount of whole subtree as well).
-On receiving a message from a child informing the parent that it is not going to participate starting from a particular redNo, add that child to barrenKidsList. 
-Now while checking the finishReduction condition, there would be two checks. One if all the local contributions are done. Second is if remoteMsgCount(redNo) == kidsCount - barrenKidsList.length. This is to say that we are not going to expect remoteMsgCount to include contributions from barrenKids. But this alone is not sufficient as shown in the following case.
Let us suppose the current redNo at PE1 is 5 and its child PE2 informed that it will not contribute starting from redNo 8. PE1 will add PE2 to the barrenKidsList but PE2 has already contributed to reductions from 5 to 7. Hence remoteMsgCount(redNo) == kidsCount - barrenKidsList will not be correct for iterations from 5 to 7. Therefore we need an adjustment counter (adjRem) which takes care of this.
So the check should be remoteMsgCount(redNo) == kidsCount - barrenKidsList + adjRem(redNo).

-During migrations, if a PE changes from barren to active, or vice versa, the information needs to be sent to the parent. (Is this necessary??)

Corner cases

1) If PE1 was barren at redno 7, then an array element migrates with redNo 5, it will be considered as a past contribution and will be sent directly to the root. But now the PE1 should inform its parent that it will contribute to reduction starting from redNo 9. If the parent has already gone past 9, it should consider this as past message and send directly to root. In the current implementation RecvMsg (msgs from kids) is not expected to have a past contribution and it will Abort.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-11 18:17:51*

---
Harshitha, could you please commit the work you've done on this and push it to a branch, so others in the group can see it and try it out?

**Comment by harshithamenon** [comment]
*Original date: 2013-03-12 21:27:05*

---
Have checked in the current implementation into reductionStarting branch.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-28 21:10:45*

---
Now that SC is past, we should get this moving again. Jim encountering reductionStarting as a performance issue in NAMD makes it somewhat more pressing.

Harshitha, do you have a design in mind for the unimplemented methods in the code on the branch? If you'd like help working out how to handle the remaining cases, you should distill the problems left to be solved (post here) and point a few people at them in the next couple days.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-04 20:18:06*

---
Prof Kale has asked me to help with this task. To understand the current status, I have a question - I believe the version checked in works in general case, and handles some corner cases. An exhaustive testing need to be done though. Is it correct? Are there corner cases that need to be implemented? Is there a need to look for further cases to be analyzed?

**Comment by harshithamenon** [comment]
*Original date: 2013-07-08 19:50:37*

---
Yes, the current version works for the general case and exhaustive testing is needed. There are corner cases that needs to be handled.

**Comment by harshithamenon** [comment]
*Original date: 2013-10-01 20:23:29*

---
Changed the previous implementation to some extend. Here is the new scheme.

* Barren: whenever no local contributor and remote children don’t have any contributors for that particular redNo.
* Whenever a PE finds that it is barren, inform the parent the redNo, gcount.
* The parent will receive this isInactive message and add it to a inactive_list which contains gcount, redNo.
* If this makes a PE become barren, then inform its parent. This goes on recursively up the tree.
* Since the barren children don’t contribute to reductions, there should be some way of counting their gcount. So whenever the reduction result is sent to the parent, it should add the gcount from the inactive_list for that redNo as well.
* Whenever we receive a remoteMsg, check whether that remote child is in the inactive_list and if so whether this message makes it active again. If it makes the remote child active again, remove it from the list.
* Note that this does not currently handle insertion of new contributors. The problem is that if a new contributor is added to a PE which was previously barren, it needs to be assigned a redNo and the gcount should reflect that. This can happen if we ask the parent to assign a redNo and then the parent will know that it needs to wait for its child.

Important cases to be handled (handled in the current implementation)

-If the messages are reordered in the following case, care should be taken
> If the previous reduction message is delivered after the isInactive message, then it should not remove the child from the inactive_list. Need to check whether the reduction message is > than the recorded redNo for that remote child. Only in that case remove it.
> If after being inactive, it suddenly receives a contributor which contributes. If the order of the isInactive msg is changed w.r.t the contribution message i.e it is received by the parent after the contribution. In that case, it should not be added to the inactive_list. For that a separate datastructure needs to be maintained which keeps track of the largest redNo seen from a child. If the isInactive msg contains a redNo < the largest seen till now then this is a stale message otherwise add it to the inactive_list.

-In the race conditions mentioned above, the handling of gcount should be done carefully. It should not be double counted and it should not be undercounted.

-If a PE becomes inactive and then becomes active but by the time the contribution is sent to the parent, the reduction result has already been sent to its parent (late migrant of the remote). So here we can directly send to the root as a late migrant message. But note that in this particular case, the gcount of the child has already been counted when the parent sent the reduction result. So the gcount of the late migrant should account for that (subtract from its gcount the accounted gcount) and then be sent to the root. (But can this handle the case when there are multiple late migrants from the same inactive pe?)

-When a contributor moves in to a barren PE, its redNo might be > the last redNo seen in that PE. So we need to fast forward the local redNo. If this is not done, then it will wait for the past reductions to complete before handling this. But note that we should not do this with the root because the root is handling the on-going reductions.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-01 21:22:35*

---
One tiny review comment from my first glance at the code: `CmiTrue` and `CmiFalse` were eliminated from the Charm++ code base a while back (#188). Please replace the cases where they're used with the standard C++ `true, false` constants.

**Comment by harshithamenon** [comment]
*Original date: 2013-10-07 19:58:43*

---
I have implemented another scheme. It is in branch of charm named reductionstarting2.

Instead of totally eliminating ReductionStarting, we use it only when there are inactive remote children. So here is the scheme
1. Whenever a PE realizes that it is inactive, it registers with the parent.
2. Whenever the parent receives any contribution, it checks whether it has any children which are inactive, if so send a ReductionStarting message to the inactive children. It expects children to always respond either with a empty reduction message or with real message.

The advantages of this scheme are
-In the common case where PEs are not barren, there won't be able ReductionStarting messages. 
-When a PE is barren, only its parent will send the ReductionStarting message. There need not be messages going through the entire tree.
-We don't need to have extra logic about new contributors being added since they will be stamped correctly. The semantics is the same as the one right now
-Code is much simpler

The disadvantages are
-There is extra message of ReductionStarting between a parent and the inactive subtree per reduction number.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-22 01:49:21*

---
This got integrated to mainline October 12. With confirmation that applications are happy and that most of the performance impact has been mitigated, we should close this issue.

**Comment by nikhil-jain** [comment]
*Original date: 2013-11-04 22:02:35*

---
Marking resolved since autobuild passes, and no one has reported any issue.
