### ISSUE TITLE
Cray autobuilds show linking error with fsglobals-test-cxx.o

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#3135]
http://charm.cs.illinois.edu/autobuild/old.2020_10_25__01_07/gni-crayxe.txt

```
[100%] Built target ampi_funcptr_shim_fortran
Scanning dependencies of target all-test
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Generating dependencies for pgm.ci
Generating dependencies for mylib.ci
jacobi3d.C(447): warning #3180: unrecognized OpenMP #pragma
    #pragma omp parallel for schedule(dynamic) 
    ^

Warning:
-dynamic was already seen on command line, overriding with -shared.
/usr/bin/ld: fsglobals-test-cxx.o: relocation R_X86_64_PC32 against symbol `extern_global_sameobject' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
Fatal Error by charmc in directory /global/project/projectdirs/m2609/autobuild/gni-crayxe/charm/gni-crayxe/tests/ampi/privatization
   Command CC -dynamic -O2 -rdynamic -L. -shared '-Wl,-rpath,$ORIGIN' -fPIE -fpic -Wl,-undefined,dynamic_lookup fsglobals-test.o fsglobals-test-cxx.o cxx-fsglobals-other-object.o -lcxx-fsglobals-static-library -lz -lrt -lpthread -lm -o cxx-fsglobals.user.so returned error code 1
charmc exiting...
make[6]: *** [Makefile:157: cxx-fsglobals] Error 1
make[5]: *** [Makefile:49: build-privatization] Error 2
make[4]: *** [Makefile:31: build-ampi] Error 2
make[3]: *** [Makefile.tests.common:11: all-test-tests] Error 2
make[2]: *** [CMakeFiles/all-test.dir/build.make:57: CMakeFiles/all-test] Error 2
make[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/all-test.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by evan-charmworks** [comment]
The confusing part about this is why crayxc builds correctly but crayxe does not on the same machine. I don't see any differences in src/arch/ or in the autobuild scripts that could account for this.

**Comment by evan-charmworks** [comment]
When I try manually on Cori, I get the same error on both XC and XE. @nitbhat It looks like the gni-crayxc autobuild actually experiences the same error, but it reports Good anyway.

What is required to fix the build is manually removing `-fPIE` from the compile step for `{fs,pip}globals-test-cxx.o`. No permutations of -fPIC and/or -fpic in the presence of -fPIE resolve the issue. Removing both -fPIC and -fpic from the command line entirely makes the .user.so link step fail in a worse fashion, where the -fPIC error comes up for a symbol containing ".rodata", instead of extern_global_sameobject. I don't need to change the invocations for anything else for the tests to build, and at least on XC they complete successfully with virtualization once that is done.
