### ISSUE TITLE
Test JetAlloc using 6.6.0

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#342]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/342*

---
Our applications should be tested using 6.6.0. Testing should include both correctness testing and performance testing against 6.5.0. The latter may be tricky in some cases due to compatibility issues, please document those cases as they arise.

**Comment by ericjbohm** [comment]
*Original date: 2013-11-18 16:48:55*

---
Any progress on this?

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2013-12-05 03:03:34*

---
No two trials of identical runs give the same performance for this application. 
Hence it is not possible to measure performance change due to charmRTS.
Also, the computations are mostly coarse grained and hence minor performance degradation
might not be noticeable. Finally, the code can be run only on taub and lab machines due to licenses restrictions.

**Comment by PhilMiller** [comment]
*Original date: 2013-12-05 03:06:14*

---
It is possible, in a statistical sense. If the mean gets worse or the distribution of timings otherwise shifts unfavorably, that can be measured.

Regardless of performance considerations, please affirm that the code is fully stable and produces correct output with the latest charm build.

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2013-12-05 20:56:57*

---
I am still getting correct answers to the optimization problems using the latest charm commit (8a03af6384e860a731c33252a1a747b729cd9e41)
