### ISSUE TITLE
Test ChaNGa using 6.6.0

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#343]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/343*

---
ChaNGa should be tested using 6.6.0. Testing should include both correctness testing and performance testing against 6.5.0. The latter may be tricky in some cases due to compatibility issues, please document those cases as they arise.

**Comment by ericjbohm** [comment]
*Original date: 2013-11-18 16:48:27*

---
Any progress on this?

**Comment by harshithamenon** [comment]
*Original date: 2013-11-18 23:00:42*

---
Notes:

1. ChaNGa had compilation problems due to BGLTorus being removed. Fixed it in changa to not use it.
2. In BG/Q with xlc and using smp build, ChaNGa fails to link. Phil has reopened that issue, #104
3. Tested non-smp on BG/Q and compared with charm 6.5 version and did not notice any performance degradation.
4. Tested on net layer and runs fine

**Comment by PhilMiller** [comment]
*Original date: 2014-02-12 20:58:39*

---
Please confirm re-testing with reference to a specific recent commit ID.

**Comment by harshithamenon** [comment]
*Original date: 2014-02-17 19:17:03*

---
Tested v6.6.0-rc2-0-gbcd2533 on 512 nodes of bluewaters in smp mode and compared it with v6.5 and did not find any performance change.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-17 19:28:09*

---
Excellent to hear. Thanks!
