### ISSUE TITLE
7.0.0-rc1 build ChaNGa fails in romio

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#3466]
`./build ChaNGa mpi-linux-x86_64  --with-production` fails in the romio configure.
Note that romio is not needed in the ChaNGa build; `./buildold ChaNGa mpi-linux-x86_64 --with-production` builds successfully.
The OS is SUSE Linux Enterprise Server 12 (x86_64).  The loaded modules are: `Currently Loaded Modulefiles:
  1) gcc/9.3               2) mpi-sgi/mpt.2.15r20
`
The error is:
> configure: error: in `/home3/trquinn/src/charm/mpi-linux-x86_64/src/libs/ck-libs/ampi/romio-prefix/src/romio':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
The config.log file is attached.
[config.log](https://github.com/UIUC-PPL/charm/files/7080103/config.log)

**Comment by stwhite91** [comment]
The error is that we are passing -standalone and -production through to the C compiler for some reason:
```
configure:3791: checking whether the C compiler works
configure:3813: /home3/trquinn/src/charm/mpi-linux-x86_64/bin/ampicc -optimize -production -DAMPI_NO_UNIMPLEMENTED_WARNINGS -standalone -fPIC   conftest.c  >&5
gcc: error: unrecognized command line option '-production'
gcc: error: unrecognized command line option '-standalone'
Fatal Error by charmc in directory /home3/trquinn/src/charm/mpi-linux-x86_64/src/libs/ck-libs/ampi/romio-prefix/src/romio
   Command mpicc -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -I/home3/trquinn/src/charm/mpi-linux-x86_64/include -I/home3/trquinn/src/charm/mpi-linux-x86_64/include/ampi -D__CHARMC__=1 -DAMPI_NO_UNIMPLEMENTED_WARNINGS -O2 -U_FORTIFY_SOURCE -fno-stack-protector -ftls-model=initial-exec -fpic -c conftest.c -o conftest.o returned error code 1
   ```

**Comment by evan-charmworks** [comment]
#3468 should fix the error but needs testing.

**Comment by evan-charmworks** [comment]
@trquinn I've updated #3468 with another potential fix, but I don't know for sure because I have not been able reproduce the problem locally. My guess is that the `mpicc` you are using is seeing the `CFLAGS` variable we pass to ROMIO's configure script and sending it to `gcc`, which would explain why the `Fatal Error by charmc ... Command mpicc` message does not contain `-production -standalone` but GCC identifies them in its error messages anyway. My change is for charmc to unset these variables before invoking the underlying compiler `mpicc`.
