### ISSUE TITLE
Test Episimdemics for 6.6.0

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#355]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/355*

---
Test Episimdemics against 6.6

**Comment by nikhil-jain** [comment]
*Original date: 2013-11-18 22:28:44*

---
Per Jae-Seung:

I checked out git clone on Nov 16. I tested the version on vulcan (BG/Q) up to 4K compute nodes using the entire US data. I also tried it on two SandyBridge/Infiniband clusters with mpi-linux-x86_64 build up to 256 compute nodes. It is working as expected on these platforms.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 23:02:38*

---
Sounds good

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-30 19:48:17*

---
Reassigning to Lukasz to coordinate with Abhishek.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-12 20:58:39*

---
Please confirm re-testing with reference to a specific recent commit ID.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-15 00:02:58*

---
Jae-Seung has verified that running with the three following commits yields similar performance: 

Nov. 14: b283a8032c200173f7f2631bf5b4a26038ba1288
Jan.6: aabd9a6b75798f248302c45ec29be6aaefd40048
Feb. 12: 340161b5d09ab55de714e3d2db2e15069658e90b

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-16 00:49:38*

---
Reopening this, as Jae-Seung has further reported that when using a build of charm from Oct. 13: commit 390648c, performance is 6% better than with the other three builds (Nov, Jan, Feb - see previous post).

**Comment by ericjbohm** [comment]
*Original date: 2014-02-17 20:11:02*

---
Please do a git-bisect and narrow the regression down.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-24 05:59:28*

---
Here are the final results of EpiSimdemics regression testing on Blue
Gene/Q, showing all the commits that caused significant regression or
improvement in performance since early last November. The net
regression for the period from 11/8 to 2/24 is 10%, but given that
there were also several commits that improved performance, fixing all
the sources of regression could improve performance by up to 20% for
this application. Also, let me reiterate that it would be very useful
to have automated performance tests for a couple fine-grained
applications and benchmarks done after every commit or at least daily.
The tests I was running took just over a minute each, including
startup time, and consumed about 20 SUs each. We can easily afford
that.

Note the assignees responsible for resolving the regression,
corresponding to the people that made the changes. People whose
changes improved performance likewise have an assignment, which is to
try to identify the reason for the improved performance, so that we
may gain insight for future optimizations.

Try to have something to report by the next core meeting, which I
believe is tomorrow.

Commits are listed in the order in which they were merged in, which is
not the same as the order of the dates in the logs.

Finally, in about half my tests for commits since mid-January, and
none of the commits before that, the program hangs. While I cannot say
for sure right now which commit led to the hang, the first commit for
which I had this issue is 967eccd, corresponding to reversal of the
envelope reduction. Eric, try to identify whether anything in your
commit could cause problems. Changes to the envelope in particular
deserve close scrutiny, where adding and removing data members and
even changing the order in which they are declared could be enough to
cause trouble. I will try running with the commit just prior to that
to verify that this is the commit causing the hang.

10/8 (0c386c6): 9.67s
11/5 (0f6dd83): 9.29s
11/8 (9fe3d55): 9.31s
11/8 (d06f4e): 9.31s
11/9 (4a59427): 9.44s    <---------------- REGRESSION 1.4% [regression may be in ancestor from 8/12 or before that]       *PHIL*
11/12 (7ebe67b): 9.25s  [4a59427 is not an ancestor]
11/12 (e73dccc): 9.43s   [not a regression - affected by 4a59427]
11/13 (797d916): 9.64s  <---------------- REGRESSION 2.2%  [regression goes away when using the flag `-fno-asynchronous-unwind-tables`] *NIKHIL*
11/14 (7a3ee37): 9.58s
11/14 (b283a8): 9.52s
12/6 (211f290): 9.66s
12/6 (9bcafc5): 9.87s      <---------------- REGRESSION 2.2%    *JONATHAN*
12/10 (d83164): 9.63s    <++++++++++ IMPROVEMENT 2.5% [addresses regression from 12/6?]   *JONATHAN*
12/3 (575af7): 9.41s     <++++++++++ IMPROVEMENT 2.3% [causes intermittent hangs!] *GENGBIN*
12/31 (72a354): 9.42s
12/31 (39db95): 9.60s    <----------- REGRESSION 1.9% *PHIL*
12/31 (6b2f7a8): 9.63s    
12/20 (3291c16): 9.60s   
1/14 (d8c3adf): 9.68s
1/16 (967eccd): 9.37s     <++++++++++ IMPROVEMENT 3.2% [reversal of envelope reduction changes]   *ERIC*
1/23 (62941b): 9.33s
1/23 (afe5e74): 9.35s
1/24 (3d170bd): 9.37s
1/24 (ddd5cce): 9.63s     <--------------- REGRESSION 2.8% [regression goes away when LB userdata is disabled; 
                                                            I think it should be disabled by default] *HARSHITHA*
1/21 (9e7d57e): 9.61s
1/21 (c7b4189): 9.66s
1/21 (1af2a73):  9.62s
1/28 (cb2ee50): 9.74s     <--------------- REGRESSION 1.2% *PHIL*
2/3  (964cbcd): 9.76s
2/5  (375b185): 9.95s      <--------------- REGRESSION 1.9% *PHIL*
2/11 (b159235): 9.96s
2/11 (340161b5): 10.38s  <---------------- REGRESSION 4.2% [TRAM routing refactoring] *LUKASZ*
2/12 (c2b6ebfb): 10.37s
1/16 (28998a1): 10.27s   <+++++++++++ IMPROVEMENT 1.0%   *PHIL*
2/11 (32f1f5): 9.85s         <+++++++++++ IMPROVEMENT 4.1%   *PHIL*
2/15 (f8f673): 9.87s
2/19 (b670687): 9.85s
8/27 (c5c151e): 10.22s    <---------------- REGRESSION 3.8% *PHIL*
2/23 (3760b51): 10.22s
2/24 (9d06a86): 10.21s   [supposed to turn off LB userdata but performance is not improved]
2/24 (8074b89): 9.99s    <++++++++++++ IMPROVEMENT 2.2% *PHIL*
3/5  (6c0aea): 10.05s
3/29 (80ffb2): 10.30s
4/20 (ea1ff8): 10.20s
?
6/2  (72f946): 9.61s     <++++++++++++ IMPROVEMENT 5.9%

**Comment by PhilMiller** [comment]
*Original date: 2014-02-24 06:15:33*

---
There's some commonality between 4a59427 and ddd5cce, in that both increase the amount of data stored in the load balancing database and collected to provide to the LB strategy. This leads me to wonder whether whether EpiSimdemics might not benefit more from fine-tuning how much effect it feels from load balancer operation, such as by using MetaLB to adaptively adjust timing.

Of course, that does not argue that applications not using these features should pay a price in performance for the cases where they are desirable. For now, it's pretty easy to say that we shouldn't carry object migration sizes by default, since nothing in our repository uses them (I just checked). The suggested use we had of them internally was for #65, though I think there were application requests for the same.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-24 06:36:40*

---
EpiSimdemics is not currently using load balancing, at least not in the version I was running, and I used +LBOff for all tests. This suggests that we are incurring LB-related overhead even when it is turned off, so that may be a possible target to consider for optimization.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-24 18:59:09*

---
1/28 (cb2ee50): 9.74s <--------------- REGRESSION 1.2% PHIL
2/5 (375b185): 9.95s <--------------- REGRESSION 1.9% PHIL

These two regressions are surprising, since they're both changes in code that should never be running during EpiSimdemics. The first is a refactoring of CmiAbort and KillOnAllSigs to share common code. The second is a bug fix in the migration constructor of CkReductionMgr, used only during restart from a checkpoint.

1/16 (28998a1): 10.27s <+++++++++++ IMPROVEMENT 1.0% PHIL
2/11 (32f1f5): 9.85s <+++++++++++ IMPROVEMENT 4.1% PHIL

These improvements are potentially surprising, too. The first moves a registration call from class registration to runtime initialization - purely a one-time operation at startup

The second fixes a bug in chare/array element construction. My understanding is that EpiSimdemics has a completely static set of elements after startup, whose locations are fixed since load balancing isn't used. So, I'm baffled to explain a speedup from this.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-25 00:35:24*

---
The hang is not caused by reverting the envelope reduction changes. I just reran the commit prior to that and got a hang on the second try.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-02-25 01:50:33*

---
I isolated the commit (575af7e) that causes the simulation to hang roughly every other time I run it. The hang does not occur on the same iteration across runs. It happens as early as iteration (day) 30, but more typically after 50 - 90 iterations. To verify this is the right commit, I ran with the prior commit several times (so far 7), not noticing any hangs. I will probably run a couple more times, but it looks almost certain that 575af7e is the right commit.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-03-14 17:55:59*

---


The hang happens only with TRAM but not with manual buffering. I tested multiple times with 2500 iterations (as compared to 120 which was default). 

Also, if we enable some debug prints, the hang goes away even in TRAM case.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-15 03:05:21*

---
Hang bug fixed. 

https://charm.cs.illinois.edu/private/tms/listlog.php?param=987

Some sources of regression have likely not been addressed yet, so not closing the issue. But for purposes of release, I think we are fine.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-17 05:30:14*

---
Shuffled the performance regression bits to another issue, to track correctness for 6.6.0 separately.
