### ISSUE TITLE
Nightly manual rebuild

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#36]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/36*

---
Make sure the Charm++ documentation is being built regularly and automatically.

**Comment by ericjbohm** [comment]
*Original date: 2013-02-08 21:09:15*

---
Make cron job to automate this.

Consult Ram about process of building as needed.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-02-11 22:24:05*

---
Moved the cron job to panache. It appears to have run as scheduled, but does not complete due to various errors when running make web in the charm/doc directory. I am handing this off to Ram who is more knowledgable about the manual build process.

**Comment by heyram** [comment]
*Original date: 2013-02-20 22:10:15*

---
Old, dormant manuals like fem, ifem, netfem, mblock will not be built everyday. Instead they're served out of a persistent copy of the manuals that is located under /www/manuals/old/. Likewise, I see there is a bit more housekeeping that needs doing under the charm/doc directory.

Possibly, further TODO: 
- pritish to update charisma manual if / when it is ready for public consumption
- when that happens, it should be reincluded into nightly builds.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-03 06:24:49*

---
Confirmed that the Charm++ manual on the web was built this morning.
