### ISSUE TITLE
Entry methods executed twice/never with periodic load balancing

### ISSUE THREAD

**Issue by kidder** [UIUC-PPL/charm#3605]
A CI failure on https://github.com/sxs-collaboration/spectre/pull/3787 led us to discover this issue with periodic load balancing in version 7 of Charm++

It appears that sometimes an entry method is either executed once before and once after a migration of an array chare element, or fails to get executed at all.  This issue does not happen in version 6.10.2 of Charm++

I have been able to reproduce the problem with a simple Charm++ only example which can be found (with instructions on how to reproduce) at https://github.com/kidder/charm-periodic-lb

The example will fail with random errors of entry methods that are called twice/never instead of once.

Please let me know if there is any additional information you need.

**Comment by rbuch** [comment]
I can reproduce this with your example code, so thanks for that. One oddity, however, is that I can also reproduce this with 6.10.2 (it seems to happen less often with that, though).

Also, I'm only ever seeing the error manifest itself as an even number of unexpected counts where the total sum of counts is correct, e.g.:

```
Pingee 0 unexpected count 2 on iteration 3 for pinger 6
Pingee 0 unexpected count 0 on iteration 4 for pinger 2
```
So I suspect there might be some kind of message or data structure corruption or something when migration happens rather than an entry method being executed an incorrect number of times.

**Comment by rbuch** [comment]
So I've been doing some digging into this, and it seems like it's actually an issue in the broadcast implementation rather than in LB. For example, changing line 96 in ping.C to `pingeesProxy[0].receive_ping(iteration, thisIndex);`, changing the broadcast to a point-to-point send, fixes this for me. Also, getting rid of LB completely and instead doing explicit migrations via `migrateMe(int destination)` while keeping the broadcast fails the check in the same way.

Investigating via git bisect led me to what I think is a red herring: the commit that added TreeLB (#2531), but due to the reasons outlined above, I think this merely revealed the error, but didn't cause it. Further digging led me to (https://github.com/UIUC-PPL/charm/pull/2696), the commit adding node aware broadcasts. This, it turns out, is closer to the fundamental issue, namely that broadcasts seem to rely on implicit ordering based on the order of when they're received (`CkArrayBroadcaster::incoming` just calling `incBcastNo()` and then enqueuing it to `oldBcasts`).

When an object migrates while broadcasts are being created or in flight, Charm++ tries to bring the object up to date when it is resumed on the destination PE (`CkArrayBroadcaster::bringUpToDate` comparing the element's broadcast number with the array broadcaster's broadcast number and delivering queued broadcasts until the element catches up). However, the ordering of broadcasts can be different on different PEs (at least in the SMP cases I've been looking into), so this delivery may redeliver broadcasts that were already delivered on the previous PE before the object migrated or never deliver broadcasts, if they are ordered earlier on the destination than they are on the source.

For now, I've only been able to reproduce this with SMP mode (only with `++ppn >= 2`; this also include `multicore` builds). This may or may not be an issue on non-SMP builds; I seem to recall there is some more intelligent stamping of messages in that case, but I haven't been looking at that part of the code at all yet.

**Comment by rbuch** [comment]
The culprit here seems to be a confluence of two things. In the shift to node aware broadcasts, broadcasts are now performed as a two step procedure, first broadcasting to every node, inserting an entry in each node's node queue. Then, some PE pops that message and enqueues individual entries (that use the same underlying message) to each PE. The problems are these:

1. The node queue -> individual PE queue step can race because there's no synchronization between PEs.. Suppose there are two broadcasts; assuming no randomized queue or anything, they should be popped in FIFO order on every node, but the second broadcast can be enqueued before the first in PE queues if the PE that pops the second node message beats the PE with the first node message to the PE enqueuing part of the code.
2. Even if that step were synchronized, there are multiple queues per PE, and this can cause messages to be processed in a different order. Namely, there are different queues for local messages (self sends) and for sends from other PEs on the node. The order in which these queues are searched may vary depending on the state of the scheduler, but the takeaway is that even if messages are queued in the same order, they may end up being delivered in different orders since they are in different queues.

I've looked into fixing those issues specifically, but after trying some things, I think it's better not to fix those things (they're not really problems, only issues when we need ordered delivery, which in general is antithetical to Charm++'s needs), but add explicit stamping of broadcasts with an ID on the send side.

**Comment by rbuch** [comment]
Talking with @kidder offline, he confirmed that #3614 fixed the issue they were seeing.
