### ISSUE TITLE
Local entry methods of class templates or function templates fail to build

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#3618]
Adding a local entry method to a class template or a local entry method that is a function template produces code like the following:
```cpp
_TRACE_CREATION_DETAILED(&env, CkIndex_AlgorithmArray <ParallelComponent, SpectreArrayIndex> ::template idx_invoke_iterable_action_void<ThisAction, PhaseIndex, DataBoxIndex>());
```
The macro `_TRACE_CREATION_DETAILED` takes two arguments and so the code fails to build. An easy fix for this is to add parentheses around the entire second argument,
```cpp
_TRACE_CREATION_DETAILED(&env, (CkIndex_AlgorithmArray <ParallelComponent, SpectreArrayIndex> ::template idx_invoke_iterable_action_void<ThisAction, PhaseIndex, DataBoxIndex>()));
```
or use some `SINGLE_ARG` macro. 

General question: would it be possible to add test(s) of multi-template parameter chares/classes and member functions? We're planning to add a CI target to SpECTRE that builds Charm++'s `HEAD` so we can catch issues like this as early as possible too.

**Comment by rbuch** [comment]
PR #3620 should fix this by using functions for these instead of macros.

Your suggestion is a good one, having more tests for templated chares/classes that go beyond the simplest cases would be useful to catch things like this. Testing SpECTRE with `HEAD` would also be nice; we may want to add it to our own CI, we already test NAMD and ChaNGa for every PR, but SpECTRE is sufficiently different from both of them that it would probably increase coverage by a meaningful amount.

**Comment by nilsdeppe** [comment]
Yep, that looks like it should do it. Thank you so much for the quick PR!

Agreed! We're doing a bunch of updates on our CI right now anyway, so adding a weekly Charm++ compatibility build shouldn't be too difficult to add :)
