### ISSUE TITLE
ChaNGa failure for 128bit key case

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#375]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/375*

---
Please document whatever this bug actually is(was?) and that the proposed fix has been verified to actually fix the problem.

Also, in the future please submit this sort of thing as a bug in Redmine so we can keep track of it properly.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-12-05 21:00:26*

---
16 byte keys are required for highly clustered cosmological simulations where the height of the barnes-hut oct tree needs to be more than 21, which is the max with 8 byte keys. Using 16 byte keys leads to errors, first noticed on Blue Waters using gni machine layer, due to misalignment of the keys.

Gengbin has checked in a fix, currently under review, which he used to successfully run on Blue Waters. The fix is quite involved, requiring ensuring 16-byte alignment at multiple points in headers, converse and Charm++ envelopes, and at the start of as well as inside varsize messages. I think there are a couple issues left to fix, according to comments I made on gerrit. 

I tried Gengbin's fix on a local workstation for net-linux-x86_64. My program fails at startup.

http://charm.cs.uiuc.edu/gerrit/#/c/14

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-12-07 06:16:53*

---
Found a fix for the startup problem on net-linux-x86_64.

Details: http://charm.cs.uiuc.edu/gerrit/#/c/14/

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-12-08 06:37:24*

---
The startup problem seems to have been due to me running make from the src directory for CkCache rather than from the generated charm++ build directory. This was causing a variable in the Makefile to not get set properly due to the relative path not being correct.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:19:50*

---
Lukasz - I believe this issue was resolved? If so, please close the issue.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-01-03 21:46:03*

---
Gengbin's fix has been reviewed and merged into the repository. ChaNGa now runs fine with 128bit keys enabled.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-03 22:42:58*

---
For bidirectional documentation's sake, the ultimately merged change was http://charm.cs.uiuc.edu/gerrit/#/c/20/
