### ISSUE TITLE
Running AMR with Metabalancer exits unexpectedly

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#377]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/377*

---
When I run AMR (charmgit:users/alanger/amr branch abstract3d) with metabalancer enabled, I see it exit early with the following unexpected messages in its output:
```
$ qsub -A BGQtools_esp -n 32 --mode c32 -t 15 ../advection 7 16 50 3 +MetaLB
. . .
[0] In DistribtuedLB strategy
[607] LBDB::Migrate: Handle 42 no longer registered, range 0-49
[650] LBDB::Migrate: Handle 45 no longer registered, range 0-49
```
I'm guessing this has something to do with attempting to migrate chares that were deleted after load balancing started. If so, it seems the solution would be to just skip over those chares when distributing or processing migration instructions.

**Comment by harshithamenon** [comment]
*Original date: 2015-02-09 21:49:45*

---
This particular error is unlikely due to Metabalancer because it does not deal with migration.

But that being said, there is a bug associated with Metabalancer and AMR when there is deletion and insertion of array elements.

Error!!! Reduction is intermingled between iteration 7.000000         and 9.000000
------------- Processor 2 Exiting: Called CmiAbort ------------
Reason: Intermingling iterations in MetaBalancer

**Comment by PhilMiller** [comment]
*Original date: 2015-02-25 05:15:49*

---
So, with the change in http://charm.cs.uiuc.edu/gerrit/569, what's the status of running AMR with `+MetaLB`?

**Comment by PhilMiller** [comment]
*Original date: 2015-02-25 23:19:47*

---
The merged change seems to not build if the load balancing infrastructure is compiled out:
http://charm.cs.illinois.edu/autobuild/cur/uth-linux-x86_64.txt

**Comment by PhilMiller** [comment]
*Original date: 2015-07-09 19:26:58*

---
The build break got resolved in http://charm.cs.uiuc.edu/gerrit/633

I'm assuming the changes committed and merged ultimately allow AMR to run with `+MetaLB`
