### ISSUE TITLE
Broken recent commit history link

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#391]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/391*

---
Per Jim,

> Hi,
>
> The "Recent Commit Activity" link on http://charm.cs.illinois.edu/help still
> points to http://charm.cs.illinois.edu/cgi-bin/gitweb.cgi?p=charm.git
> rather than http://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git
>
> Jim
>

Instructions to update webpage are at: https://wiki.engr.illinois.edu/display/ppl/Deploy+the+PPL+website

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-08 16:24:36*

---
Assigning to Jonathan because there was confusion regarding the instructions on the web - which branch to update? I would prefer if Jonathan verifies the instructions and then reassigns for updating the link.

**Comment by lifflander** [comment]
*Original date: 2014-01-08 21:01:36*

---
Due to the priority of the task I have completed it quickly myself. However, I don't really know what the confusion is regarding the instructions. Changes are to be made on the "master" branch and then ported to the release branch "charmweb-1.0", because it has charm server configuration/paths etc. baked in for the release.

Nikhil Jain wrote:
> Assigning to Jonathan because there was confusion regarding the instructions on the web - which branch to update? I would prefer if Jonathan verifies the instructions and then reassigns for updating the link.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-08 21:15:02*

---
Confirmed new link is in place.
