### ISSUE TITLE
Potentially wrong re-assignment of alignment macro in persist-comm

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#393]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/393*

---
From ICC (and probably other compilers, but I noticed it there):
```
../bin/charmc  -optimize -production   -c -I. persist-comm.c
In file included from persist-comm.c(12):
converse.h(39): warning #47: incompatible redefinition of macro "ALIGN16" (declared at line 11 of "persist-comm.c")
  #define ALIGN16(x)         CMIALIGN(x,16)
          ^

```

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-14 17:09:10*

---
ALIGN16 is in persist-comm.c for a while. The one in converse.h is just added (Dec-03).  If you decide to use ALIGN16 in the converse.h, the easy way to fix this problem is just to remove the macro in persist-comm.c , and instead we can use the one in converse.h

**Comment by PhilMiller** [comment]
*Original date: 2014-01-14 17:11:56*

---
You own that code. Make sure the one in converse.h serves the same purpose, decide what's best, and just do it.
