### ISSUE TITLE
Topology aware spanning trees broken on XE6

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#484]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/484*

---
Noting that it was not enabled, I experimented with enabling this features in spanningTreeStrategy.h and it crashed during OpenAtom startup.  Probably replicable in the section test code.  Bug is due to some mishandling of a mesh with holes in it.  Not all that urgent, but it would be better if it worked.

**Comment by juanjgalvez** [comment]
*Original date: 2016-10-18 18:13:07*

---
Fix is currently in branch juan/section-spanning-tree

Will submit to gerrit as soon as I do some code cleanup.

Also note that the algorithm has been improved so that it forms a tree of physical nodes. Before, there could be multiple tree branches coming into the same node.

**Comment by juanjgalvez** [comment]
*Original date: 2017-02-21 18:39:42*

---
Fix here:
~~https://charm.cs.illinois.edu/gerrit/#/c/2078/~~ https://github.com/UIUC-PPL/charm/commit/cc36ac6c56529069f5c3e4eb33fbdce1bf3ff2e6

But I'll just note that this fix is probably irrelevant given the new spanning tree code I will submit soon.
