### ISSUE TITLE
static linking breaks on multicore builds with 'undefined reference to `get_myaddress''

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#522]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/522*

---
On an NVIDIA ARM64 machine, --with-production works but -optimize gives link error:

../../../bin/charmc  -language charm++ -o hello hello.o
../../../bin/../lib/libck.a(debug-charm.o): In function `hostInfo(void*, void*, CpdListItemsRequest*)':
debug-charm.C:(.text+0x40): undefined reference to `get_myaddress'
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /home-2/jphillips/NAMD_CVS-2014-06-18_Source/charm-6.6.0-rc3/multicore-arm7/tests/charm++/simplearrayhello
   Command g++ -D_REENTRANT -rdynamic -o hello -L../../../bin/../lib -I../../../bin/../include ../../../bin/../lib/libldb-rand.o hello.o moduleinit29126.o ../../../bin/../lib/libmemory-default.o ../../../bin/../lib/libthreads-default.o -lckmain -lck -lconv-cplus-y -lconv-core -lconv-util -lconv-partition -lpthread -lckqt -ldl -lm returned error code 1
charmc exiting...

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 17:33:20*

---
RSA ID for TCBG has expired.  Will get a new one so I can reproduce the bug.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-16 18:14:56*

---
I cannot reproduce this bug on cupertino.  I suspect the actual issue was resolved by other changes in the interim.

I have found numerous compilation bugs arise with high levels of parallelization on the make (-j or -j8).  Those seem to be compiler crashes in gcc, probably due to memory constraints. I'd consider those upstream bugs rather than charm bugs.  I'm reluctant to try to enforce low levels of parallel compilation as the environmental toolchain issues may be resolved in subsequent releases. 

Building with -j2 has been safe so far.

**Comment by stwhite91** [comment]
*Original date: 2016-12-20 06:42:49*

---
This same error happens when building examples/ampi/Cjacobi3D with -tlsglobals on multicore-linux64 and is reproducible there (see autobuild). The common denominators are that these are multicore builds using static rather than dynamic linking ('-tlsglobals' implicitly passes '-static' to the linker).

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:43:14*

---
It would seem that the thing to do about this would be to statically link everything with the exception of `libc`. This may take some careful trickery in how we do the linking setup, but would also resolve some other warnings we've seen.

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-20 20:38:40*

---
I am unable to reproduce this. My command was:

./build AMPI multicore-linux-x86_64 -j4 --no-build-shared -optimize && pushd multicore-linux-x86_64/examples/ampi/Cjacobi3D && make test TESTOPTS="++local"

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-26 20:28:53*

---
Proposing closure unless the issue can be reproduced.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-10 22:11:51*

---
Closing because the issue has not been reproduced.
