### ISSUE TITLE
Change default shell from rsh to ssh

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#553]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/553*

---
Currently, the default remote shell Charm++ tries to use is rsh, which has largely fallen out of favor, having been replaced with ssh.  The default shell in Charm should be changed to reflect this.

[GTC_rsh.o1547594](https://github.com/UIUC-PPL/charm/files/3536506/GTC_rsh.o1547594.txt)

**Comment by pplimport** [comment]
*Original author: Anonymous*
*Original date: 2014-10-03 07:03:47*

---
Initial investigation:
 1) changes need to be done in charm/src/util/charmrun-src/charmrun.C
 2) arch using rsh 
    net-linux-cell,mpi-darwin-x86_64,multicore-aix-ppc,multicore-arm7,multicore-cygwin,multicore-darwin-x86,multicore-darwin-x86_64,multicore-linux-ppc,multicore-linux32,multicore-linux64,net-aix-ppc,net-cygwin,net-darwin-x86,net-darwin-x86_64,net-linux,net-linux-arm7,net-linux-ia64,net-linux-ppc,net-linux-x86_64,net-sol,net-sol-x86,net-sol-x86_64,netlrts-darwin-x86_64,netlrts-linux,netlrts-linux-x86_64,sim-linux,uth-linux,uth-linux-x86_64,verbs-linux-x86_64
 3) HP-UX has the command remsh instead of rsh

Suggested changes.
 1) Macro renaming 
    CMK_RSH_IS_A_COMMAND to CMK_SSH_IS_A_COMMAND
    RSH_CMD to SHELL_CMD
    CMK_USE_RSH to CMK_USE_SSH
    CMK_RSH_NOT_NEEDED to CMK_SSH_NOT_NEEDED
 2) changing env CONV_RSH to CONV_SHELL (we still need to have CONV_RSH for backward compatibility but can remove it from documents and encourage users to use CONV_SHELL)
 3) Do we need the below macros? CMK_RSH_USE_REMSH is always defined to 0 in the source tree. Also, this is a HP-UX specific macro. I don't see any hp-ux folder in the ARCH directory. So, do we support hp-ux?

```
<code class="C">
    #  if CMK_RSH_USE_REMSH
    #    define RSH_CMD "remsh"
    #  endif
</code>
```


Current Progress:
 1) tested in taub after making the below change. One of the runs timed out. The verbose output of charmrun is attached. I don't think this is due to the change I did.  

```
 <code>
 #  if CMK_RSH_IS_A_COMMAND
-#    define RSH_CMD "rsh"
+#    define RSH_CMD "ssh" 
 #  endif
 </code>
```

 2) Need to test on other machines. Any suggestions?

**Comment by PhilMiller** [comment]
*Original date: 2014-10-03 14:51:24*

---
HP-UX is long defunct for HPC purposes. You can start out by deleting any relics specific to supporting HP-UX, simplifying other bits that were complicated for its benefit, and then adjusting your plan accordingly.

Also, you may be able to avoid the hang you saw by passing one or both of the options `++batch 10` (to limit how many connections charmrun will start and look for reverse connections from at a time) and `++timeout 120` (to tell charmrun to wait a bit longer to get those connections).
