### ISSUE TITLE
Built-in reducer types for logical and bitvec and/or/xor on bools and ints

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#557]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/557*

---
I am cleaning up Jacobi example and I found that logical_and does not perform as it should.  I reproduce this in a simple example. 
```
hello.ci

mainmodule hello {
  readonly CProxy_Main mainProxy;
  readonly int nElements;

  mainchare Main {
    entry Main(CkArgMsg *m);
  };

  array [1D] Hello {
    entry Hello(void);
    entry void SayHi(int hiNo);
    entry [reductiontarget] void recvConvergeResult(bool result);
  };
};


hello.C

#include <stdio.h>
#include "hello.decl.h"

/*readonly*/ CProxy_Main mainProxy;
/*readonly*/ int nElements;

/*mainchare*/
class Main : public CBase_Main
{
public:
  Main(CkArgMsg* m)
  {
    //Process command-line arguments
    nElements=5;
    if(m->argc >1 ) nElements=atoi(m->argv[1]);
    delete m;

    //Start the computation
    CkPrintf("Running Hello on %d processors for %d elements\n",
       CkNumPes(),nElements);
    mainProxy = thisProxy;

    CProxy_Hello arr = CProxy_Hello::ckNew(nElements);

    arr.SayHi(17);
  };

  void done(void)
  {
    CkPrintf("All done\n");
    CkExit();
  };
};

/*array [1D]*/
class Hello : public CBase_Hello
{
public:
  Hello()
  {
    CkPrintf("Hello %d created\n",thisIndex);
  }

  Hello(CkMigrateMessage *m) {}
 void recvConvergeResult(bool result)
  {
    if(result)
      printf("------ result true \n");
    else
      printf("------ result false\n");
    if(thisIndex == 0)
      CkExit();
  }


  void SayHi(int hiNo)
  {
    bool conv;
    if(thisIndex%2 == 0)
    {
      conv = true;
      CkPrintf("true Hi[%d] from element %d\n",hiNo,thisIndex);
    }
    else
    {
      conv = false;
      CkPrintf("false Hi[%d] from element %d\n",hiNo,thisIndex);
    }
    CkCallback cb(CkReductionTarget(Hello, recvConvergeResult), thisProxy);
    contribute(sizeof(bool), &conv, CkReduction::logical_and, cb);
  }
};

#include "hello.def.h"
```

To run it 
>  ./hello 4 

The result should be false, however it shows true.

**Comment by nikhil-jain** [comment]
*Original date: 2014-10-06 21:57:31*

---
Remaining part of the discussion on this topic from email posted to provide complete context:

On Sun, Oct 5, 2014 at 11:37 PM, Phil Miller <mille121`illinois.edu> wrote:
We definitely can't just change the definition of the existing operator, because that would break existing code using it. We could easily enough add logical_{and,or}_bool that applied to bools. If we do that, we should perhaps also define logical_{and,or}_int synonymous with the current operators, and change the documentation to use the explicit versions.

In the longer term, it would probably be good to move toward a fully typed reduction contribution interface, to match up with the typed [reductiontarget] receivers.

On Sun, Oct 5, 2014 at 11:33 PM, Yanhua Sun <sun51`illinois.edu> wrote:
Okay. I did not notice this.   The question is whether we should make logical_and works with bool.

Yanhua

On Sun, Oct 5, 2014 at 11:20 PM, Nikhil Jain <nikhil.life`gmail.com> wrote:
The manual mentions that the logical operators only works on integer data here.

On Sun, Oct 5, 2014 at 11:16 PM, Yanhua Sun <sun51`illinois.edu> wrote:
yeah integer works.   But doing logical_and for bool is very common to use.  We need to fix this, or at least in manual to tell users not to use bool 

Yanhua

On Sun, Oct 5, 2014 at 11:11 PM, Nikhil Jain <nikhil.life`gmail.com> wrote:
I think the problem is contribution of a bool; logical_and reducer expects an integer to be contributed...though not sure why would that lead to incorrect answer.

--Nikhil

**Comment by stwhite91** [comment]
*Original date: 2016-08-30 15:41:00*

---
Supporting more datatypes for logical reduction operations in Charm will benefit AMPI too.

**Comment by stwhite91** [comment]
*Original date: 2016-09-13 19:32:06*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1841/~~ https://github.com/UIUC-PPL/charm/commit/4159d512960e2749b7b17098df75925e36645f92
