### ISSUE TITLE
Charm++ integrate and integrate2 examples

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#568]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/568*

---
Cleanup integrate integrate2 and integrate array examples, merge if needed

**Comment by ericjbohm** [comment]
*Original date: 2016-02-15 18:10:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1051/~~ https://github.com/UIUC-PPL/charm/commit/53f75b46ac14b8291d87314fc8582d913312fbd3

integrate2 (now integratePUPable) is just the integrate example extended to also demonstrate a use of PUP::able that improves overall flexibility in a way that could be useful in a variety of solvers like this.

Revised defaults and makefiles so that all the integrate examples produce the same results.
    
Renamed integrate2 to integratePUPable as that is a more useful moniker.
 
Added README for integratePUPable.
