### ISSUE TITLE
jacobi-sdag

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#613]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/613*

---
No body.

**Comment by epmikida** [comment]
*Original date: 2015-02-09 19:19:31*

---
There is no "test" target in the makefile. All of the targets in the test file are related to fault tolerance, and only run when Charm++ is built with fault tolerance enabled. Otherwise they crash due to bad command line parsing.

**Comment by epmikida** [comment]
*Original date: 2015-02-10 17:37:42*

---
Both this and bug 429 were resolved by the fix for bug 654. There are now warning messages when you pass in flags that don't apply to the current build of charm, so when these tests fail on incorrect builds it will be clear why. This test will stay in the tests directory because it is meant as a fault tolerance test, which is why it has fittest targets but no test target.
