### ISSUE TITLE
CkLoop produces unhelpful Projections traces

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#648]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/648*

---
When a PE is running in CkLoop code, the Projections traces don't accurately reflect the work getting done, and instead show essentially nothing there.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-29 21:16:24*

---
CkLoop is just executing a regular function , not entry method. That is why its display is useless.  What we can do is probably add some user event.  Is this enough for you to use?

**Comment by PhilMiller** [comment]
*Original date: 2015-01-29 21:26:21*

---
Given that CkLoop is an integral feature of the runtime system, work done under it should show up as 'native' in Projections, not as a user event. That work should probably be attributed to the entry methods and objects that spawned it.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-29 21:39:15*

---
Projections does not trace it because currently we use converse notification message.  There is another option to use Charm notification message, which is off by default.
Before we fix this, it is better to figure out in which case we can use charm notification. If it can be used to replace converse notification, this bug is solved naturally. If charm notification is not useful, then we should remove that part of code.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-02-09 21:28:39*

---
Although enabling the charm notify message should fix it, using charm notify msg causes more overhead. Instead, we add special handling for converse message for ckloop to pretend there is entry method for the messages. Explicit tracing is added.  Refer to http://charm.cs.uiuc.edu/gerrit/512

**Comment by PhilMiller** [comment]
*Original date: 2015-07-09 19:28:55*

---
The linked change in Gerrit seems to need a little more work before it can get merged.

Or should we just merge it, since it's an improvement on the current state of things, and open a separate issue for the lack of causality tracking?
