### ISSUE TITLE
MetaLB: Separate cost/benefit analysis for running LB strategy and performing migration

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#65]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/65*

---
MetaLB potentially has two separate decisions to make as execution proceeds:
1. Is current load imbalance bad enough to justify the cost of running the load balancing strategy to compute new assignments?
2. Having obtained new better-balanced assignments, is the improvement they would offer enough to justify the cost of migration they would entail?

We may need to carry object size information (as reported by the sizing PUPper) in the load balancing database to allow estimation of migration costs as soon as decisions are made. Alternately, we can transmit the decisions and compute the expected time cost in a distributed fashion (max over network model, some more detailed contention-based estimate, simulation, etc.).

**Comment by kavithachandrasekar** [comment]
*Original date: 2018-04-04 20:03:01*

---
Estimation of migration costs is already included in the model based method to select Load balancing strategy. So this issue is somewaht subsumed by ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/1914/~~ https://github.com/UIUC-PPL/charm/commit/27eaa51c4c55bde8f66541b747e9cdea92165794

**Comment by kavithachandrasekar** [comment]
*Original date: 2018-08-07 22:46:59*

---
The MetaBalancer patch has been merged. The random forest model will be updated to include more training runs. Chare pup size feature will also be included as a hint for migration cost in the updated model.
