### ISSUE TITLE
spurious data error in charm++ megatest all-at-once

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#655]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/655*

---
From bleeding-edge multicore-linux64/tests/charm++/megatest:

 test 53: initiated [all-at-once]
 Starting test
 Created detector, starting first detection
 Started first test
 farray[0] should be -677737249374208.00000000, is instead 0.00000000
 Finished second test
 Started third test
 test 53: completed (0.01 sec)

This happened the first two times I ran the binary then went away, but if I run in a loop it can be reproduced readily:

 jim`sunnyvale$while ( 1 ) 
 while? ./pgm +p16 | grep "should be"
 while? end
 farray[0] should be -2608215359488.00000000, is instead 0.00000000
 farray[0] should be 48203218734703958489090823815168.00000000, is instead 0.00000000
 farray[0] should be -734031659589429760492568576.00000000, is instead 0.00000000
 farray[6] should be -11339757616944247734272.00000000, is instead 0.00000000
 farray[0] should be -3166479646117296960751432897147174912.00000000, is instead 0.00000000
 farray[0] should be -12349194655895239470283703608934400.00000000, is instead 0.00000000
 farray[0] should be -612.85351562, is instead 0.00000000
 farray[0] should be -171647234113273856.00000000, is instead 0.00000000
 farray[0] should be 670081470169088.00000000, is instead 0.00000000
 farray[2] should be -40412608.00000000, is instead 0.00000000
 farray[0] should be -155755.25000000, is instead 0.00000000
 farray[0] should be -43943169676625838080.00000000, is instead 0.00000000
 farray[0] should be 43867101064169783296.00000000, is instead 0.00000000
 farray[8] should be 2638821195776.00000000, is instead 0.00000000

This is on CentOS 6.5 with gcc 4.4.7 on a 16-core (32-hyperthread) workstation.

I see this output is reversed in varraystest.C, varsizetest2.C, and varsizetest.C:

      CkPrintf("farray[%d] should be %0.8f, is instead %0.8f\n",i,farray[i],2.0*i*i*seqnum);

Also, the conditional logic for detecting the errors seems wrong:

    if((fabs(farray[i]) - fabs(2.0*i*i*seqnum))>10.0) {

The fabs() should be around the difference, not the individual values, and use a relative error rather than 10.0.

Finally, the test values for the first pass (seqnum == 0) are all zero.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 20:41:50*

---
Pass to Eric for reassignment.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 22:30:26*

---
Difficult bug to replicate on lab machines.  Will explore other hardware.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-16 22:15:06*

---
On further investigation varsizetest2 was found to be a flawed translation of varsizetest.  The original did its value initialization in the alloc method.    The newer version has no alloc method as it was designed to test the code path without a custom alloc.  However, it failed to translate the data initialization over.  Probably because initialization as a side effect in a method called alloc() is counter intuitive and the flow of control in megatest is so baroque that it is easy to overlook how things are done.  

Therefore the check() copied from varsizetest was examining data that had not been initialized.  Some of the time the data would actually be "right" because it was using memory which had been initialized by varsizetest, or because the correct answer was 0 and the allocator was providing zero'd data.  The actual check method was not enforcing a failure when the data was inconsistent.   Presumably because the check method ran into occasional failures that were never satisfactorily debugged.
