### ISSUE TITLE
ampi/megampi test fails with randomized queues

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#668]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/668*

---
See parent task for full details.

**Comment by PhilMiller** [comment]
*Original date: 2015-08-17 18:12:28*

---
Reproduced and captured record/replay logs. Will attempt to run under charmdebug to understand what goes wrong.

**Comment by PhilMiller** [comment]
*Original date: 2016-05-29 17:24:04*

---
Passing off an AMPI bug

**Comment by PhilMiller** [comment]
*Original date: 2016-06-27 18:53:13*

---
Per the parent task, 


```
./build AMPI net-linux-x86_64 --with-prio-type=int --enable-randomized-msgq -j16 --suffix randq-debug -O3 -g
```


`ampi/megampi`: Crashes rarely due to a failed assertion: `Broadcast integer from master> expected 123, got 4!`

It might be worthwhile to try the various mpich-test, imb, and other conformance tests under randomized queues. If we see more failures, those would be indicative of substantial robustness issues that we'll have to face, or subject users to potential unpredictable failures/wrong results.

**Comment by stwhite91** [comment]
*Original date: 2016-06-27 21:11:55*

---
I built as above and ran megampi for 1000 iterations 10 times (>1 hour), and got no failures. None from mpich-tests/coll that I tried either. I can try IMB.
