### ISSUE TITLE
alignmentCheck test fails for netlrts-darwin-x86_64-smp build

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#670]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/670*

---
I could not reproduce this error, but the alignmentCheck test in tests/charm++/alignment/ failed in the nightly autobuild for netlrts-darwin-x86_64-smp:

https://charm.cs.illinois.edu/autobuild/cur/netlrts-darwin-x86_64-smp.txt

To test run: ./charmrun +p2 ./alignmentCheck ++local

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-19 22:24:52*

---
This is being caused by clang doing nasty thing for the following comparison:

startHdr < startEnv

Even with sane values, its inverting the expected output.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-20 05:45:22*

---
A deep dive into reading assembly code confirms that clang is producing incorrect assembly.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-20 05:50:39*

---
Unexpected, certainly. We need to be much more thorough before we can say that it's wrong to produce it.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-20 05:52:38*

---
Agreed, but it seems that way. I will see if we get time to briefly discuss this tomorrow.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-20 17:08:19*

---
Happens with Apple's Clang derived from upstream version 3.2. Doesn't happen with MacPorts clang-mp-3.3, and I can't install the clang-3.2 port on my Mac laptop due to version incompatibilities. Also doesn't happen with clang-3.5 or clang-3.6 on other systems. The code also doesn't trigger the Undefined Behavior Sanitizer at all. I'm now much more inclined to agree that this is a wrong-code generation bug in the older compiler.

To address this on our machines, we'll need Xcode upgraded to at least 5.0 from the current 4.6.x (per http://en.wikipedia.org/wiki/Xcode). I'll ask Yanhua to do that on Wit.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-20 20:18:34*

---
My earlier attempts at reproduction were flawed. It happens even on later compiler versions, with either distribution.

We concluded that the pointer arithmetic in question was potentially undefined behavior, and replaced it with integer arithmetic:
http://charm.cs.uiuc.edu/gerrit/#/c/559/
