### ISSUE TITLE
AMPI fails reading binary file I/O using gfortran

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#673]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/673*

---
This could be related to the build flags. It fails on all machines doing big endian file I/O using gfortran.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2015-02-19 19:33:04*

---
gfortran has command line argument -fconvert=conversion for converting binary formats. This only works if it is used in the main program. Since AMPI's main program is compiled separately, and it is in C, I don't think we can make this command line argument work for our ampif90 script.

Solution:

Use the environment variable: GFORTRAN_CONVERT_UNIT='big_endian' ./a.out
