### ISSUE TITLE
Isomalloc performance bug on Hopper

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#681]
*Original author: Ehsan Totoni*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/681*

---
Lulesh 2.0 is 2-3 times slower on Hopper when run with iso-malloc. The repository is at benchmarks/lulesh.git.

**Comment by stwhite91** [comment]
*Original date: 2015-03-05 18:44:36*

---
I don't have access to Hopper, but one potential problem when running on Cray machines with Isomalloc Heap is that by default the GNI network layer wants to use 8MB huge pages. Isomalloc Heap allocates a page to each separate object that the application code wants to put on the heap. This means that if the application is allocating many small arrays or pointers to structs that we are suffering internal fragmentation in each 8MB page and getting poor locality / TLB usage. As you increase the amount of overdecomposition/virtualization each core will want to touch many different pages. You can lessen this effect by using 4KB pages and building AMPI with the 'regularpages' option.

We should do some benchmarking to quantify this effect. I'm not sure if the tests on Hopper were run with huge pages or if it used much heap data, but this is one thing to watch out for when using isomalloc heap (instead of pup) and the GNI net layer.

Edit: nevermind. Isomalloc does not allocate memory the way I thought above. Fragmentation is not an issue at the granularity of pages but within smaller power-of-two sized slots that it manages.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-12 20:29:08*

---
What we probably should have done a long while ago is instantiate an actual memory allocator atop isomalloc to work within the heap segment that isomalloc provisions.

**Comment by PhilMiller** [comment]
*Original date: 2016-03-18 21:25:55*

---
It would be useful to have current data on whether isomalloc introduces substantial slowdown relative to other memory allocators on more current uGNI systems. If not, Hopper was retired last year, and so this bug can be Rejected.
