### ISSUE TITLE
MPI_Register fortran pointer

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#682]
*Original author: Ehsan Totoni*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/682*

---
One cannot register a fortran pointer with MPI_Register since it expects a pointer to a pointer which is not possible in Fortran.

[ftn_pup.tar](https://github.com/UIUC-PPL/charm/files/3536533/ftn_pup.tar.txt)

**Comment by stwhite91** [comment]
*Original date: 2015-03-05 19:27:43*

---
Here is an example AMPI Fortran90 with a pup routine for a pointer to a derived type. Instructions on how to run it are in the Makefile.

**Comment by stwhite91** [comment]
*Original date: 2015-03-14 16:58:42*

---
The issue is that pointers in Fortran are pass by value while non-pointers are pass by reference.

The work-around for this issue is to encapsulate all Fortran pointers that need to be pup'ed inside a derived type and pass an object of that type to MPI_Register.

**Comment by PhilMiller** [comment]
*Original date: 2015-04-30 18:47:35*

---
I accidentally included this in the mass "target to 6.7" - you can decide whether this is directly solvable or not, and whether it's important in that time frame.

**Comment by stwhite91** [comment]
*Original date: 2015-08-19 04:22:27*

---
I don't see any direct solution. Fortran AMPI applications should wrap pointers in derived types and pass that to MPI_Register.
