### ISSUE TITLE
CkLoop doesn't build on Windows or Solaris

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#701]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/701*

---
CkLoop is calling __sync_add_and_fetch(), which breaks builds on Solaris and Windows:

```
 c:\cygwin64\usr\tmp\charm-6.6.1-build-2015-mar-13-197553-multicore-win64\charm-6.6.1\multicore-win64\tmp\libs\ck-libs\ckloop\CkLoop.h(92) : error C3861: '__sync_add_and_fetch': identifier not found
 c:\cygwin64\usr\tmp\charm-6.6.1-build-2015-mar-13-197553-multicore-win64\charm-6.6.1\multicore-win64\tmp\libs\ck-libs\ckloop\CkLoop.h(97) : error C3861: '__sync_add_and_fetch': identifier not found
 CkLoop.C(2) : fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
```

**Comment by PhilMiller** [comment]
*Original date: 2015-03-19 20:24:26*

---
Converse startup knows how to launch OS threads, because it does so for SMP builds. We should use the common (OS-portable) infrastructure to bring up whatever threads CkLoop wants to create. This may require some refactoring to expose an interface that lets the creator control what function the new thread runs.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-19 20:31:50*

---
Separate bug copied to a separate issue.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:24:07*

---
~~https://charm.cs.illinois.edu/gerrit/669~~ https://github.com/UIUC-PPL/charm/commit/95e91c699d5a8aba6a6157936b4a4692eae97974
