### ISSUE TITLE
Enable user-specified initial mappings of AMPI ranks to cores

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#712]
*Original author: Cyril Bordage*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/712*

---
The purpose of exposing the chare array, which AMPI threads are bounds to, is to be able to map AMPI threads during the execution of the application.

**Comment by stwhite91** [comment]
*Original date: 2015-06-25 16:10:04*

---
I am unsure of who wants to use this work now that Cyril is gone, but I have an implementation of it sitting in the branch 'ehsan/ampi-interop'. I added a MPI_Init_with_mapping() API that you can pass a CkArrayMap into in order to set the underlying Chare array mapping.

**Comment by stwhite91** [comment]
*Original date: 2017-01-17 04:36:09*

---
No user of this, and the implementation is sitting on Ehsan's interop branch if need be.
