### ISSUE TITLE
tsan hangs for smp build of charm

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#713]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/713*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2015-04-16 13:38:45*

---
Which exact build, and what compiler and version, and what OS? What command line and options? This must be relatively new, since I've used TSAN in the not-too-distant past.

**Comment by pplimport** [comment]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original date: 2015-05-16 20:25:33*

---
Was able to reproduce a hang with `megatest` on `netlrts-linux-x86_64-smp-tsan` using gcc's threadsanitizer (4.9.2) launched as follows:

```
./charmrun ./pgm +p4 ++ppn 2 ++verbose ++local
```

I had to modify `conv-mach.sh` like so:

```
CMK_CC="gcc $CMK_AMD64 -pie -fPIC"
CMK_CXX="g++ $CMK_AMD64 -pie -fPIC"
```

Didn't test the `darwin` builds since Apple clang (`clang-425.0.28`) doesn't seem to support `-fsanitize=thread` yet (at least the version on Wit.)
