### ISSUE TITLE
Allow running with ++debug ++local

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#754]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/754*

---
For obscure reasons, launching a Charm++ application with each process under the control of a gdb session in an xterm requires that the launching be done through ssh connections, even if they're all to be run on the local machine. There's no reason charmrun shouldn't be able to just `fork()/exec()` the corresponding bits directly.

**Comment by ericjbohm** [comment]
*Original date: 2015-09-18 21:09:47*

---
I can shed some light on why this was not supported out of the box.

The ++local feature short circuits the rather intricate launch process that writes a script for execution by remote ssh, to instead use fork and execve.

The presence of a script in the former process vastly simplifies certain aspects of modifying the command line.

Modifying the command line for an execve is orders of magnitude more finicky.  For example, there are several ways to get it wrong which will result in crashing your entire X Desktop session.  I can't even begin to explain how annoying it is to debug code that does that.

Ironically, the most annoying part of it is that the first parameter to execve must be a file.  Which means you not only have to get the absolute path for the xterm binary, you have to do so in a cross platform way.  There is no POSIX standard for that. <-- finding a cross platform solution that where we are currently stuck in this implementation. 

Furthermore, in order to pass the arguments through to gdb, you can't just prepend gdb to the command line, you have to reformulate them to pass them through the -ex parameter as set args commands, or write them as set args commands in a file which is then passed as an argument to the -x argument.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-18 21:12:18*

---
For $PATH, special-casing Linux and OS X should be enough. Windows is a second-class development citizen anyway.

For `gdb`, look at the `--args` flag.

**Comment by ericjbohm** [comment]
*Original date: 2015-09-18 21:21:09*

---
 
I've got the gdb thing already solved.  That was only mildly annoying. --args is somewhat newer, new enough that its not in the gdb manpage.  Using the older -ex scheme as I expect it will be better supported for now.  Also we have to pass commands through to gdb to support the ++debug-no-pause functionality, so --args isn't enough regardless.

 I'll start with a PATH navigation search and we'll see how far that takes us.h

**Comment by ericjbohm** [comment]
*Original date: 2015-09-18 22:22:12*

---
Pushed implementation to gerrit.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-18 22:22:54*

---
Please link here, to make bi-directional navigation easier.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:19*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
