### ISSUE TITLE
AMPI net-linux-x86_64-smp segfaults at migration

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#824]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/824*

---
See Jenkins nightly builds numbered: 569 - 549 (and beyond)

http://poise:8080/job/Nightly-Build/label=linux,platform=net-linux-x86_64-smp/

**Comment by mprobson** [comment]
*Original date: 2015-09-01 20:58:20*

---
http://charm.cs.illinois.edu/autobuild/cur/ seems to suggest that this can work but further investigation (maybe of options) is necessary

**Comment by stwhite91** [comment]
*Original date: 2015-09-02 20:52:04*

---
The failures for the net-linux-x86_64 smp build are all from 3 tests:

1) tests/ampi/megampi failed for different combinations of +p and +vp options with "Charmrun> error on request socket to node 'localhost'--".
I could not reproduce these failures, though they are pretty consistent since build #549.

2) tests/charm++/chkpt failed during application startup
Failures resulted from the initial bugfix for registering command line options not being thread-safe, but this has since been fixed.

3) examples/ampi/Cjacobi3D failed during migration using PUP
- I could not reproduce these failures, which have occurred in builds 579 and 580.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-04 01:35:14*

---
This is indeed caused by non-uniformity in isomalloc regions. In non SMP mode, if stack randomization is off, all processes are likely to find the same common region. This isn't true for SMP. With multiple threads present, a few mallocs here and there can disrupt the regions found by different processes. +isomalloc_sync is a solution, but we need to do something about it using FS for synchronizing.

**Comment by stwhite91** [comment]
*Original date: 2015-10-13 17:49:27*

---
This failure is to be expected when running on SMP without synchronizing isomalloc memory regions first, as Nikhil described. Michael added +isomalloc_sync to the the AMPI tests on net-smp for Jenkins.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 20:31:08*

---
Wasn't code merged in the repo. Changing to make filtering clearer.

**Comment by PhilMiller** [comment]
*Original date: 2016-04-19 17:05:26*

---
Could isomalloc on SMP builds maybe spit out a warning that users should really use `+isomalloc_sync` or expect very likely crashes?

**Comment by stwhite91** [comment]
*Original date: 2016-04-19 18:50:37*

---
Warning added here:  ~~https://charm.cs.illinois.edu/gerrit/#/c/1150/~~ https://github.com/UIUC-PPL/charm/commit/1b71206ec658e1581f9ee5bcfb816c6249f81a2b
