### ISSUE TITLE
mpi smp build is locked to one core per node by default

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#833]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/833*

---
Repeat by:
build ChaNGa mpi-linux_x86_64 smp ...
Compile changa
Run a test on (e.g.) stampede with "ibrun ChaNGa ++ppn 15 test.param
Note that it is an order of magnitude slower that it should be; also logging in to a compute node shows only one core is running while the load is 16.
Adding "+cpuaffinity +commap 0 +pemap 1-15" gets it running at full speed, but charm should do something sensible when these options are not included.

I also suspect this is a problem for the GNI builds.

**Comment by jcphill** [comment]
*Original date: 2015-10-06 20:59:11*

---
Does adding this to the job script fix the problem?
export OMP_NUM_THREADS=16

Cray's aprun does have similar issues.

It would be good for the smp/multicore builds to detect at startup that the cpu mask is limited to a single core (or insufficient cores) and treat this as a fatal error if cpu affinity options are not set.

NAMD also refuses to run smp builds with ppn 1.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-04 20:47:40*

---
Basically, look at whatever code handles `+pemap` currently. In there, if no `+pemap` argument was provided, have each PE examine its CPU affinity mask. If there are multiple PEs assigned uniquely to a single CPU, then we should detect that and at least print a warning, if not error out entirely.

If that case happens even with `+pemap`, we may still want to warn about potentially inadvertent oversubscription, and recommend adjusting options or if it's intentional, the passing `+CmiSleepOnIdle` so that they won't interfere as badly.

**Comment by juanjgalvez** [comment]
*Original date: 2016-01-14 18:19:10*

---
I have implemented a solution for this issue.

I added a function called checkAffinity in cpuaffinity.c that checks if there are multiple PEs assigned to the same core (currently only on physical node 0). This check is performed whether affinity options have been specified or not. If affinity options weren't set by the user or calculated by charm++ the function will abort if it detects oversubscription. Otherwise it will print a warning if there is oversubscription.

Note that checkAffinity requires cputopology to be enabled, so it's necessary to change ck-core/init.C to initialize cputopology before cpuaffinity.

Currently the check is very simple and will not detect oversubscription in many cases, but it probably will in all instances we are interested in. The check consists in doing an OR of the cpu sets of PEs in the physical node, and checking that the size of the resulting set is greater or equal to the number of PEs. I also implemented an algorithm which detects most (all?) oversubscription cases but it's C++ and cpuaffinity module is C. The algorithm is simple but I feel implementing it in C would make it unnecessarily complex (I'm using std::vector to dynamically store PE affinities in a specific way). cputopology.C is C++ so not sure if we can also make cpuaffinity.c C++ or if it's worth it, or maybe we can just stick to the simple check.

Tested this running jacobi3d test on SMP mode across multiple lab machines and on Bluewaters (4 physical nodes). Haven't encountered any issues.

On Bluewaters I ran cases where the system assigns all threads to core 0 and it detects it accordingly. I also tested specifying a good and bad pemap and also acts accordingly in both cases.

**Comment by PhilMiller** [comment]
*Original date: 2016-01-14 19:08:29*

---
Porting cpuaffinity from C to C++ should be totally fine, and is well justified if it simplifies implementation of desired features.

On the other hand, getting this check in a small, simple patch would make porting it into a 6.7.1 patch release much easier.

**Comment by juanjgalvez** [comment]
*Original date: 2016-01-26 17:11:23*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1030/~~ https://github.com/UIUC-PPL/charm/commit/ee083cc56aa0ddd5a57016c39170f2b052e4e54e

**Comment by stwhite91** [comment]
*Original date: 2016-08-04 18:39:58*

---
Bump: this has been stuck in gerrit since March

**Comment by juanjgalvez** [comment]
*Original date: 2016-08-04 18:57:10*

---
I sort of agreed with Eric to wait until hwloc changes are finalized, since this is going to bring changes to cputopology and cpuaffinity. I will merge my patch with these additions if appropiate.

**Comment by stwhite91** [comment]
*Original date: 2017-04-04 20:53:42*

---
Since we won't have hwloc integration for the release, I think it would be good to get this into 6.8.0 if it is ready?

**Comment by stwhite91** [comment]
*Original date: 2017-04-25 20:57:22*

---
Eric Bohm will test this on a machine that is known to have bad default mapping

**Comment by PhilMiller** [comment]
*Original date: 2017-04-25 20:59:56*

---
We're not immediately going to worry about the case where the user gives a bad pemap/commap argument set.

**Comment by juanjgalvez** [comment]
*Original date: 2017-05-04 17:13:52*

---
Code hangs on Blue Waters with multiple processes per node.

Problem is, the first process on the node doesn't receive any messages from the other processes on the node. For some reason, having the commthreads in a loop doing `CmiNetworkProgress` doesn't work on CRAYXE. Instead, in order for messages to actually be sent you need to let the commthreads go through charm init

But the problem now would be achieving synchronization between threads... several parts of charm init do CmiNodeAllBarrier, but for my code to work, the comm threads shouldn't encounter any more such barriers, because if the comm threads stop, my code hangs.

From what I have seen in cpuaffinity and cputopology, the code avoids using converse communication for crayxe. So, not sure how to fix it right now.

there don't seem to be anymore CmiNodeAllBarrier after doing cpuaffinity initialization, only this block:
```
#if CMK_USE_PXSHM && ( CMK_CRAYXE || CMK_CRAYXC ) && CMK_SMP
    // for SMP on Cray XE6 (hopper) it seems pxshm has to be initialized
    // again after cpuaffinity is done
    if (CkMyRank() == 0) {
      CmiInitPxshm(argv);
    }
    CmiNodeAllBarrier();
#endif
```

which isn't enabled by default. An option could be, for cray-specific code, let commthreads exit cpuaffinity and assume they will finish charm init and won't block, but this assumption might not hold in the future?

**Comment by juanjgalvez** [comment]
*Original date: 2017-05-10 23:01:29*

---
Posted a new patch in gerrit.

Should work on all architectures, including Cray because it does not rely on the NetworkProgress call.

Also there was a very rare race condition which happened infrequently on netlrts-linux which caused segfault due to converse attempting to process a message for which a handler had not been registered yet. Solved it for netlrts and made a change which should make it very difficult to happen in other architectures (haven't actually analyzed the code to see if it can still potentially happen or not).

Have tested on Blue Waters and netlrts-linux with multiple processes per physical node and it's working.
