### ISSUE TITLE
multicore-win64 doesn't build.

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#837]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/837*

---
Investigate if this compiler failure. Mostly likely it is same as 489.

[fix_win64.patch](https://github.com/UIUC-PPL/charm/files/3536564/fix_win64.patch.txt)
[fix_win64.patch.1](https://github.com/UIUC-PPL/charm/files/3536563/fix_win64.patch.1.txt)

**Comment by jcphill** [comment]
*Original date: 2015-09-24 21:10:41*

---
I just finished installing Visual Studio Professional 2013 and with a simple change from 11 to 12 and 8.0 to 8.1 in the vcvars64 file it
seems to work, but I get the following error:

C:\PROGRA~2\MICROS~2.0\VC\Include\xmemory0(611) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1325)

Updating to Visual Studio Professional 2013 with Update 5 and also changing win8 to winv6.3 in the vcvars64 fixes it, but now I get the
following for multicore-win64:

../bin/charmc  -optimize -production   -I. -o machine.o  -DFOR_CPLUS=1 machine.c
machine.c
c:\cygwin64\tmp\charm-6.7.0-pre\multicore-win64\tmp\sockRoutines.h(119) : error C2371: 'sleep' : redefinition; different basic types

What seems to be happening is that CmiNodeBarrierCount() calls sleep(0) in machine-smp.c before it is defined, which is OK in a .c file as
it is assumed to be int (int), but then it is redefined in sockRoutines.h.  The fix seems to be including sockRoutines.h in machine-smp.c
right after machine-smp.h, althoug I'm not sure if this breaks other platforms.

I then get two link errors from multicore-win64:

libconv-cplus-y.a(machine.o) : error LNK2019: unresolved external symbol pthread_exit referenced in function LrtsExit
libconv-cplus-y.a(machine.o) : error LNK2019: unresolved external symbol _Cmi_sleepOnIdle referenced in function CmiNotifyStillIdle

These appear to be from assuming that smp implies pthreads.

**Comment by jcphill** [comment]
*Original date: 2015-09-24 21:11:04*

---
Also, the mpi machine.c has it's own definition of sleep(), which interferes with the one I added to sockRoutines.h.  After removing it
mpi-win64 builds, but not ckloop.

**Comment by jcphill** [comment]
*Original date: 2015-09-25 12:56:45*

---
One last failure on multicore-win64:

if [ -f charmrun ] ; then ( cp -f charmrun ../bin ) ; fi
cp: cannot create regular file `../bin/charmrun': File exists
Makefile:431: recipe for target 'charmrun-target' failed

The error happens because cygwin tries to treat executables foo and foo.exe interchangeably, so it is trying to overwrite bin/charmrun.exe with tmp/charmrun.

What will succeed is "cp -f charmrun ../bin/charmrun.exe" but cp is apparently not smart enough to remove charmrun.exe when trying to copy charmrun, although it's probably better to avoid building the binary charmrun for multicore, which doesn't use it.

**Comment by jcphill** [comment]
*Original date: 2015-09-29 23:07:58*

---
The attached patch gets multicore-win64 to build, but when based on netlrts simplearrayhellp hangs on startup.  Switching src/arch/multicore/gdir_link from netlrts to net allows it to run.  Is there a way to redirect only multicore-win64 to use net while the rest of the multicore builds are based on netlrts?

**Comment by jcphill** [comment]
*Original date: 2015-09-29 23:35:50*

---
Updated patch also fixes mpi-win64.

**Comment by jcphill** [comment]
*Original date: 2015-09-30 15:29:27*

---
The reason multicore is building charmrun is that in src/arch/net/Makefile.machine we have:

	if [ ! -f charmrun ]; then \
			(cd charmrun-src ; $(MAKE) OPTS='$(OPTS) -Wno-error' -j1) ; fi

while src/arch/netlrts/Makefile.machine does not check for the existence of a charmrun script.

**Comment by rbuch** [comment]
*Original date: 2015-10-06 18:33:24*

---
Cannot currently login to dexterity.  Will test fixes when I can access the machine.

**Comment by jcphill** [comment]
*Original date: 2015-10-20 14:10:18*

---
Please merge ~~https://charm.cs.illinois.edu/gerrit/#/c/855/~~ https://github.com/UIUC-PPL/charm/commit/5332fd8d48bdd3666f50bd7ff6fedae714043e74 as it fixes the charmrun issue for all multicore builds based on netlrts.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-20 20:01:59*

---
Some of the bits of patch Jim submitted have been integrated. The rest need to be broken out and submitted for merge.

**Comment by rbuch** [comment]
*Original date: 2015-10-26 22:22:16*

---
Gerrit Link: ~~https://charm.cs.illinois.edu/gerrit/#/c/886/~~ https://github.com/UIUC-PPL/charm/commit/4941bd0fc11f5a8d556263465228f573cbfc6b4d

**Comment by bilgeacun** [comment]
*Original date: 2015-10-27 18:54:08*

---
The hanging problem after applying Jim's patch which was caused by a problem in the exit call. It was not a hang in the start-up as Jim reported earlier. The failure in the exit call was preventing any prints to appear.

In Jim's patch the exit call was changed to ExitThread(0). This function kills the thread's process(if it's the last thread) as well as the threads. Hence we see that hang in the exit.

We should find another thread safe way to exit. Since pthreads do not exist in Windows platform, we cannot use the thread safe pthread_exit function for multicore-win builds. As a *temporary* fix, we simply use exit(0) call. This was implemented and merged in the posted gerrit patch.

According to Windows documentation, [[https://msdn.microsoft.com/en-us/library/windows/desktop/ms682659(v=vs.85).aspx]], if the thread *returns* from it's function calls, it will terminate. So we may simply return instead of calling exit. However this solution may not be as simple as it sounds because of the structure of the function calls.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 19:43:07*

---
`ExitThread()` sounds like it does exactly what we need it to do, just as `pthread_exit()` does. I don't understand why the one should cause hangs at shutdown but not the other.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 19:44:01*

---
Perhaps we should open a new bug/cleanup issue to look into the ExitThread issue and possibly move to that, if necessary.

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-27 19:48:33*

---
Phil Miller wrote:
> `ExitThread()` sounds like it does exactly what we need it to do, just as `pthread_exit()` does. I don't understand why the one should cause hangs at shutdown but not the other.

Windows differentiates between threads and processes. We only create n-1 threads, but calls Exitthread n times.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:26*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
