### ISSUE TITLE
thread migration (as in megampi) crashes on all darwin builds

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#838]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/838*

---
net-darwin-x86_64, netlrts-darwin-x86_64, net-darwin-x86_64-smp, netlrts-darwin-x86_64-smp also crash in megaampi. Find the cause. Mostly likely missing isomalloc_sync.

**Comment by stwhite91** [comment]
*Original date: 2015-09-30 00:06:31*

---
Added +isomalloc_sync to test commands for Darwin builds on autobuild and jenkins, but the problem persists... The error is reproducible on all {net, netlrts}-darwin-x86_64{-smp} builds in tests/ampi/megampi running ./charmrun +p{>1} ./pgm +vp{>0} ++local.

**Comment by stwhite91** [comment]
*Original date: 2015-10-22 19:43:53*

---
The issue was with the Jcontext threads implementation in src/utils/uJcontext.c, which makes an unsafe assumption that the compiler will use the frame pointer to reference local variables. LLVM on Darwin x86_64 is using the stack to reference local variables instead. Context threads do not have this problem, so I changed that to be the default.


~~https://charm.cs.illinois.edu/gerrit/869~~ https://github.com/UIUC-PPL/charm/commit/fae32e530dbf8fe5c91bfee2e9d8138f1fa1b464

**Comment by PhilMiller** [comment]
*Original date: 2015-10-23 14:29:21*

---
Apparently, context threads break other tests :-(

See if there's at least one of the thread packages that behaves reasonably on the entire test suite. If not, we'll need  to put in more work to get one of them working.

**Comment by stwhite91** [comment]
*Original date: 2015-10-23 15:05:13*

---
context threads break the megatest/synctest, but passes megampi, while uJcontext threads break megaampi but pass megatest/synctest.

I tried all other threads libraries and none of the ones that build on darwin pass the megampi test, so we'll have to look into this further.

**Comment by stwhite91** [comment]
*Original date: 2015-10-26 17:10:07*

---
Switching the default threads library on darwin builds to uJcontext and then using the portable alloca method in uJcontext instead of the darwin-x86_64-specific mov instruction (which breaks on Clang and possible other compilers) seems to fix the main issue of running with user-level threads on darwin builds.

However, there is an issue with Isomalloc PUP routines on Darwin now, so thread migration fails.

~~https://charm.cs.illinois.edu/gerrit/#/c/872/~~ https://github.com/UIUC-PPL/charm/commit/af3199a81bd382f029a4c7bdd881244be0ccad55

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 02:01:02*

---
Oh, I see, not quite. Sorry for the noise.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-10 21:21:08*

---
The lack of thread migratability support on Darwin is non-critical, since we don't expect large or distributed runs that need load balancing enabled there. We'll need some solution just to not have the failing tests get in the way or confuse users.

**Comment by stwhite91** [comment]
*Original date: 2015-12-02 16:19:15*

---
To clarify, we fixed the issue with runs like './charmrun +p1 ./pgm +p2' but we are still seeing failures in MPI_Init for runs like './charmrun +p2 ./pgm +vp2' and failures at migration time for runs like './charmrun +p2 ./pgm +vp1'.
The failures in migration across PEs are likely an effect of the same bug that fails in MPI_Init for runs with multiple PEs.

What's weird is that if we run with ++debug, all cases run correctly. Seems like a race condition or memory allocation/alignment issue...

**Comment by nikhil-jain** [comment]
*Original date: 2015-12-04 22:28:04*

---
SInce scalable start made the master branch run fine, Phil suggested that we may need to disable ASLR. I tried with  OPTS=-Wl,-no_pie link time, and that may be the solution we need.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-05 20:32:18*

---
Could you try that patch on a baseline without `++scalable-start` enabled? It would be good to see if this independently fixes the issue across the range of cases.

**Comment by stwhite91** [comment]
*Original date: 2015-12-05 21:33:29*

---
Yes, adding -Wl,-no_pie to CMK_LD and CMK_LDXX and turning off scalable-start, all tests pass. (The alloca change is also unnecessary with the new patch, though it doesn't hurt either...)

**Comment by PhilMiller** [comment]
*Original date: 2015-12-05 21:38:39*

---
Cool. Could you submit that patch in gerrit please?

**Comment by stwhite91** [comment]
*Original date: 2015-12-05 22:11:50*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/943/~~ https://github.com/UIUC-PPL/charm/commit/dabea3dba78481aa9bcc6f110dc1d1d24d4d7f6f
