### ISSUE TITLE
Get rid of unnecessary yields within AMPI_Test* and AMPI_Wait* routines

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#933]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/933*

---
When test is called on any nonblocking request, the calling thread yields. Not sure if this is optimal, especially when Waitany is called which yields for every test.

**Comment by stwhite91** [comment]
*Original date: 2015-12-28 07:16:15*

---
We can optimize the MPI_Waitany implementation to not yield when testing each request for completion but only once we find that no requests have completed. However, the general case of MPI_Test needs to yield the calling thread since the following case is allowed by the standard:

```
MPI_Irecv(..., &req);

do {
    MPI_Test(&req, &flag, &status);
} while ( ! flag );
```

In AMPI, if we don't yield to the scheduler, this case will hang. I need to check on other AMPI functions that call AMPI_Test as well.

**Comment by nikhil-jain** [comment]
*Original date: 2015-12-28 15:47:25*

---
I had similar thoughts and agree to what Sam said.

**Comment by nikhil-jain** [comment]
*Original date: 2015-12-31 04:41:26*

---
Another improvement to Waitany could be something I did in this commit:

https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=7ffccd1103663c80feefe8e2efe3c6fdec108636

My motivation was to reduce trace size for cases where waits run for long, but I can see performance benefits of this approach.

**Comment by stwhite91** [comment]
*Original date: 2016-01-04 19:58:45*

---
Changing the way we yield in Waitany (and possibly others) to only re-enqueue an AMPI thread once it has actually received a message (like Nikhil's suggestion above) can be done in a separate commit. My initial commit for the problem of yielding unnecessarily is in Gerrit here: ~~https://charm.cs.illinois.edu/gerrit/#/c/977/~~ https://github.com/UIUC-PPL/charm/commit/fb1c60b1b766bbd4427b3c0d5e5e929ba436cbed

**Comment by stwhite91** [comment]
*Original date: 2016-01-09 20:18:16*

---
Still working on Nikhil's suggestion for more efficient resumeOnRecv scheme for AMPI_Waitany. Will open a new feature for that and close this one.
