### ISSUE TITLE
Memory affinity autodetection doesn't work on RHEL 5

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#935]
*Original author: Tom Coles*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/935*

---
After compiling with --with-numa in SMP mode, memory affinity nodemap auto detection doesn't work on RHEL 5: there are error messages saying that the corresponding NUMA node is not found.

The explanation is in the use of popen in memoryaffinity.c, specifically in CmiNumNUMANodes and getNUMANidByRank. It seems that this use of popen is not thread-safe with Charm++ on RHEL 5, as garbage is returned in most threads most of the time.

The use of popen is just for convenience to obtain directory information using ls, but I would suggest instead doing this directly with C code. In particular, CmiNumNUMANodes could be obtained simply by using numa_max_node()+1, as numa.h is already included anyway.

It would also be possible to calculate getNUMANidByRank using a function from numa.h, but the libnuma API has changed over the years and so this would not be compatible with all systems. Instead, I suggest traversing the directory structure with readdir().

I have attached a patch with these changes. It should be applied to src/conv-core/memoryaffinity.c

[memaffinity.patch](https://github.com/UIUC-PPL/charm/files/3536582/memaffinity.patch.txt)

**Comment by ericjbohm** [comment]
*Original date: 2016-02-15 20:47:11*

---
A very slightly modified version of Tom Coles' patch is pushed as gerrit ~~https://charm.cs.illinois.edu/gerrit/#/c/1060/~~ https://github.com/UIUC-PPL/charm/commit/d8fc771af5cb64351403c4156cc98d779bfed599

Note: in order to actually test this code your system needs the libnuma API installed (libnuma-dev package on ubuntu) and build charm --with-numa, and run +setcpuaffinity +maffinity +mempol bind  (or other valid policy options).
