### ISSUE TITLE
OFI Layer

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#975]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/975*

---
Integration of OFI layer implemented by Intel. Test and make it work on the Cisco cluster.

The initial patch from the integration is here: https://charm.cs.illinois.edu/gerrit/#/c/1047/

It currently does not work on the Pacini cluster.

**Comment by bilgeacun** [comment]
*Original date: 2016-02-15 20:55:08*

---
Progress of fixes: https://charm.cs.illinois.edu/gerrit/#/c/1059/

**Comment by bilgeacun** [comment]
*Original date: 2017-02-01 18:36:10*

---
Version 2 patch is here: https://charm.cs.illinois.edu/gerrit/#/c/1945/

**Comment by bilgeacun** [comment]
*Original date: 2017-08-01 21:01:13*

---
The newest version of the patch from Intel is here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2759/~~ https://github.com/UIUC-PPL/charm/commit/c0c86a6eb043a3dcf4910f1268caccf15a5cade4
Previous patches are abandoned.

Also, assigning the feature to Nitin who is doing the testing of the new patch.

**Comment by nitbhat** [comment]
*Original date: 2017-08-16 15:02:57*

---
The current patch shows decent performance improvements over the MPI build on both Stampede2 and Bridges. 

This patch includes the use of a cache for the OFI machine specific metadata (OFIRequest) and a memory pool similar to the one used in the gni layer. However, since the performance improvements with the cache and the mempool weren't significant, I've disabled the use of the cache and mempool for now. 

Results from the OFI layer patch: 
1. Initial results with cache enabled and no mempool : https://docs.google.com/spreadsheets/d/1T7yNr_cObWqR7dgiN14hXyvv1dnwG-79quF4wGUIObg/edit?usp=sharing
2. Results comparing cache and no-cache implementations : https://docs.google.com/spreadsheets/d/1AqursBrFjjIPJb7I1AYB8rBhWtevHR5CcA4ku4--Uo8/edit?usp=sharing
3. Results comparing mempool and no-mempool implementations : https://docs.google.com/spreadsheets/d/1wC089wF4ZWoAJINU9DFOQUhTGr2FXzdBaJbatE4ToAY/edit?usp=sharing

**Comment by jcphill** [comment]
*Original date: 2017-08-16 17:39:55*

---
Do you have any synthetic performance tests besides ping-pong?
If you can make this compatible with the 6.8.0 head I can test it with NAMD.

**Comment by nitbhat** [comment]
*Original date: 2017-08-16 17:49:57*

---
Other than pingpong, I haven't done any other synthetic performance tests. 
I have tested it on NAMD, ChaNGa and Openatom (for a few smaller nodes). The tabs in the botton of the spreadsheets have results from these.
