### ISSUE TITLE
charmrun should not ignore +ppn

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#988]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/988*

---
In net/verbs layer, it seems like passing +ppn to charmrun does not have any effect.

**Comment by stwhite91** [comment]
*Original date: 2017-11-04 17:54:35*

---
Reassigning to Evan since he's been working on charmrun

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-04 21:42:53*

---
++ppn (two pluses) is working fine. Should +ppn (one plus) work in the same circumstances as ++ppn?

**Comment by jcphill** [comment]
*Original date: 2018-01-05 02:23:40*

---
Rejected why?  Does charmrun silently ignore +ppn?  It should either accept it or throw an error.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-08 20:46:43*

---
The convention for command line arguments appears to be that options with a single plus "+" are reserved for the Charm runtime system to handle as part of the node program, while two-plus "++" options belong to Charmrun. Charmrun's argument passing code makes an exception for arguments a single character long, and "+p" is currently the only single-character argument. "+ppn" with one plus has never been a part of Charmrun's vocabulary. This is how things stand as of Charm master today, assuming netlrts or verbs:

Charm standalone, non-SMP
+p --> (error)
++p --> (error)
+ppn --> (error)
++ppn --> (error)

Charmrun, non-SMP
+p --> total PEs = total nodes
++p --> total PEs = total nodes
+ppn --> (error)
++ppn --> (error)

Charm standalone, SMP
+p --> total PEs = PEs per node
++p --> (error)
+ppn --> total PEs = PEs per node
++ppn --> total PEs = PEs per node

Charmrun, SMP
+p --> total PEs
++p --> total PEs
+ppn --> (error)
++ppn --> PEs per node

I don't know if the intent behind Charmrun's support for one-plus "+p" is an ease of use feature for users, or more akin to the GNU convention of "-" for single characters and "--" for multiple. I am not sure of the value of adding support for "+ppn", since pairs of +p and ++ppn values do not mean the same thing between standalone and Charmrun.

**Comment by jcphill** [comment]
*Original date: 2018-01-09 00:01:41*

---
Producing an error is sufficient.  Silently ignoring an option is not.

The confusion is that platforms that don't use charmrun (IBM, Cray, MPI, OFI) require passing +ppn to the application binary.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-09 20:43:36*

---
If an error is sufficient, I am marking this resolved.
